package com.bfrc.pojo.tire.jda;

// Generated Nov 23, 2007 4:02:41 PM by Hibernate Tools 3.2.0.beta8

/**
 * BrandImage generated by hbm2java
 */
public class BrandImage implements java.io.Serializable {

	// Fields    

	private long brandId;

	private byte[] image;

	// Constructors

	/** default constructor */
	public BrandImage() {
	}

	/** minimal constructor */
	public BrandImage(long brandId) {
		this.brandId = brandId;
	}

	/** full constructor */
	public BrandImage(long brandId, byte[] image) {
		this.brandId = brandId;
		this.image = image;
	}

	// Property accessors
	public long getBrandId() {
		return this.brandId;
	}

	public void setBrandId(long brandId) {
		this.brandId = brandId;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

}
