package com.bfrc.pojo.tire.jda;

import java.util.*;

import org.codehaus.jackson.map.annotate.JsonSerialize;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.map.ser.ToStringSerializer;

// Generated Nov 23, 2007 4:02:41 PM by Hibernate Tools 3.2.0.beta8

/**
 * Configuration generated by hbm2java
 */
@JsonSerialize(include = JsonSerialize.Inclusion.NON_DEFAULT)
public class Configuration implements java.io.Serializable, Comparable {

	// Fields    

	private long sku;

	private Mileage mileage;

	private Traction traction;

	private Sidewall sidewall;

	private Display display;

	private Speed speed;

	private Temperature temperature;

	private String crossSection;

	private String aspect;

	private String rimSize;

	private String treadwear;

	private String label;

	private String oemFlag;

	private Long loadIndex;

	private String loadRange;

	private Long DLoadIndex;

	private String ply;

	private Character dd;

    private Set tireWebsources = new HashSet(0);
    
    private Technology technology;

    public Technology getTechnology() {
		return this.technology;
	}

    public void setTechnology(Technology technology) {
		this.technology = technology;
	}

	// Implement Comparable
	public int compareTo(Object arg0) {
		Configuration c = (Configuration)arg0;
		int rimDiff = Integer.valueOf(this.rimSize).intValue() - Integer.valueOf(c.getRimSize()).intValue(); 
		if(rimDiff == 0) {
			String cAspect = c.getAspect();
			String thisAspect = this.aspect;
			if("NONE".equals(cAspect))
				cAspect = "0";
			if("NONE".equals(thisAspect))
				thisAspect = "0";
			int aspectDiff = Integer.valueOf(cAspect).intValue() - Integer.valueOf(thisAspect).intValue();
			if(aspectDiff == 0) {
				int crossDiff = Integer.valueOf(this.crossSection).intValue() - Integer.valueOf(c.getCrossSection()).intValue();
				if(crossDiff == 0) {
					if(this.sidewall != null && c.getSidewall() != null) {
						int sideDiff = (int)(this.sidewall.getId() - c.getSidewall().getId());
						if(sideDiff != 0)
							return sideDiff;
						return fallbackCompare(c);
					}
					return fallbackCompare(c);
				}
				return crossDiff;
			}
			return aspectDiff;
		}
		return rimDiff;
	}
   
	private int fallbackCompare(Configuration c) {
		int labelDiff = this.getLabel().compareTo(c.getLabel());
		if(labelDiff != 0)
			return labelDiff;
		return (int)(this.sku - c.getSku());
	}

    // Constructors

	/** default constructor */
	public Configuration() {
	}

	/** minimal constructor */
	public Configuration(long sku, Mileage mileage, Traction traction,
			Display display, Speed speed, Temperature temperature,
			String crossSection, String aspect, String rimSize,
			String treadwear, String label) {
		this.sku = sku;
		this.mileage = mileage;
		this.traction = traction;
		this.display = display;
		this.speed = speed;
		this.temperature = temperature;
		this.crossSection = crossSection;
		this.aspect = aspect;
		this.rimSize = rimSize;
		this.treadwear = treadwear;
		this.label = label;
	}

	/** full constructor */
	public Configuration(long sku, Mileage mileage, Traction traction,
			Sidewall sidewall, Display display, Speed speed,
			Temperature temperature, String crossSection, String aspect,
			String rimSize, String treadwear, String label, String oemFlag,
			Long loadIndex, String loadRange, Long DLoadIndex, String ply,
			Character dd) {
		this.sku = sku;
		this.mileage = mileage;
		this.traction = traction;
		this.sidewall = sidewall;
		this.display = display;
		this.speed = speed;
		this.temperature = temperature;
		this.crossSection = crossSection;
		this.aspect = aspect;
		this.rimSize = rimSize;
		this.treadwear = treadwear;
		this.label = label;
		this.oemFlag = oemFlag;
		this.loadIndex = loadIndex;
		this.loadRange = loadRange;
		this.DLoadIndex = DLoadIndex;
		this.ply = ply;
		this.dd = dd;
	}

	// Property accessors
	@JsonSerialize(include=JsonSerialize.Inclusion.NON_DEFAULT, using=ToStringSerializer.class)
	public long getSku() {
		return this.sku;
	}

	public void setSku(long sku) {
		this.sku = sku;
	}
	
	public Mileage getMileage() {
		return this.mileage;
	}

	public void setMileage(Mileage mileage) {
		this.mileage = mileage;
	}

	public Traction getTraction() {
		return this.traction;
	}

	public void setTraction(Traction traction) {
		this.traction = traction;
	}

	public Sidewall getSidewall() {
		return this.sidewall;
	}

	public void setSidewall(Sidewall sidewall) {
		this.sidewall = sidewall;
	}

	@JsonIgnore
	public Display getDisplay() {
		return this.display;
	}

	@JsonIgnore
	public void setDisplay(Display display) {
		this.display = display;
	}

	public Speed getSpeed() {
		return this.speed;
	}

	public void setSpeed(Speed speed) {
		this.speed = speed;
	}

	public Temperature getTemperature() {
		return this.temperature;
	}

	public void setTemperature(Temperature temperature) {
		this.temperature = temperature;
	}

	public String getCrossSection() {
		return this.crossSection;
	}

	public void setCrossSection(String crossSection) {
		this.crossSection = crossSection;
	}

	public String getAspect() {
		return this.aspect;
	}

	public void setAspect(String aspect) {
		this.aspect = aspect;
	}

	public String getRimSize() {
		return this.rimSize;
	}

	public void setRimSize(String rimSize) {
		this.rimSize = rimSize;
	}

	public String getTreadwear() {
		return this.treadwear;
	}

	public void setTreadwear(String treadwear) {
		this.treadwear = treadwear;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getOemFlag() {
		return this.oemFlag;
	}

	public void setOemFlag(String oemFlag) {
		this.oemFlag = oemFlag;
	}

	@JsonSerialize(include=JsonSerialize.Inclusion.NON_DEFAULT, using=ToStringSerializer.class)
	public Long getLoadIndex() {
		return this.loadIndex;
	}

	public void setLoadIndex(Long loadIndex) {
		this.loadIndex = loadIndex;
	}

	public String getLoadRange() {
		return this.loadRange;
	}

	public void setLoadRange(String loadRange) {
		this.loadRange = loadRange;
	}

	public Long getDLoadIndex() {
		return this.DLoadIndex;
	}

	public void setDLoadIndex(Long DLoadIndex) {
		this.DLoadIndex = DLoadIndex;
	}

	public String getPly() {
		return this.ply;
	}

	public void setPly(String ply) {
		this.ply = ply;
	}

	public Character getDd() {
		return this.dd;
	}

	public void setDd(Character dd) {
		this.dd = dd;
	}

	@JsonIgnore
	public Set getTireWebsources() {
		return this.tireWebsources;
	}

	@JsonIgnore
	public void setTireWebsources(Set tireWebsources) {
		this.tireWebsources = tireWebsources;
	}

}
