package com.bfrc.pojo.tire.jda;
// Generated Nov 23, 2007 4:02:41 PM by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.map.annotate.JsonSerialize;

/**
 * Display generated by hbm2java
 */
@JsonSerialize(include = JsonSerialize.Inclusion.NON_DEFAULT)
public class Display  implements java.io.Serializable {

    // Fields    

     private long id;
     private Brand brand;
     private Segment segment;
     private Category category;
     private Warranty warranty;
     private Class theClass;
     private Tiregroup tiregroup;
     private String value;
     private String description;
     private String generateCatalogPage;
     private Set configurations = new HashSet(0);
     private Set facts = new HashSet(0);
     private Set features = new HashSet(0);
     private boolean onemonthroadtest = false;
     private Technology technology;

     // Constructors

	public Technology getTechnology() {
		return this.technology;
	}

	public void setTechnology(Technology technology) {
		this.technology = technology;
	}

	@JsonIgnore
	public Set getFacts() {
		return this.facts;
	}

	@JsonIgnore
	public void setFacts(Set facts) {
		this.facts = facts;
	}

	@JsonIgnore
	public Set getFeatures() {
		return this.features;
	}

	@JsonIgnore
	public void setFeatures(Set features) {
		this.features = features;
	}

	/** default constructor */
    public Display() {
    }

	/** minimal constructor */
    public Display(long id, Brand brand, Segment segment, Category category, Warranty warranty, Class theClass, Tiregroup tiregroup, String value) {
        this.id = id;
        this.brand = brand;
        this.segment = segment;
        this.category = category;
        this.warranty = warranty;
        this.theClass = theClass;
        this.tiregroup = tiregroup;
        this.value = value;
    }
    /** full constructor */
    public Display(long id, Brand brand, Segment segment, Category category, Warranty warranty, Class theClass, Tiregroup tiregroup, String value, String description, String generateCatalogPage, Set configurations) {
       this.id = id;
       this.brand = brand;
       this.segment = segment;
       this.category = category;
       this.warranty = warranty;
       this.theClass = theClass;
       this.tiregroup = tiregroup;
       this.value = value;
       this.description = description;
       this.generateCatalogPage = generateCatalogPage;
       this.configurations = configurations;
    }
   
    // Property accessors
    @JsonIgnore
    public long getId() {
        return this.id;
    }
    
    @JsonIgnore
    public void setId(long id) {
        this.id = id;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    
    public Segment getSegment() {
        return this.segment;
    }
    
    public void setSegment(Segment segment) {
        this.segment = segment;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Warranty getWarranty() {
        return this.warranty;
    }
    
    public void setWarranty(Warranty warranty) {
        this.warranty = warranty;
    }
    public Class getTheClass() {
        return this.theClass;
    }
    
    public void setTheClass(Class theClass) {
        this.theClass = theClass;
    }
    public Tiregroup getTiregroup() {
        return this.tiregroup;
    }
    
    public void setTiregroup(Tiregroup tiregroup) {
        this.tiregroup = tiregroup;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getGenerateCatalogPage() {
        return this.generateCatalogPage;
    }
    
    public void setGenerateCatalogPage(String generateCatalogPage) {
        this.generateCatalogPage = generateCatalogPage;
    }
    
    @JsonIgnore
    public Set getConfigurations() {
        return this.configurations;
    }
    
    @JsonIgnore
    public void setConfigurations(Set configurations) {
        this.configurations = configurations;
    }

	public boolean isOnemonthroadtest() {
		return this.onemonthroadtest;
	}

	public void setOnemonthroadtest(boolean onemonthroadtest) {
		this.onemonthroadtest = onemonthroadtest;
	}

}


