package com.bfrc.pojo.tire.jda;

// Generated Nov 23, 2007 4:02:41 PM by Hibernate Tools 3.2.0.beta8

/**
 * FactImage generated by hbm2java
 */
public class FactImage implements java.io.Serializable {

	// Fields    

	private long factId;

	private byte[] image;

	// Constructors

	/** default constructor */
	public FactImage() {
	}

	/** minimal constructor */
	public FactImage(long factId) {
		this.factId = factId;
	}

	/** full constructor */
	public FactImage(long factId, byte[] image) {
		this.factId = factId;
		this.image = image;
	}

	// Property accessors
	public long getFactId() {
		return this.factId;
	}

	public void setFactId(long factId) {
		this.factId = factId;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

}
