package com.bfrc.pojo.tire.jda;

// Generated Nov 23, 2007 4:02:41 PM by Hibernate Tools 3.2.0.beta8

/**
 * FactJoinId generated by hbm2java
 */
public class FactJoinId implements java.io.Serializable {

	// Fields    

	private long displayId;

	private long factId;

	// Constructors

	/** default constructor */
	public FactJoinId() {
	}

	/** full constructor */
	public FactJoinId(long displayId, long factId) {
		this.displayId = displayId;
		this.factId = factId;
	}

	// Property accessors
	public long getDisplayId() {
		return this.displayId;
	}

	public void setDisplayId(long displayId) {
		this.displayId = displayId;
	}

	public long getFactId() {
		return this.factId;
	}

	public void setFactId(long factId) {
		this.factId = factId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FactJoinId))
			return false;
		FactJoinId castOther = (FactJoinId) other;

		return (this.getDisplayId() == castOther.getDisplayId())
				&& (this.getFactId() == castOther.getFactId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getDisplayId();
		result = 37 * result + (int) this.getFactId();
		return result;
	}

}
