package com.bfrc.pojo.tire.jda;

// Generated Nov 23, 2007 4:02:41 PM by Hibernate Tools 3.2.0.beta8

/**
 * FeatureJoin generated by hbm2java
 */
public class FeatureJoin implements java.io.Serializable {

	// Fields    

	private FeatureJoinId id;

	// Constructors

	/** default constructor */
	public FeatureJoin() {
	}

	/** full constructor */
	public FeatureJoin(FeatureJoinId id) {
		this.id = id;
	}

	// Property accessors
	public FeatureJoinId getId() {
		return this.id;
	}

	public void setId(FeatureJoinId id) {
		this.id = id;
	}

}
