package com.bfrc.pojo.tire.jda;

// Generated Nov 23, 2007 4:02:41 PM by Hibernate Tools 3.2.0.beta8

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.map.annotate.JsonSerialize;

/**
 * Feature generated by hbm2java
 */
@JsonSerialize(include = JsonSerialize.Inclusion.NON_DEFAULT)
public class Feature implements java.io.Serializable {

	// Fields    

	private long id;

	private String value;

	private String benefit;

	// Constructors

	/** default constructor */
	public Feature() {
	}

	/** minimal constructor */
	public Feature(long id, String value) {
		this.id = id;
		this.value = value;
	}

	/** full constructor */
	public Feature(long id, String value, String benefit) {
		this.id = id;
		this.value = value;
		this.benefit = benefit;
	}

	// Property accessors
	@JsonIgnore
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getBenefit() {
		return this.benefit;
	}

	public void setBenefit(String benefit) {
		this.benefit = benefit;
	}

}
