package com.bfrc.pojo.tire.jda;

// Generated Nov 23, 2007 4:02:41 PM by Hibernate Tools 3.2.0.beta8

/**
 * TechnologyImage generated by hbm2java
 */
public class TechnologyImage implements java.io.Serializable {

	// Fields    

	private long technologyId;

	private byte[] image;

	// Constructors

	/** default constructor */
	public TechnologyImage() {
	}

	/** minimal constructor */
	public TechnologyImage(long technologyId) {
		this.technologyId = technologyId;
	}

	/** full constructor */
	public TechnologyImage(long technologyId, byte[] image) {
		this.technologyId = technologyId;
		this.image = image;
	}

	// Property accessors
	public long getTechnologyId() {
		return this.technologyId;
	}

	public void setTechnologyId(long technologyId) {
		this.technologyId = technologyId;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

}
