package com.bfrc.pojo.tire.jda;

// Generated Nov 23, 2007 4:02:41 PM by Hibernate Tools 3.2.0.beta8

/**
 * TiregroupClass generated by hbm2java
 */
public class TiregroupClass implements java.io.Serializable {

	// Fields    

	private TiregroupClassId id;

	// Constructors

	/** default constructor */
	public TiregroupClass() {
	}

	/** full constructor */
	public TiregroupClass(TiregroupClassId id) {
		this.id = id;
	}

	// Property accessors
	public TiregroupClassId getId() {
		return this.id;
	}

	public void setId(TiregroupClassId id) {
		this.id = id;
	}

}
