package com.bfrc.pojo.tire.jda;

// Generated Nov 23, 2007 4:02:41 PM by Hibernate Tools 3.2.0.beta8

/**
 * TireWebsource generated by hbm2java
 */
public class TireWebsource implements java.io.Serializable {

	// Fields    

	private TireWebsourceId id;

	// Constructors

	/** default constructor */
	public TireWebsource() {
	}

	/** full constructor */
	public TireWebsource(TireWebsourceId id) {
		this.id = id;
	}

	// Property accessors
	public TireWebsourceId getId() {
		return this.id;
	}

	public void setId(TireWebsourceId id) {
		this.id = id;
	}

}
