package com.bfrc.pojo.tire.jda;

// Generated Nov 23, 2007 4:02:41 PM by Hibernate Tools 3.2.0.beta8

/**
 * TiregroupImage generated by hbm2java
 */
public class TiregroupImage implements java.io.Serializable {

	// Fields    

	private TiregroupImageId id;

	private byte[] image;

	// Constructors

	/** default constructor */
	public TiregroupImage() {
	}

	/** minimal constructor */
	public TiregroupImage(TiregroupImageId id) {
		this.id = id;
	}

	/** full constructor */
	public TiregroupImage(TiregroupImageId id, byte[] image) {
		this.id = id;
		this.image = image;
	}

	// Property accessors
	public TiregroupImageId getId() {
		return this.id;
	}

	public void setId(TiregroupImageId id) {
		this.id = id;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

}
