package com.bfrc.pojo.storeadmin;
// Generated Jan 16, 2012 4:18:26 PM by Hibernate Tools 3.2.1.GA



/**
 * BsroCorpUsers generated by hbm2java
 */
public class BsroCorpUsers  implements java.io.Serializable {


     private String emailAddress;
     private String firstName;
     private String lastName;

    public BsroCorpUsers() {
    }

    public BsroCorpUsers(String emailAddress, String firstName, String lastName) {
       this.emailAddress = emailAddress;
       this.firstName = firstName;
       this.lastName = lastName;
    }
   
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }




}


