package com.bfrc.pojo.storeadmin;
// Generated Oct 19, 2011 7:57:34 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

import org.springframework.web.multipart.commons.CommonsMultipartFile;

/**
 * StoreAdminLibraryImage generated by hbm2java
 */
public class StoreAdminLibraryImage  implements java.io.Serializable {

     public long getImageId() {
		return imageId;
	}
	public void setImageId(long imageId) {
		this.imageId = imageId;
	}
	private long imageId;
     private byte[] image;
     private String type;
	private String createdBy;
     private Date createdDate;
     private String modifiedBy;
     private Date modifiedDate;
     private String url;

    public StoreAdminLibraryImage() {
    }
    public StoreAdminLibraryImage(long imageId, Date createdDate) {
        this.imageId = imageId;
        this.createdDate = createdDate;
    }
    public StoreAdminLibraryImage(long imageId, byte[] image, String createdBy, Date createdDate, String modifiedBy, Date modifiedDate) {
       this.imageId = imageId;
       this.image = image;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    private CommonsMultipartFile imageFile;
	public CommonsMultipartFile getImageFile() {
		return this.imageFile;
	}
	public void setImageFile(CommonsMultipartFile imageFile) {
		this.imageFile = imageFile;
	}
    public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	
}


