package com.bfrc.pojo.storeadmin;

// Generated Oct 19, 2011 7:57:34 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

import com.bfrc.pojo.admin.AdminAppsUsersId;

/**
 * StoreAdminOffer generated by hbm2java
 */
public class StoreAdminOffer implements java.io.Serializable {

	private long offerId;
	private String friendlyId;
	private Long templateId;
	private Long promoId;
	private BigDecimal price;
	private BigDecimal percentOff;
	private Integer rollingDatePeriod;
	private Long articleNumber;
	private String createdBy;
	private String validWeekDays;
	private Date createdDate;
	private String modifiedBy;
	private Date modifiedDate;
	private String disclaimer;
	private Integer priority;

	public StoreAdminOffer() {
	}

	public StoreAdminOffer(long offerId, Date createdDate) {
		this.offerId = offerId;
		this.createdDate = createdDate;
	}

	public StoreAdminOffer(long offerId, String friendlyId, Long templateId,
			Long promoId, String brand, BigDecimal price,
			BigDecimal percentOff, Date onlineStartDate, Date onlineEndDate,
			Date startDate, Date endDate, Integer rollingDatePeriod,
			String denyReason, Long articleNumber, String createdBy,
			Date createdDate, String modifiedBy, Date modifiedDate,
			String status, String disclaimer) {
		this.offerId = offerId;
		this.friendlyId = friendlyId;
		this.templateId = templateId;
		this.promoId = promoId;
		this.price = price;
		this.percentOff = percentOff;
		this.rollingDatePeriod = rollingDatePeriod;
		this.articleNumber = articleNumber;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.disclaimer = disclaimer;
	}

	public long getOfferId() {
		return this.offerId;
	}

	public void setOfferId(long offerId) {
		this.offerId = offerId;
	}

	public String getFriendlyId() {
		return this.friendlyId;
	}

	public void setFriendlyId(String friendlyId) {
		this.friendlyId = friendlyId;
	}

	public Long getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(Long templateId) {
		this.templateId = templateId;
	}

	public Long getPromoId() {
		return this.promoId;
	}

	public void setPromoId(Long promoId) {
		this.promoId = promoId;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getPercentOff() {
		return this.percentOff;
	}

	public void setPercentOff(BigDecimal percentOff) {
		this.percentOff = percentOff;
	}

	public Integer getRollingDatePeriod() {
		return this.rollingDatePeriod;
	}

	public void setRollingDatePeriod(Integer rollingDatePeriod) {
		this.rollingDatePeriod = rollingDatePeriod;
	}

	public Long getArticleNumber() {
		return this.articleNumber;
	}

	public void setArticleNumber(Long articleNumber) {
		this.articleNumber = articleNumber;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getDisclaimer() {
		return this.disclaimer;
	}

	public void setDisclaimer(String disclaimer) {
		this.disclaimer = disclaimer;
	}

	public String getValidWeekDays() {
		return validWeekDays;
	}

	public void setValidWeekDays(String validWeekDays) {
		this.validWeekDays = validWeekDays;
	}

	public Integer getPriority() {
		return priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}
	 public boolean equals(Object other) {
		 if ( (other == null ) )
			 return false;
		 if ( !(other instanceof StoreAdminOffer) ) 
			 return false;
		 StoreAdminOffer castOther = ( StoreAdminOffer ) other; 
		 return (this.getOfferId()==castOther.getOfferId());
   }
}
