package com.bfrc.pojo.storeadmin;
// Generated Oct 19, 2011 7:57:34 PM by Hibernate Tools 3.2.1.GA



/**
 * StoreAdminOfferStoreJoinId generated by hbm2java
 */
public class StoreAdminOfferStoreJoinId  implements java.io.Serializable {


     private long offerId;
     private long storeNumber;

    public StoreAdminOfferStoreJoinId() {
    }

    public StoreAdminOfferStoreJoinId(long offerId, long storeNumber) {
       this.offerId = offerId;
       this.storeNumber = storeNumber;
    }
   
    public long getOfferId() {
        return this.offerId;
    }
    
    public void setOfferId(long offerId) {
        this.offerId = offerId;
    }
    public long getStoreNumber() {
        return this.storeNumber;
    }
    
    public void setStoreNumber(long storeNumber) {
        this.storeNumber = storeNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StoreAdminOfferStoreJoinId) ) return false;
		 StoreAdminOfferStoreJoinId castOther = ( StoreAdminOfferStoreJoinId ) other; 
         
		 return (this.getOfferId()==castOther.getOfferId())
 && (this.getStoreNumber()==castOther.getStoreNumber());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getOfferId();
         result = 37 * result + (int)this.getStoreNumber();
         return result;
   }   


}


