package com.bfrc.pojo.storeadmin;
// Generated Oct 19, 2011 7:57:34 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

import org.springframework.web.multipart.commons.CommonsMultipartFile;

/**
 * StoreAdminStoreImage generated by hbm2java
 */
public class StoreAdminStoreImage  implements java.io.Serializable {

     private Long storeNumber;
     private String status;
 	private byte[] image;
	private byte[] bannerImage;
     private String createdBy;
     private Date createdDate;
     private String modifiedBy;
     private Date modifiedDate;

    public StoreAdminStoreImage() {
    }
    public StoreAdminStoreImage(Long storeNumber, Date createdDate) {
        this.storeNumber = storeNumber;
        this.createdDate = createdDate;
    }
    public StoreAdminStoreImage(Long storeNumber, byte[] image, String createdBy, Date createdDate, String modifiedBy, Date modifiedDate) {
       this.storeNumber = storeNumber;
       this.image = image;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
    public Long getStoreNumber() {
		return storeNumber;
	}
	public void setStoreNumber(long storeNumber) {
		this.storeNumber = storeNumber;
	}
    public byte[] getImage() {
        return this.image;
    }
    public void setImage(byte[] image) {
        this.image = image;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    private CommonsMultipartFile imageFile;
	public CommonsMultipartFile getImageFile() {
		return this.imageFile;
	}
	public void setImageFile(CommonsMultipartFile imageFile) {
		this.imageFile = imageFile;
	}
    public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public byte[] getBannerImage() {
		return bannerImage;
	}
	public void setBannerImage(byte[] bannerImage) {
		this.bannerImage = bannerImage;
	}
}


