package com.bfrc.pojo.tirepromotion;
// Generated Jun 12, 2009 11:31:56 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SourcePromotionType generated by hbm2java
 */
public class SourcePromotionType  implements java.io.Serializable {


     private char promoType;
     private String promoTypeDescription;
     private char reducePriceFlag;
     private Set tirePromotionEvents = new HashSet(0);
     private Set tirePromotionEventHistories = new HashSet(0);

    public SourcePromotionType() {
    }

	
    public SourcePromotionType(char promoType, String promoTypeDescription, char reducePriceFlag) {
        this.promoType = promoType;
        this.promoTypeDescription = promoTypeDescription;
        this.reducePriceFlag = reducePriceFlag;
    }
    public SourcePromotionType(char promoType, String promoTypeDescription, char reducePriceFlag, Set tirePromotionEvents, Set tirePromotionEventHistories) {
       this.promoType = promoType;
       this.promoTypeDescription = promoTypeDescription;
       this.reducePriceFlag = reducePriceFlag;
       this.tirePromotionEvents = tirePromotionEvents;
       this.tirePromotionEventHistories = tirePromotionEventHistories;
    }
   
    public char getPromoType() {
        return this.promoType;
    }
    
    public void setPromoType(char promoType) {
        this.promoType = promoType;
    }
    public String getPromoTypeDescription() {
        return this.promoTypeDescription;
    }
    
    public void setPromoTypeDescription(String promoTypeDescription) {
        this.promoTypeDescription = promoTypeDescription;
    }
    public char getReducePriceFlag() {
        return this.reducePriceFlag;
    }
    
    public void setReducePriceFlag(char reducePriceFlag) {
        this.reducePriceFlag = reducePriceFlag;
    }
    public Set getTirePromotionEvents() {
        return this.tirePromotionEvents;
    }
    
    public void setTirePromotionEvents(Set tirePromotionEvents) {
        this.tirePromotionEvents = tirePromotionEvents;
    }
    public Set getTirePromotionEventHistories() {
        return this.tirePromotionEventHistories;
    }
    
    public void setTirePromotionEventHistories(Set tirePromotionEventHistories) {
        this.tirePromotionEventHistories = tirePromotionEventHistories;
    }




}


