package com.bfrc.pojo.tirepromotion;
// Generated Jun 12, 2009 11:31:56 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TirePromotionSite generated by hbm2java
 */
public class TirePromotionSite  implements java.io.Serializable {


     private TirePromotionSiteId id;
     private String lastChangedBy;
     private Date lastChangedDate;

    public TirePromotionSite() {
    }

    public TirePromotionSite(TirePromotionSiteId id, String lastChangedBy, Date lastChangedDate) {
       this.id = id;
       this.lastChangedBy = lastChangedBy;
       this.lastChangedDate = lastChangedDate;
    }
   
    public TirePromotionSiteId getId() {
        return this.id;
    }
    
    public void setId(TirePromotionSiteId id) {
        this.id = id;
    }
    public String getLastChangedBy() {
        return this.lastChangedBy;
    }
    
    public void setLastChangedBy(String lastChangedBy) {
        this.lastChangedBy = lastChangedBy;
    }
    public Date getLastChangedDate() {
        return this.lastChangedDate;
    }
    
    public void setLastChangedDate(Date lastChangedDate) {
        this.lastChangedDate = lastChangedDate;
    }




}


