package com.bfrc.pojo.tirepromotion;
// Generated Jun 12, 2009 11:31:56 AM by Hibernate Tools 3.2.1.GA



/**
 * TirePromotionSiteId generated by hbm2java
 */
public class TirePromotionSiteId  implements java.io.Serializable {


     private long promoId;
     private String siteName;

    public TirePromotionSiteId() {
    }

    public TirePromotionSiteId(long promoId, String siteName) {
       this.promoId = promoId;
       this.siteName = siteName;
    }
   
    public long getPromoId() {
        return this.promoId;
    }
    
    public void setPromoId(long promoId) {
        this.promoId = promoId;
    }
    public String getSiteName() {
        return this.siteName;
    }
    
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TirePromotionSiteId) ) return false;
		 TirePromotionSiteId castOther = ( TirePromotionSiteId ) other; 
         
		 return (this.getPromoId()==castOther.getPromoId())
 && ( (this.getSiteName()==castOther.getSiteName()) || ( this.getSiteName()!=null && castOther.getSiteName()!=null && this.getSiteName().equals(castOther.getSiteName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getPromoId();
         result = 37 * result + ( getSiteName() == null ? 0 : this.getSiteName().hashCode() );
         return result;
   }   


}


