package com.bfrc.pojo.tirepromotion;
// Generated Jun 12, 2009 11:31:56 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;

/**
 * TirePromotionEventHistory generated by hbm2java
 */
public class TirePromotionEventHistory  implements java.io.Serializable {


     private long eventHistoryId;
     private TirePromotionEvent tirePromotionEvent;
     private SourcePromotionType sourcePromotionType;
     private String promoName;
     private BigDecimal promoValue;
     private byte minQualifierQty;
     private Blob promoLargeImg;
     private Blob promoSmallImg;
     private String promoSmallImgText;
     private String promoSmallImgTooltip;
     private String promoDisplayName;
     private String promoTotalTag;
     private String promoUrlName;
     private String promoMainText;
     private String promoFooterText;
     private Blob promoPdf;
     private String promoPdfText;
     private char statusFlag;
     private String lastChangedBy;
     private Date lastChangedDate;

    public TirePromotionEventHistory() {
    }

	
    public TirePromotionEventHistory(long eventHistoryId, TirePromotionEvent tirePromotionEvent, SourcePromotionType sourcePromotionType, String promoName, BigDecimal promoValue, byte minQualifierQty, Blob promoLargeImg, String promoDisplayName, String promoMainText, String promoFooterText, char statusFlag, String lastChangedBy, Date lastChangedDate) {
        this.eventHistoryId = eventHistoryId;
        this.tirePromotionEvent = tirePromotionEvent;
        this.sourcePromotionType = sourcePromotionType;
        this.promoName = promoName;
        this.promoValue = promoValue;
        this.minQualifierQty = minQualifierQty;
        this.promoLargeImg = promoLargeImg;
        this.promoDisplayName = promoDisplayName;
        this.promoMainText = promoMainText;
        this.promoFooterText = promoFooterText;
        this.statusFlag = statusFlag;
        this.lastChangedBy = lastChangedBy;
        this.lastChangedDate = lastChangedDate;
    }
    public TirePromotionEventHistory(long eventHistoryId, TirePromotionEvent tirePromotionEvent, SourcePromotionType sourcePromotionType, String promoName, BigDecimal promoValue, byte minQualifierQty, Blob promoLargeImg, Blob promoSmallImg, String promoSmallImgText, String promoSmallImgTooltip, String promoDisplayName, String promoTotalTag, String promoUrlName, String promoMainText, String promoFooterText, Blob promoPdf, String promoPdfText, char statusFlag, String lastChangedBy, Date lastChangedDate) {
       this.eventHistoryId = eventHistoryId;
       this.tirePromotionEvent = tirePromotionEvent;
       this.sourcePromotionType = sourcePromotionType;
       this.promoName = promoName;
       this.promoValue = promoValue;
       this.minQualifierQty = minQualifierQty;
       this.promoLargeImg = promoLargeImg;
       this.promoSmallImg = promoSmallImg;
       this.promoSmallImgText = promoSmallImgText;
       this.promoSmallImgTooltip = promoSmallImgTooltip;
       this.promoDisplayName = promoDisplayName;
       this.promoTotalTag = promoTotalTag;
       this.promoUrlName = promoUrlName;
       this.promoMainText = promoMainText;
       this.promoFooterText = promoFooterText;
       this.promoPdf = promoPdf;
       this.promoPdfText = promoPdfText;
       this.statusFlag = statusFlag;
       this.lastChangedBy = lastChangedBy;
       this.lastChangedDate = lastChangedDate;
    }
   
    public long getEventHistoryId() {
        return this.eventHistoryId;
    }
    
    public void setEventHistoryId(long eventHistoryId) {
        this.eventHistoryId = eventHistoryId;
    }
    public TirePromotionEvent getTirePromotionEvent() {
        return this.tirePromotionEvent;
    }
    
    public void setTirePromotionEvent(TirePromotionEvent tirePromotionEvent) {
        this.tirePromotionEvent = tirePromotionEvent;
    }
    public SourcePromotionType getSourcePromotionType() {
        return this.sourcePromotionType;
    }
    
    public void setSourcePromotionType(SourcePromotionType sourcePromotionType) {
        this.sourcePromotionType = sourcePromotionType;
    }
    public String getPromoName() {
        return this.promoName;
    }
    
    public void setPromoName(String promoName) {
        this.promoName = promoName;
    }
    public BigDecimal getPromoValue() {
        return this.promoValue;
    }
    
    public void setPromoValue(BigDecimal promoValue) {
        this.promoValue = promoValue;
    }
    public byte getMinQualifierQty() {
        return this.minQualifierQty;
    }
    
    public void setMinQualifierQty(byte minQualifierQty) {
        this.minQualifierQty = minQualifierQty;
    }
    public Blob getPromoLargeImg() {
        return this.promoLargeImg;
    }
    
    public void setPromoLargeImg(Blob promoLargeImg) {
        this.promoLargeImg = promoLargeImg;
    }
    public Blob getPromoSmallImg() {
        return this.promoSmallImg;
    }
    
    public void setPromoSmallImg(Blob promoSmallImg) {
        this.promoSmallImg = promoSmallImg;
    }
    public String getPromoSmallImgText() {
        return this.promoSmallImgText;
    }
    
    public void setPromoSmallImgText(String promoSmallImgText) {
        this.promoSmallImgText = promoSmallImgText;
    }
    public String getPromoSmallImgTooltip() {
        return this.promoSmallImgTooltip;
    }
    
    public void setPromoSmallImgTooltip(String promoSmallImgTooltip) {
        this.promoSmallImgTooltip = promoSmallImgTooltip;
    }
    public String getPromoDisplayName() {
        return this.promoDisplayName;
    }
    
    public void setPromoDisplayName(String promoDisplayName) {
        this.promoDisplayName = promoDisplayName;
    }
    public String getPromoTotalTag() {
        return this.promoTotalTag;
    }
    
    public void setPromoTotalTag(String promoTotalTag) {
        this.promoTotalTag = promoTotalTag;
    }
    public String getPromoUrlName() {
        return this.promoUrlName;
    }
    
    public void setPromoUrlName(String promoUrlName) {
        this.promoUrlName = promoUrlName;
    }
    public String getPromoMainText() {
        return this.promoMainText;
    }
    
    public void setPromoMainText(String promoMainText) {
        this.promoMainText = promoMainText;
    }
    public String getPromoFooterText() {
        return this.promoFooterText;
    }
    
    public void setPromoFooterText(String promoFooterText) {
        this.promoFooterText = promoFooterText;
    }
    public Blob getPromoPdf() {
        return this.promoPdf;
    }
    
    public void setPromoPdf(Blob promoPdf) {
        this.promoPdf = promoPdf;
    }
    public String getPromoPdfText() {
        return this.promoPdfText;
    }
    
    public void setPromoPdfText(String promoPdfText) {
        this.promoPdfText = promoPdfText;
    }
    public char getStatusFlag() {
        return this.statusFlag;
    }
    
    public void setStatusFlag(char statusFlag) {
        this.statusFlag = statusFlag;
    }
    public String getLastChangedBy() {
        return this.lastChangedBy;
    }
    
    public void setLastChangedBy(String lastChangedBy) {
        this.lastChangedBy = lastChangedBy;
    }
    public Date getLastChangedDate() {
        return this.lastChangedDate;
    }
    
    public void setLastChangedDate(Date lastChangedDate) {
        this.lastChangedDate = lastChangedDate;
    }




}


