package com.bfrc.pojo.tirepromotion;
// Generated Jun 12, 2009 11:31:56 AM by Hibernate Tools 3.2.1.GA



/**
 * TirePromotionArticle generated by hbm2java
 */
public class TirePromotionArticle  implements java.io.Serializable {


     private TirePromotionArticleId id;

    public TirePromotionArticle() {
    }

    public TirePromotionArticle(TirePromotionArticleId id) {
       this.id = id;
    }
   
    public TirePromotionArticleId getId() {
        return this.id;
    }
    
    public void setId(TirePromotionArticleId id) {
        this.id = id;
    }




}


