package com.bfrc.pojo.tire.jda2;
// Generated Mar 19, 2011 12:14:12 PM by Hibernate Tools 3.2.1.GA

/**
 * BrandImage generated by hbm2java
 */
public class BrandImage  implements java.io.Serializable {


     private long brandId;
     private byte[] image;

    public BrandImage() {
    }

	
    public BrandImage(long brandId) {
        this.brandId = brandId;
    }
    public BrandImage(long brandId, byte[] image) {
       this.brandId = brandId;
       this.image = image;
    }
   
    public long getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(long brandId) {
        this.brandId = brandId;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


