package com.bfrc.pojo.tire.jda2;
// Generated Mar 19, 2011 12:15:50 PM by Hibernate Tools 3.2.1.GA



/**
 * Configuration generated by hbm2java
 */
public class Configuration  implements java.io.Serializable {


     private long sku;
     private String crossSection;
     private String aspect;
     private String rimSize;
     private long displayId;
     private long mileageId;
     private long speedId;
     private String treadwear;
     private long tractionId;
     private long temperatureId;
     private String label;
     private Long sidewallId;
     private String oemFlag;
     private Long loadIndex;
     private String loadRange;
     private Long DLoadIndex;
     private String ply;
     private Character dd;
     private Long technologyId;

    public Configuration() {
    }

	
    public Configuration(long sku, String crossSection, String aspect, String rimSize, long displayId, long mileageId, long speedId, String treadwear, long tractionId, long temperatureId, String label) {
        this.sku = sku;
        this.crossSection = crossSection;
        this.aspect = aspect;
        this.rimSize = rimSize;
        this.displayId = displayId;
        this.mileageId = mileageId;
        this.speedId = speedId;
        this.treadwear = treadwear;
        this.tractionId = tractionId;
        this.temperatureId = temperatureId;
        this.label = label;
    }
    public Configuration(long sku, String crossSection, String aspect, String rimSize, long displayId, long mileageId, long speedId, String treadwear, long tractionId, long temperatureId, String label, Long sidewallId, String oemFlag, Long loadIndex, String loadRange, Long DLoadIndex, String ply, Character dd, Long technologyId) {
       this.sku = sku;
       this.crossSection = crossSection;
       this.aspect = aspect;
       this.rimSize = rimSize;
       this.displayId = displayId;
       this.mileageId = mileageId;
       this.speedId = speedId;
       this.treadwear = treadwear;
       this.tractionId = tractionId;
       this.temperatureId = temperatureId;
       this.label = label;
       this.sidewallId = sidewallId;
       this.oemFlag = oemFlag;
       this.loadIndex = loadIndex;
       this.loadRange = loadRange;
       this.DLoadIndex = DLoadIndex;
       this.ply = ply;
       this.dd = dd;
       this.technologyId = technologyId;
    }
   
    public long getSku() {
        return this.sku;
    }
    
    public void setSku(long sku) {
        this.sku = sku;
    }
    public String getCrossSection() {
        return this.crossSection;
    }
    
    public void setCrossSection(String crossSection) {
        this.crossSection = crossSection;
    }
    public String getAspect() {
        return this.aspect;
    }
    
    public void setAspect(String aspect) {
        this.aspect = aspect;
    }
    public String getRimSize() {
        return this.rimSize;
    }
    
    public void setRimSize(String rimSize) {
        this.rimSize = rimSize;
    }
    public long getDisplayId() {
        return this.displayId;
    }
    
    public void setDisplayId(long displayId) {
        this.displayId = displayId;
    }
    public long getMileageId() {
        return this.mileageId;
    }
    
    public void setMileageId(long mileageId) {
        this.mileageId = mileageId;
    }
    public long getSpeedId() {
        return this.speedId;
    }
    
    public void setSpeedId(long speedId) {
        this.speedId = speedId;
    }
    public String getTreadwear() {
        return this.treadwear;
    }
    
    public void setTreadwear(String treadwear) {
        this.treadwear = treadwear;
    }
    public long getTractionId() {
        return this.tractionId;
    }
    
    public void setTractionId(long tractionId) {
        this.tractionId = tractionId;
    }
    public long getTemperatureId() {
        return this.temperatureId;
    }
    
    public void setTemperatureId(long temperatureId) {
        this.temperatureId = temperatureId;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    public Long getSidewallId() {
        return this.sidewallId;
    }
    
    public void setSidewallId(Long sidewallId) {
        this.sidewallId = sidewallId;
    }
    public String getOemFlag() {
        return this.oemFlag;
    }
    
    public void setOemFlag(String oemFlag) {
        this.oemFlag = oemFlag;
    }
    public Long getLoadIndex() {
        return this.loadIndex;
    }
    
    public void setLoadIndex(Long loadIndex) {
        this.loadIndex = loadIndex;
    }
    public String getLoadRange() {
        return this.loadRange;
    }
    
    public void setLoadRange(String loadRange) {
        this.loadRange = loadRange;
    }
    public Long getDLoadIndex() {
        return this.DLoadIndex;
    }
    
    public void setDLoadIndex(Long DLoadIndex) {
        this.DLoadIndex = DLoadIndex;
    }
    public String getPly() {
        return this.ply;
    }
    
    public void setPly(String ply) {
        this.ply = ply;
    }
    public Character getDd() {
        return this.dd;
    }
    
    public void setDd(Character dd) {
        this.dd = dd;
    }
    public Long getTechnologyId() {
        return this.technologyId;
    }
    
    public void setTechnologyId(Long technologyId) {
        this.technologyId = technologyId;
    }




}


