package com.bfrc.pojo.tire.jda2;
// Generated Mar 19, 2011 1:31:34 PM by Hibernate Tools 3.2.1.GA



/**
 * Display generated by hbm2java
 */
public class Display  implements java.io.Serializable {


     private long id;
     private String value;
     private long brandId;
     private long warrantyId;
     private long tiregroupId;
     private long categoryId;
     private long segmentId;
     private long classId;
     private String description;
     private String generateCatalogPage;

    public Display() {
    }

	
    public Display(long id, String value, long brandId, long warrantyId, long tiregroupId, long categoryId, long segmentId, long classId) {
        this.id = id;
        this.value = value;
        this.brandId = brandId;
        this.warrantyId = warrantyId;
        this.tiregroupId = tiregroupId;
        this.categoryId = categoryId;
        this.segmentId = segmentId;
        this.classId = classId;
    }
    public Display(long id, String value, long brandId, long warrantyId, long tiregroupId, long categoryId, long segmentId, long classId, String description, String generateCatalogPage) {
       this.id = id;
       this.value = value;
       this.brandId = brandId;
       this.warrantyId = warrantyId;
       this.tiregroupId = tiregroupId;
       this.categoryId = categoryId;
       this.segmentId = segmentId;
       this.classId = classId;
       this.description = description;
       this.generateCatalogPage = generateCatalogPage;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public long getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(long brandId) {
        this.brandId = brandId;
    }
    public long getWarrantyId() {
        return this.warrantyId;
    }
    
    public void setWarrantyId(long warrantyId) {
        this.warrantyId = warrantyId;
    }
    public long getTiregroupId() {
        return this.tiregroupId;
    }
    
    public void setTiregroupId(long tiregroupId) {
        this.tiregroupId = tiregroupId;
    }
    public long getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }
    public long getSegmentId() {
        return this.segmentId;
    }
    
    public void setSegmentId(long segmentId) {
        this.segmentId = segmentId;
    }
    public long getClassId() {
        return this.classId;
    }
    
    public void setClassId(long classId) {
        this.classId = classId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getGenerateCatalogPage() {
        return this.generateCatalogPage;
    }
    
    public void setGenerateCatalogPage(String generateCatalogPage) {
        this.generateCatalogPage = generateCatalogPage;
    }




}


