package com.bfrc.pojo.tire.jda2;
// Generated Mar 19, 2011 12:18:10 PM by Hibernate Tools 3.2.1.GA



/**
 * FactJoin generated by hbm2java
 */
public class FactJoin  implements java.io.Serializable {


     private FactJoinId id;

    public FactJoin() {
    }

    public FactJoin(FactJoinId id) {
       this.id = id;
    }
   
    public FactJoinId getId() {
        return this.id;
    }
    
    public void setId(FactJoinId id) {
        this.id = id;
    }




}


