package com.bfrc.pojo.tire.jda2;
// Generated Mar 19, 2011 12:18:10 PM by Hibernate Tools 3.2.1.GA



/**
 * Fact generated by hbm2java
 */
public class Fact  implements java.io.Serializable {


     private long id;
     private String name;
     private String description;

    public Fact() {
    }

    public Fact(long id, String name, String description) {
       this.id = id;
       this.name = name;
       this.description = description;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


