package com.bfrc.pojo.tire.jda2;
// Generated Mar 19, 2011 12:18:10 PM by Hibernate Tools 3.2.1.GA
/**
 * FactImage generated by hbm2java
 */
public class FactImage  implements java.io.Serializable {


     private long factId;
     private byte[] image;

    public FactImage() {
    }

	
    public FactImage(long factId) {
        this.factId = factId;
    }
    public FactImage(long factId, byte[] image) {
       this.factId = factId;
       this.image = image;
    }
   
    public long getFactId() {
        return this.factId;
    }
    
    public void setFactId(long factId) {
        this.factId = factId;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


