package com.bfrc.pojo.tire.jda2;
// Generated Mar 19, 2011 12:21:45 PM by Hibernate Tools 3.2.1.GA


/**
 * TechnologyImage generated by hbm2java
 */
public class TechnologyImage  implements java.io.Serializable {


     private long technologyId;
     private byte[] image;

    public TechnologyImage() {
    }

	
    public TechnologyImage(long technologyId) {
        this.technologyId = technologyId;
    }
    public TechnologyImage(long technologyId, byte[] image) {
       this.technologyId = technologyId;
       this.image = image;
    }
   
    public long getTechnologyId() {
        return this.technologyId;
    }
    
    public void setTechnologyId(long technologyId) {
        this.technologyId = technologyId;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


