package com.bfrc.pojo.tire.jda2;
// Generated Mar 19, 2011 12:23:55 PM by Hibernate Tools 3.2.1.GA



/**
 * TiregroupImageId generated by hbm2java
 */
public class TiregroupImageId  implements java.io.Serializable {


     private long tiregroupId;
     private String websource;

    public TiregroupImageId() {
    }

    public TiregroupImageId(long tiregroupId, String websource) {
       this.tiregroupId = tiregroupId;
       this.websource = websource;
    }
   
    public long getTiregroupId() {
        return this.tiregroupId;
    }
    
    public void setTiregroupId(long tiregroupId) {
        this.tiregroupId = tiregroupId;
    }
    public String getWebsource() {
        return this.websource;
    }
    
    public void setWebsource(String websource) {
        this.websource = websource;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TiregroupImageId) ) return false;
		 TiregroupImageId castOther = ( TiregroupImageId ) other; 
         
		 return (this.getTiregroupId()==castOther.getTiregroupId())
 && ( (this.getWebsource()==castOther.getWebsource()) || ( this.getWebsource()!=null && castOther.getWebsource()!=null && this.getWebsource().equals(castOther.getWebsource()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getTiregroupId();
         result = 37 * result + ( getWebsource() == null ? 0 : this.getWebsource().hashCode() );
         return result;
   }   


}


