package com.bfrc.pojo.tire.jda2;
// Generated Mar 19, 2011 12:23:55 PM by Hibernate Tools 3.2.1.GA

/**
 * TireImage generated by hbm2java
 */
public class TireImage  implements java.io.Serializable {


     private long displayId;
     private byte[] productImage;
     private byte[] productNameImage;

    public TireImage() {
    }

	
    public TireImage(long displayId) {
        this.displayId = displayId;
    }
    public TireImage(long displayId, byte[] productImage, byte[] productNameImage) {
       this.displayId = displayId;
       this.productImage = productImage;
       this.productNameImage = productNameImage;
    }
   
    public long getDisplayId() {
        return this.displayId;
    }
    
    public void setDisplayId(long displayId) {
        this.displayId = displayId;
    }
    public byte[] getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(byte[] productImage) {
        this.productImage = productImage;
    }
    public byte[] getProductNameImage() {
        return this.productNameImage;
    }
    
    public void setProductNameImage(byte[] productNameImage) {
        this.productNameImage = productNameImage;
    }




}


