package com.bfrc.pojo.tire.jda2;
// Generated Aug 21, 2011 10:08:13 AM by Hibernate Tools 3.2.1.GA



/**
 * TireGrouping generated by hbm2java
 */
public class TireGrouping  implements java.io.Serializable {


     private long groupingId;
     private Long displayId;
     private String category;
     private String segment;
     private String class_;
     private String tireVehicle;
     private String tireClass;
     private String tireType;

    public TireGrouping() {
    }

	
    public TireGrouping(long groupingId) {
        this.groupingId = groupingId;
    }
    public TireGrouping(long groupingId, Long displayId, String category, String segment, String class_, String tireVehicle, String tireClass, String tireType) {
       this.groupingId = groupingId;
       this.displayId = displayId;
       this.category = category;
       this.segment = segment;
       this.class_ = class_;
       this.tireVehicle = tireVehicle;
       this.tireClass = tireClass;
       this.tireType = tireType;
    }
   
    public long getGroupingId() {
        return this.groupingId;
    }
    
    public void setGroupingId(long groupingId) {
        this.groupingId = groupingId;
    }
    public Long getDisplayId() {
        return this.displayId;
    }
    
    public void setDisplayId(Long displayId) {
        this.displayId = displayId;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getSegment() {
        return this.segment;
    }
    
    public void setSegment(String segment) {
        this.segment = segment;
    }
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }
    public String getTireVehicle() {
        return this.tireVehicle;
    }
    
    public void setTireVehicle(String tireVehicle) {
        this.tireVehicle = tireVehicle;
    }
    public String getTireClass() {
        return this.tireClass;
    }
    
    public void setTireClass(String tireClass) {
        this.tireClass = tireClass;
    }
    public String getTireType() {
        return this.tireType;
    }
    
    public void setTireType(String tireType) {
        this.tireType = tireType;
    }




}


