package com.bfrc.pojo.tire.jda2;
// Generated Mar 19, 2011 12:23:55 PM by Hibernate Tools 3.2.1.GA



/**
 * TiregroupClass generated by hbm2java
 */
public class TiregroupClass  implements java.io.Serializable {


     private TiregroupClassId id;

    public TiregroupClass() {
    }

    public TiregroupClass(TiregroupClassId id) {
       this.id = id;
    }
   
    public TiregroupClassId getId() {
        return this.id;
    }
    
    public void setId(TiregroupClassId id) {
        this.id = id;
    }




}


