package com.bfrc.pojo.tire.jda2;
// Generated Mar 19, 2011 12:23:55 PM by Hibernate Tools 3.2.1.GA



/**
 * Tiregroup generated by hbm2java
 */
public class Tiregroup  implements java.io.Serializable {


     private long id;
     private String value;
     private String description;

    public Tiregroup() {
    }

    public Tiregroup(long id, String value, String description) {
       this.id = id;
       this.value = value;
       this.description = description;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


