package com.bfrc.pojo.tire.jda2;
// Generated Mar 19, 2011 12:23:55 PM by Hibernate Tools 3.2.1.GA



/**
 * TireWebsource generated by hbm2java
 */
public class TireWebsource  implements java.io.Serializable {


     private TireWebsourceId id;

    public TireWebsource() {
    }

    public TireWebsource(TireWebsourceId id) {
       this.id = id;
    }
   
    public TireWebsourceId getId() {
        return this.id;
    }
    
    public void setId(TireWebsourceId id) {
        this.id = id;
    }




}


