package com.bfrc.pojo.tire.jda2;
// Generated Mar 19, 2011 12:23:55 PM by Hibernate Tools 3.2.1.GA



/**
 * WarrantyImage generated by hbm2java
 */
public class WarrantyImage  implements java.io.Serializable {


     private WarrantyImageId id;

    public WarrantyImage() {
    }

    public WarrantyImage(WarrantyImageId id) {
       this.id = id;
    }
   
    public WarrantyImageId getId() {
        return this.id;
    }
    
    public void setId(WarrantyImageId id) {
        this.id = id;
    }




}


