package com.bfrc.dataaccess.model.user;

import java.util.Date;

/**
 * User generated by hbm2java
 */

public class WebSiteUser implements java.io.Serializable {

    // Fields

	public static final long COOKIE_USER_TYPE_ID =  0;
	public static final long LOGGED_IN_USER_TYPE_ID =  1;
	
     private Long webSiteUserId;
     private String firstName;
     private String lastName;
     private String address;
     private String city;
     private String state;
     private String zip;
     private String emailAddress;
     private String dayTimePhone;
     private String eveningPhone;
     private String mobilePhone;
     private String password;
     private Date createdDate;
     private Date modifiedDate;
     private Date lastLoginDate;
     private boolean passwordReset;
     private String passwordResetToken ;
     private Date passwordResetMaxDateTime;
     private boolean active;
     private long userTypeId = COOKIE_USER_TYPE_ID;
     private long webSiteId;
     private Long storeNumber;
     private Long webSiteUserVehicleId;

	public String toString() {
		StringBuffer sb = new StringBuffer("ID: " + webSiteUserId + "\nUser Type ID: " + userTypeId + "\nActive: " + active + "\n");
		if(emailAddress != null)
			sb.append("E-mail Address: " + emailAddress + "\n");
		if(firstName != null)
			sb.append("First Name: " + firstName + "\n");
		if(lastName != null)
			sb.append("Last Name: " + lastName + "\n");
		if(dayTimePhone != null)
			sb.append("Day Time Phone: " + dayTimePhone + "\n");
		if(eveningPhone != null)
			sb.append("Evening Phone: " + eveningPhone + "\n");
		if(mobilePhone != null)
			sb.append("Mobile Phone: " + mobilePhone + "\n");
		if(address != null)
			sb.append("Address: " + address + "\n");
		if(city != null)
			sb.append("City: " + city + "\n");
		if(state != null)
			sb.append("State: " + state + "\n");
		if(zip != null)
			sb.append("ZIP Code: " + zip + "\n");
	
		return sb.toString();
 	}

	public Long getWebSiteUserVehicleId() {
		return webSiteUserVehicleId;
	}


	public void setWebSiteUserVehicleId(Long webSiteUserVehicleId) {
		this.webSiteUserVehicleId = webSiteUserVehicleId;
	}

	public Long getWebSiteUserId() {
		return webSiteUserId;
	}


	public void setWebSiteUserId(Long webSiteUserId) {
		this.webSiteUserId = webSiteUserId;
	}


	public String getFirstName() {
		return firstName;
	}


	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}


	public String getLastName() {
		return lastName;
	}


	public void setLastName(String lastName) {
		this.lastName = lastName;
	}


	public String getAddress() {
		return address;
	}


	public void setAddress(String address) {
		this.address = address;
	}


	public String getCity() {
		return city;
	}


	public void setCity(String city) {
		this.city = city;
	}


	public String getState() {
		return state;
	}


	public void setState(String state) {
		this.state = state;
	}


	public String getZip() {
		return zip;
	}


	public void setZip(String zip) {
		this.zip = zip;
	}


	public String getEmailAddress() {
		return emailAddress;
	}


	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}


	public String getDayTimePhone() {
		return dayTimePhone;
	}


	public void setDayTimePhone(String dayTimePhone) {
		this.dayTimePhone = dayTimePhone;
	}


	public String getEveningPhone() {
		return eveningPhone;
	}


	public void setEveningPhone(String eveningPhone) {
		this.eveningPhone = eveningPhone;
	}


	public String getMobilePhone() {
		return mobilePhone;
	}


	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}


	public String getPassword() {
		return password;
	}


	public void setPassword(String password) {
		this.password = password;
	}


	public Date getCreatedDate() {
		return createdDate;
	}


	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}


	public Date getModifiedDate() {
		return modifiedDate;
	}


	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}


	public Date getLastLoginDate() {
		return lastLoginDate;
	}


	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}


	public boolean isPasswordReset() {
		return passwordReset;
	}


	public void setPasswordReset(boolean passwordReset) {
		this.passwordReset = passwordReset;
	}

	public boolean isActive() {
		return active;
	}


	public void setActive(boolean active) {
		this.active = active;
	}


	public long getUserTypeId() {
		return userTypeId;
	}


	public void setUserTypeId(long userTypeId) {
		this.userTypeId = userTypeId;
	}

	public Long getWebSiteId() {
		return webSiteId;
	}


	public void setWebSiteId(Long webSiteId) {
		this.webSiteId = webSiteId;
	}


	public String getPasswordResetToken() {
		return passwordResetToken;
	}


	public void setPasswordResetToken(String passwordResetToken) {
		this.passwordResetToken = passwordResetToken;
	}


	public Date getPasswordResetMaxDateTime() {
		return passwordResetMaxDateTime;
	}


	public void setPasswordResetMaxDateTime(Date passwordResetMaxDateTime) {
		this.passwordResetMaxDateTime = passwordResetMaxDateTime;
	}


	public Long getStoreNumber() {
		return storeNumber;
	}


	public void setStoreNumber(Long storeNumber) {
		this.storeNumber = storeNumber;
	}
  
}
