package com.bfrc.dataaccess.model.vehicle;

/**
 * User generated by hbm2java
 */

public class WebSiteUserSubvehicle implements java.io.Serializable {
	private Long WebSiteUserSubvehicleId;
	private WebSiteUserVehicle webSiteUserVehicle;
	private String vehicleType;
	private String vehicleObjectId;
	private Integer year;
	private String yearId;
	private String make;
	private String makeId;
	private String model;
	private String modelId;
	private String submodel;
	private String submodelId;
	private String engine;
	private String engineId;
	
	public String getMake() {
		return make;
	}
	public void setMake(String make) {
		this.make = make;
	}
	public String getMakeId() {
		return makeId;
	}
	public void setMakeId(String makeId) {
		this.makeId = makeId;
	}
	public Long getWebSiteUserSubvehicleId() {
		return WebSiteUserSubvehicleId;
	}
	public void setWebSiteUserSubvehicleId(Long webSiteUserSubvehicleId) {
		WebSiteUserSubvehicleId = webSiteUserSubvehicleId;
	}
	public WebSiteUserVehicle getWebSiteUserVehicle() {
		return webSiteUserVehicle;
	}
	public void setWebSiteUserVehicle(WebSiteUserVehicle webSiteUserVehicle) {
		this.webSiteUserVehicle = webSiteUserVehicle;
	}
	public String getVehicleType() {
		return vehicleType;
	}
	public void setVehicleType(String vehicleType) {
		this.vehicleType = vehicleType;
	}
	public String getVehicleObjectId() {
		return vehicleObjectId;
	}
	public void setVehicleObjectId(String vehicleObjectId) {
		this.vehicleObjectId = vehicleObjectId;
	}
	public Integer getYear() {
		return year;
	}
	public void setYear(Integer year) {
		this.year = year;
	}
	public String getYearId() {
		return yearId;
	}
	public void setYearId(String yearId) {
		this.yearId = yearId;
	}
	public String getModel() {
		return model;
	}
	public void setModel(String model) {
		this.model = model;
	}
	public String getModelId() {
		return modelId;
	}
	public void setModelId(String modelId) {
		this.modelId = modelId;
	}
	public String getSubmodel() {
		return submodel;
	}
	public void setSubmodel(String submodel) {
		this.submodel = submodel;
	}
	public String getSubmodelId() {
		return submodelId;
	}
	public void setSubmodelId(String submodelId) {
		this.submodelId = submodelId;
	}
	public String getEngine() {
		return engine;
	}
	public void setEngine(String engine) {
		this.engine = engine;
	}
	public String getEngineId() {
		return engineId;
	}
	public void setEngineId(String engineId) {
		this.engineId = engineId;
	}
	
	
}
