/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Oct 28 09:57:01 CDT 2005 by MyEclipse Hibernate Tool.
 */
package com.bfrc.pojo.appointment;

import java.text.*;
import java.util.*;

import com.bfrc.Bean;
import com.bfrc.framework.dao.*;
import com.bfrc.framework.util.StringUtils;

/**
 * A class that represents a row in the APPOINTMENT table. 
 * You can customize the behavior of this class by editing the class, {@link EmailSignup()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public class Appointment implements Bean
{
	private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MMMM-d h:mma");

	
	private String[] maintenanceChoices;
	
	private com.bfrc.pojo.UserVehicle vehicle;
	
	private Set services = new HashSet();
	private List choices = new ArrayList();
	
	private boolean usingClassicRules = true;
	
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long appointmentId;

    /** The value of the simple storeNumber property. */
    private java.lang.Long storeNumber;

    /** The value of the simple vehicleYear property. */
    private java.lang.Long vehicleYear;

    /** The value of the simple vehicleMake property. */
    private java.lang.String vehicleMake;

    /** The value of the simple vehicleModel property. */
    private java.lang.String vehicleModel;

    /** The value of the simple vehicleSubmodel property. */
    private java.lang.String vehicleSubmodel;

    /** The value of the simple mileage property. */
    private java.lang.Integer mileage;

    /** The value of the simple comments property. */
    private java.lang.String comments;
    
    /** The value of the simple comments property. */
    private java.lang.String customerComments;

    /** The value of the simple firstName property. */
    private java.lang.String firstName;

    /** The value of the simple lastName property. */
    private java.lang.String lastName;

    /** The value of the simple address1 property. */
    private java.lang.String address1;

    /** The value of the simple address2 property. */
    private java.lang.String address2;

    /** The value of the simple city property. */
    private java.lang.String city;

    /** The value of the simple state property. */
    private java.lang.String state;

    /** The value of the simple zip property. */
    private java.lang.String zip;

    /** The value of the simple daytimePhone property. */
    private java.lang.String daytimePhone;

    /** The value of the simple eveningPhone property. */
    private java.lang.String eveningPhone;

    /** The value of the simple cellPhone property. */
    private java.lang.String cellPhone;

    /** The value of the simple email property. */
    private java.lang.String emailAddress;

    /** The value of the simple emailSignup property. */
    private java.lang.String emailSignup;

    /** The value of the simple createdDate property. */
    private java.util.Date createdDate;

    /** The value of the simple webSite property. */
    private java.lang.String webSite;

    /** The value of the simple webSiteSource property. */
    private java.lang.String webSiteSource;
    
    /** The value of tpms flag. */
    private java.lang.String tpmsFlag;
    
    /** The value of the simple quoteId property. */
    private java.lang.Long batteryQuoteId;
    
    /** The value of the email reminder indicator property. */
    private java.lang.String emailReminder;
    
    /** The value of the phone reminder indicator property. */
    private java.lang.String phoneReminder;
    
    private Long employeeId;
    
    private Long locationId;
    
    private Long appointmentStatusId;
    
    private String appointmentStatusDesc;
    
    private String serviceIds;
    
    private String ap_serviceDescriptions;

	private Date testDate;
	
	private Integer minTimeBewteen1stAnd2ndAppointment;
	
	private Integer minTimeBewteen2ndAnd3rdAppointment;
	
	private List<Integer> daysForNoPriorToNoonAppointments;
	
	private Integer minRequiredAppointments;
	
	private Boolean checkApptTimesBeforeNoon;

	private AppointmentSchedule appointmentSchedule;
	
	public Date getTestDate() {
		return testDate;
	}

	public void setTestDate(Date testDate) {
		this.testDate = testDate;
	}

	public AppointmentSchedule getAppointmentSchedule() {
		return appointmentSchedule;
	}

	public void setAppointmentSchedule(AppointmentSchedule appointmentSchedule) {
		this.appointmentSchedule = appointmentSchedule;
	}
    /**
     * Simple constructor of AbstractEmailSignup instances.
     */
    public Appointment() {
    }

	/**
	 * @return Returns the address1.
	 */
	public java.lang.String getAddress1() {
		return StringUtils.truncate(this.address1,50);
	}
	/**
	 * @param address1 The address1 to set.
	 */
	public void setAddress1(java.lang.String address1) {
		this.address1 = address1;
	}
	/**
	 * @return Returns the address2.
	 */
	public java.lang.String getAddress2() {
		return StringUtils.truncate(this.address2,50);
	}
	/**
	 * @param address2 The address2 to set.
	 */
	public void setAddress2(java.lang.String address2) {
		this.address2 = address2;
	}
	/**
	 * @return Returns the appointmentId.
	 */
	public java.lang.Long getAppointmentId() {
		return this.appointmentId;
	}
	/**
	 * @param appointmentId The appointmentId to set.
	 */
	public void setAppointmentId(java.lang.Long appointmentId) {
		this.appointmentId = appointmentId;
	}
	/**
	 * @return Returns the cellPhone.
	 */
	public java.lang.String getCellPhone() {
		return StringUtils.truncate(this.cellPhone,25);
	}
	/**
	 * @param cellPhone The cellPhone to set.
	 */
	public void setCellPhone(java.lang.String cellPhone) {
		this.cellPhone = cellPhone;
	}
	/**
	 * @return Returns the city.
	 */
	public java.lang.String getCity() {
		return StringUtils.truncate(this.city,50);
	}
	/**
	 * @param city The city to set.
	 */
	public void setCity(java.lang.String city) {
		this.city = city;
	}
	/**
	 * @return Returns the comments.
	 */
	public java.lang.String getComments() {
		return StringUtils.truncate(this.comments,2000);
	}
	/**
	 * @param comments The comments to set.
	 */
	public void setComments(java.lang.String comments) {
		this.comments = comments;
	}
	/**
	 * @return the customerComments
	 */
	public java.lang.String getCustomerComments() {
		return StringUtils.truncate(this.customerComments,2000);
	}

	/**
	 * @param customerComments the customerComments to set
	 */
	public void setCustomerComments(java.lang.String customerComments) {
		this.customerComments = customerComments;
	}

	/**
	 * @return Returns the createdDate.
	 */
	public java.util.Date getCreatedDate() {
		return this.createdDate;
	}
	/**
	 * @param createdDate The createdDate to set.
	 */
	public void setCreatedDate(java.util.Date createdDate) {
		this.createdDate = createdDate;
	}
	/**
	 * @return Returns the daytimePhone.
	 */
	public java.lang.String getDaytimePhone() {
		return this.daytimePhone;
	}
	/**
	 * @param daytimePhone The daytimePhone to set.
	 */
	public void setDaytimePhone(java.lang.String daytimePhone) {
		this.daytimePhone = daytimePhone;
	}
	/**
	 * @return Returns the emailAddress.
	 */
	public java.lang.String getEmailAddress() {
		return StringUtils.truncate(this.emailAddress,255);
	}
	/**
	 * @param emailAddress The emailAddress to set.
	 */
	public void setEmailAddress(java.lang.String emailAddress) {
		this.emailAddress = emailAddress;
	}
	/**
	 * @return Returns the emailSignup.
	 */
	public java.lang.String getEmailSignup() {
		return this.emailSignup;
	}
	/**
	 * @param emailSignup The emailSignup to set.
	 */
	public void setEmailSignup(java.lang.String emailSignup) {
		this.emailSignup = emailSignup;
	}
	/**
	 * @return Returns the eveningPhone.
	 */
	public java.lang.String getEveningPhone() {
		return this.eveningPhone;
	}
	/**
	 * @param eveningPhone The eveningPhone to set.
	 */
	public void setEveningPhone(java.lang.String eveningPhone) {
		this.eveningPhone = eveningPhone;
	}
	/**
	 * @return Returns the firstName.
	 */
	public java.lang.String getFirstName() {
		return StringUtils.userNameFilter(this.firstName,50);
	}
	/**
	 * @param firstName The firstName to set.
	 */
	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}
	/**
	 * @return Returns the hashValue.
	 */
	public int getHashValue() {
		return this.hashValue;
	}
	/**
	 * @param hashValue The hashValue to set.
	 */
	public void setHashValue(int hashValue) {
		this.hashValue = hashValue;
	}
	/**
	 * @return Returns the lastName.
	 */
	public java.lang.String getLastName() {
		return StringUtils.userNameFilter(this.lastName,80);
	}
	/**
	 * @param lastName The lastName to set.
	 */
	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}
	/**
	 * @return Returns the mileage.
	 */
	public java.lang.Integer getMileage() {
		return this.mileage;
	}
	/**
	 * @param mileage The mileage to set.
	 */
	public void setMileage(java.lang.Integer mileage) {
		this.mileage = mileage;
	}
	/**
	 * @return Returns the state.
	 */
	public java.lang.String getState() {
		return StringUtils.truncate(this.state,2);
	}
	/**
	 * @param state The state to set.
	 */
	public void setState(java.lang.String state) {
		this.state = state;
	}
	/**
	 * @return Returns the storeNumber.
	 */
	public java.lang.Long getStoreNumber() {
		return this.storeNumber;
	}
	/**
	 * @param storeNumber The storeNumber to set.
	 */
	public void setStoreNumber(java.lang.Long storeNumber) {
		this.storeNumber = storeNumber;
	}
	/**
	 * @return Returns the vehicleMake.
	 */
	public java.lang.String getVehicleMake() {
		return StringUtils.userNameFilter(this.vehicleMake,30);
	}
	/**
	 * @param vehicleMake The vehicleMake to set.
	 */
	public void setVehicleMake(java.lang.String vehicleMake) {
		this.vehicleMake = vehicleMake;
	}
	/**
	 * @return Returns the vehicleModel.
	 */
	public java.lang.String getVehicleModel() {
		return StringUtils.userNameFilter(this.vehicleModel,40);
	}
	/**
	 * @param vehicleModel The vehicleModel to set.
	 */
	public void setVehicleModel(java.lang.String vehicleModel) {
		this.vehicleModel = vehicleModel;
	}
	/**
	 * @return Returns the vehicleSubmodel.
	 */
	public java.lang.String getVehicleSubmodel() {
		return StringUtils.userNameFilter(this.vehicleSubmodel,80);
	}
	/**
	 * @param vehicleSubmodel The vehicleSubmodel to set.
	 */
	public void setVehicleSubmodel(java.lang.String vehicleSubmodel) {
		this.vehicleSubmodel = vehicleSubmodel;
	}
	/**
	 * @return Returns the vehicleYear.
	 */
	public java.lang.Long getVehicleYear() {
		return this.vehicleYear;
	}
	/**
	 * @param vehicleYear The vehicleYear to set.
	 */
	public void setVehicleYear(java.lang.Long vehicleYear) {
		this.vehicleYear = vehicleYear;
	}
	/**
	 * @return Returns the zip.
	 */
	public java.lang.String getZip() {
		return StringUtils.truncate(this.zip,10);
	}
	/**
	 * @param zip The zip to set.
	 */
	public void setZip(java.lang.String zip) {
		this.zip = zip;
	}

	public com.bfrc.pojo.UserVehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(com.bfrc.pojo.UserVehicle vehicle) {
		this.vehicle = vehicle;
	}

	public String[] getMaintenanceChoices() {
		return this.maintenanceChoices;
	}

	public void setMaintenanceChoices(String[] maintenanceChoices) {
		this.maintenanceChoices = maintenanceChoices;
	}

	public List getChoices() {
		return this.choices;
	}

	public void setChoices(List choices) {
		this.choices = choices;
	}

	public Set getServices() {
		return this.services;
	}

	public void setServices(Set services) {
		this.services = services;
	}
	
	public java.lang.String getWebSite() {
		return webSite;
	}
	
	public void setWebSite(java.lang.String webSite) {
		this.webSite = webSite;
	}

	public java.lang.String getWebSiteSource() {
		return webSiteSource;
	}

	public void setWebSiteSource(java.lang.String webSiteSource) {
		this.webSiteSource = webSiteSource;
	}

	public java.lang.String getTpmsFlag() {
		return tpmsFlag;
	}

	public void setTpmsFlag(java.lang.String tpmsFlag) {
		this.tpmsFlag = tpmsFlag;
	}

	public java.lang.Long getBatteryQuoteId() {
		return batteryQuoteId;
	}
	
	public void setBatteryQuoteId(java.lang.Long batteryQuoteId) {
		this.batteryQuoteId = batteryQuoteId;
	}

	public java.lang.String getEmailReminder() {
		return emailReminder;
	}

	public void setEmailReminder(java.lang.String emailReminder) {
		this.emailReminder = emailReminder;
	}

	public java.lang.String getPhoneReminder() {
		return phoneReminder;
	}

	public void setPhoneReminder(java.lang.String phoneReminder) {
		this.phoneReminder = phoneReminder;
	}

	public Long getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(Long employeeId) {
		this.employeeId = employeeId;
	}

	public Long getLocationId() {
		return locationId;
	}

	public void setLocationId(Long locationId) {
		this.locationId = locationId;
	}

	public Long getAppointmentStatusId() {
		return appointmentStatusId;
	}

	public void setAppointmentStatusId(Long appointmentStatusId) {
		this.appointmentStatusId = appointmentStatusId;
	}

	public String getAppointmentStatusDesc() {
		return appointmentStatusDesc;
	}

	public void setAppointmentStatusDesc(String appointmentStatusDesc) {
		this.appointmentStatusDesc = appointmentStatusDesc;
	}

	public String getServiceIds() {
		return serviceIds;
	}

	public void setServiceIds(String serviceIds) {
		this.serviceIds = serviceIds;
	}

	public String getAp_serviceDescriptions() {
		return ap_serviceDescriptions;
	}

	public void setAp_serviceDescriptions(String ap_serviceDescriptions) {
		this.ap_serviceDescriptions = ap_serviceDescriptions;
	}

	public boolean isUsingClassicRules() {
		return usingClassicRules;
	}

	public void setUsingClassicRules(boolean usingClassicRules) {
		this.usingClassicRules = usingClassicRules;
	}

	public String toEmail(List l) { return toEmail(l, null); }
	
	public String toEmail(List l, AppointmentDAO dao) {
			String out = "";
			if(this.firstName != null)
				out += "First Name=" + this.firstName + "\n";
			if(this.lastName != null)
				out += "Last Name=" + this.lastName + "\n";
			if(this.address1 != null)
				out += "Address=" + this.address1 + "\n";
			if(this.address2 != null && !"".equals(this.address2))
				out += this.address2 + "\n";
			if(this.city != null)
				out += "City=" + this.city + "\n";
			if(this.state != null)
				out += "State=" + this.state + "\n";
			if(this.zip != null)
				out += "ZIP Code=" + this.zip + "\n";
			if(this.emailAddress != null)
				out += "E-mail=" + this.emailAddress + "\n";
			if(this.daytimePhone != null && !"".equals(this.daytimePhone))
				out += "Daytime Phone=" + this.daytimePhone + "\n";
			if(this.eveningPhone != null && !"".equals(this.eveningPhone))
				out += "Evening Phone=" + this.eveningPhone + "\n";
			if(this.cellPhone != null && !"".equals(this.cellPhone))
				out += "Cell Phone=" + this.cellPhone + "\n";
			
			if(this.vehicle != null)
				out += "Vehicle=" + this.vehicle.getYear() + " " + this.vehicle.getMake() + " " +
				this.vehicle.getModel() + " " + this.vehicle.getSubmodel() + "\n";
			if(this.mileage != null)
				out += "Mileage=" + this.mileage + "\n";
			if(this.ap_serviceDescriptions != null && this.ap_serviceDescriptions.length() > 0) {
				out += "Services=";
				String[] serDesc = ap_serviceDescriptions.split(",");
				for(int i=0;i<serDesc.length;i++) {
					if(i>0)
						out += ", ";
					String choice = serDesc[i];
					/*try {
						Integer id = Integer.valueOf(choice);
						if(dao != null)
							choice = dao.getServiceDesc(id);
					} catch(Exception ex) {}*/
					out += choice;
				}
				out += "\n";
			}
			if(this.comments != null && !"".equals(this.comments))
				out += "Comment=" + this.comments + "\n";

			if(l != null && l.size() > 0) {
				for(int i=0;i<l.size();i++) {
					AppointmentChoice c = (AppointmentChoice)l.get(i);
					out += "Choice " + (i+1) + "=" + this.sdf.format(c.getDatetime()) + "\n";
					if("drop".equals(c.getDropWaitOption()))
						out += "Leave vehicle";
					else out += "Wait for service to be complete";
					out += "\n";
				}
			}
			return out;
	}

	
	public Integer getMinTimeBewteen1stAnd2ndAppointment() {
		return minTimeBewteen1stAnd2ndAppointment;
	}

	public void setMinTimeBewteen1stAnd2ndAppointment(
			Integer minTimeBewteen1stAnd2ndAppointment) {
		this.minTimeBewteen1stAnd2ndAppointment = minTimeBewteen1stAnd2ndAppointment;
	}

	public Integer getMinTimeBewteen2ndAnd3rdAppointment() {
		return minTimeBewteen2ndAnd3rdAppointment;
	}

	public void setMinTimeBewteen2ndAnd3rdAppointment(
			Integer minTimeBewteen2ndAnd3rdAppointment) {
		this.minTimeBewteen2ndAnd3rdAppointment = minTimeBewteen2ndAnd3rdAppointment;
	}

	public Integer getMinRequiredAppointments() {
		return minRequiredAppointments;
	}

	public void setMinRequiredAppointments(Integer minRequiredAppointments) {
		this.minRequiredAppointments = minRequiredAppointments;
	}

	public Boolean getTwoAppointmentsPriorToNoonAllowed() {
		return checkApptTimesBeforeNoon;
	}

	public void setTwoAppointmentsPriorToNoonAllowed(Boolean checkApptTimesBeforeNoon) {
		this.checkApptTimesBeforeNoon = checkApptTimesBeforeNoon;
	}

	public List<Integer> getDaysForNoPriorToNoonAppointments() {
		return daysForNoPriorToNoonAppointments;
	}

	public void setDaysForNoPriorToNoonAppointments(
			List<Integer> daysForNoPriorToNoonAppointments) {
		this.daysForNoPriorToNoonAppointments = daysForNoPriorToNoonAppointments;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Appointment [maintenanceChoices="
				+ Arrays.toString(maintenanceChoices) + ", vehicle=" + vehicle
				+ ", services=" + services + ", choices=" + choices
				+ ", usingClassicRules=" + usingClassicRules + ", hashValue="
				+ hashValue + ", appointmentId=" + appointmentId
				+ ", storeNumber=" + storeNumber + ", vehicleYear="
				+ vehicleYear + ", vehicleMake=" + vehicleMake
				+ ", vehicleModel=" + vehicleModel + ", vehicleSubmodel="
				+ vehicleSubmodel + ", mileage=" + mileage + ", comments="
				+ comments + ", customerComments=" + customerComments
				+ ", firstName=" + firstName + ", lastName=" + lastName
				+ ", address1=" + address1 + ", address2=" + address2
				+ ", city=" + city + ", state=" + state + ", zip=" + zip
				+ ", daytimePhone=" + daytimePhone + ", eveningPhone="
				+ eveningPhone + ", cellPhone=" + cellPhone + ", emailAddress="
				+ emailAddress + ", emailSignup=" + emailSignup
				+ ", createdDate=" + createdDate + ", webSite=" + webSite
				+ ", webSiteSource=" + webSiteSource + ", tpmsFlag=" + tpmsFlag
				+ ", batteryQuoteId=" + batteryQuoteId + ", emailReminder="
				+ emailReminder + ", phoneReminder=" + phoneReminder
				+ ", employeeId=" + employeeId + ", locationId=" + locationId
				+ ", appointmentStatusId=" + appointmentStatusId
				+ ", appointmentStatusDesc=" + appointmentStatusDesc
				+ ", serviceIds=" + serviceIds + ", ap_serviceDescriptions="
				+ ap_serviceDescriptions + "]";
	}
	
}
