/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Oct 28 09:57:01 CDT 2005 by MyEclipse Hibernate Tool.
 */
package com.bfrc.pojo.appointment;

import java.io.Serializable;

/**
 * A class that represents a row in the APPOINTMENT_SERVICE table. 
 */
public class AppointmentService implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long appointmentServiceId;

    /** The value of the simple serviceId property. */
    private java.lang.Integer serviceId;

    /** The value of the simple serviceDesc property. */
    private java.lang.String serviceDesc;

    /** The value of the simple appointmentId property. */
    private java.lang.Long appointmentId;

    /**
     * Simple constructor of AppointmentService instances.
     */
    public AppointmentService() {
    }

	/**
	 * @return Returns the appointmentId.
	 */
	public java.lang.Long getAppointmentId() {
		return this.appointmentId;
	}
	/**
	 * @param appointmentId The appointmentId to set.
	 */
	public void setAppointmentId(java.lang.Long appointmentId) {
		this.appointmentId = appointmentId;
	}
	/**
	 * @return Returns the appointmentServiceId.
	 */
	public java.lang.Long getAppointmentServiceId() {
		return this.appointmentServiceId;
	}
	/**
	 * @param appointmentServiceId The appointmentServiceId to set.
	 */
	public void setAppointmentServiceId(java.lang.Long appointmentServiceId) {
		this.appointmentServiceId = appointmentServiceId;
	}
	/**
	 * @return Returns the hashValue.
	 */
	public int getHashValue() {
		return this.hashValue;
	}
	/**
	 * @param hashValue The hashValue to set.
	 */
	public void setHashValue(int hashValue) {
		this.hashValue = hashValue;
	}
	/**
	 * @return Returns the serviceId.
	 */
	public java.lang.Integer getServiceId() {
		return this.serviceId;
	}
	/**
	 * @param serviceId The serviceId to set.
	 */
	public void setServiceId(java.lang.Integer serviceId) {
		this.serviceId = serviceId;
	}
	/**
	 * @return Returns the serviceDesc.
	 */
	public java.lang.String getServiceDesc() {
		return this.serviceDesc;
	}
	/**
	 * @param serviceDesc The serviceDesc to set.
	 */
	public void setServiceDesc(java.lang.String serviceDesc) {
		this.serviceDesc = serviceDesc;
	}
}
