package com.bfrc.pojo.appointment;
// Generated Aug 5, 2010 10:58:25 AM by Hibernate Tools 3.2.1.GA

/**
 * AppointmentServiceDesc generated by hbm2java
 */
public class AppointmentServiceDesc  implements java.io.Serializable {


     private Integer serviceId;
     private String serviceDesc;
     private Integer serviceType;
     private Integer sortOrder;

    public AppointmentServiceDesc() {
    }

	
    public AppointmentServiceDesc(Integer serviceId) {
        this.serviceId = serviceId;
    }
    public AppointmentServiceDesc(Integer serviceId, String serviceDesc) {
       this.serviceId = serviceId;
       this.serviceDesc = serviceDesc;
    }
    public AppointmentServiceDesc(Integer serviceId, String serviceDesc, Integer serviceType, Integer sortOrder) {
        this.serviceId = serviceId;
        this.serviceDesc = serviceDesc;
        this.serviceType = serviceType;
        this.sortOrder = sortOrder;
     }

	public Integer getServiceId() {
		return serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}


	public String getServiceDesc() {
        return this.serviceDesc;
    }
    
    public void setServiceDesc(String serviceDesc) {
        this.serviceDesc = serviceDesc;
    }
    
    public Integer getServiceType() {
		return serviceType;
	}

	public void setServiceType(Integer serviceType) {
		this.serviceType = serviceType;
	}
	
	public Integer getSortOrder() {
		return sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}




}


