/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Oct 28 09:57:01 CDT 2005 by MyEclipse Hibernate Tool.
 */
package com.bfrc.pojo.appointment;

import java.io.Serializable;

/**
 * A class that represents a row in the APPOINTMENT_CHOICE table. 
 */
public class AppointmentChoice implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long appointmentChoiceId;

    /** The value of the simple choice property. */
    private java.lang.Integer choice;

    /** The value of the simple datetime property. */
    private java.util.Date datetime;

    /** The value of the simple dropWaitOption property. */
    private java.lang.String dropWaitOption;
    
    /** The value of the simple appointmentId property. */
    private java.lang.Long appointmentId;
    
    /** The value of the simple dropOffTime property. */
    private java.util.Date dropOffTime;
    
    /** The value of the simple pickUpTime property. */
    private java.util.Date pickUpTime;

    /**
     * Simple constructor of AppointmentService instances.
     */
    public AppointmentChoice() {
    }

	/**
	 * @return Returns the appointmentChoiceId.
	 */
	public java.lang.Long getAppointmentChoiceId() {
		return this.appointmentChoiceId;
	}
	/**
	 * @param appointmentChoiceId The appointmentChoiceId to set.
	 */
	public void setAppointmentChoiceId(java.lang.Long appointmentChoiceId) {
		this.appointmentChoiceId = appointmentChoiceId;
	}
	/**
	 * @return Returns the appointmentId.
	 */
	public java.lang.Long getAppointmentId() {
		return this.appointmentId;
	}
	/**
	 * @param appointmentId The appointmentId to set.
	 */
	public void setAppointmentId(java.lang.Long appointmentId) {
		this.appointmentId = appointmentId;
	}
	/**
	 * @return Returns the choice.
	 */
	public java.lang.Integer getChoice() {
		return this.choice;
	}
	/**
	 * @param choice The choice to set.
	 */
	public void setChoice(java.lang.Integer choice) {
		this.choice = choice;
	}
	/**
	 * @return Returns the datetime.
	 */
	public java.util.Date getDatetime() {
		return this.datetime;
	}
	/**
	 * @param datetime The datetime to set.
	 */
	public void setDatetime(java.util.Date datetime) {
		this.datetime = datetime;
	}
	/**
	 * @return the dropOffTime
	 */
	public java.util.Date getDropOffTime() {
		return dropOffTime;
	}

	/**
	 * @param dropOffTime the dropOffTime to set
	 */
	public void setDropOffTime(java.util.Date dropOffTime) {
		this.dropOffTime = dropOffTime;
	}

	/**
	 * @return the pickUpTime
	 */
	public java.util.Date getPickUpTime() {
		return pickUpTime;
	}

	/**
	 * @param pickUpTime the pickUpTime to set
	 */
	public void setPickUpTime(java.util.Date pickUpTime) {
		this.pickUpTime = pickUpTime;
	}

	/**
	 * @return Returns the dropWaitOption.
	 */
	public java.lang.String getDropWaitOption() {
		return this.dropWaitOption;
	}
	/**
	 * @param dropWaitOption The dropWaitOption to set.
	 */
	public void setDropWaitOption(java.lang.String dropWaitOption) {
		this.dropWaitOption = dropWaitOption;
	}
	/**
	 * @return Returns the hashValue.
	 */
	public int getHashValue() {
		return this.hashValue;
	}
	/**
	 * @param hashValue The hashValue to set.
	 */
	public void setHashValue(int hashValue) {
		this.hashValue = hashValue;
	}
}
