/**
 * 
 */
package com.bfrc.pojo.appointment;

/**
 * A class that represents a row in the APPOINTMENT_METADATA table. 
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 */
public class AppointmentMetadata {
	
    /** The value of the primary key appointmentId property. */
    private java.lang.Long appointmentId;

    /** The value of the simple locationId property. */
    private java.lang.Long locationId;
    
    /** The value of the simple employeeId property. */
    private java.lang.Long employeeId;

    /** The value of the simple servicesCSV property. */
    private java.lang.String servicesCSV;

    /** The value of the simple appointmentStatusId property. */
    private java.lang.Long appointmentStatusId;
    
    /** The value of the simple otherDetails property. */
    private java.lang.String otherDetails;
    
    /** The value of the simple createdDate property. */
    private java.util.Date createdDate;
    

	public AppointmentMetadata() {
	}
	/**
	 * @return the locationId
	 */
	public java.lang.Long getLocationId() {
		return locationId;
	}

	/**
	 * @param locationId the locationId to set
	 */
	public void setLocationId(java.lang.Long locationId) {
		this.locationId = locationId;
	}

	/**
	 * @return the employeeId
	 */
	public java.lang.Long getEmployeeId() {
		return employeeId;
	}

	/**
	 * @param employeeId the employeeId to set
	 */
	public void setEmployeeId(java.lang.Long employeeId) {
		this.employeeId = employeeId;
	}

	/**
	 * @return the servicesCSV
	 */
	public java.lang.String getServicesCSV() {
		return servicesCSV;
	}

	/**
	 * @param servicesCSV the servicesCSV to set
	 */
	public void setServicesCSV(java.lang.String servicesCSV) {
		this.servicesCSV = servicesCSV;
	}

	/**
	 * @return the appointmentId
	 */
	public java.lang.Long getAppointmentId() {
		return appointmentId;
	}

	/**
	 * @param appointmentId the appointmentId to set
	 */
	public void setAppointmentId(java.lang.Long appointmentId) {
		this.appointmentId = appointmentId;
	}

	/**
	 * @return the appointmentStatusId
	 */
	public java.lang.Long getAppointmentStatusId() {
		return appointmentStatusId;
	}

	/**
	 * @param appointmentStatusId the appointmentStatusId to set
	 */
	public void setAppointmentStatusId(java.lang.Long appointmentStatusId) {
		this.appointmentStatusId = appointmentStatusId;
	}

	/**
	 * @return the otherDetails
	 */
	public java.lang.String getOtherDetails() {
		return otherDetails;
	}
	/**
	 * @param otherDetails the otherDetails to set
	 */
	public void setOtherDetails(java.lang.String otherDetails) {
		this.otherDetails = otherDetails;
	}
	/**
	 * @return the createdDate
	 */
	public java.util.Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(java.util.Date createdDate) {
		this.createdDate = createdDate;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "AppointmentMetadata [appointmentId=" + appointmentId
				+ ", locationId=" + locationId + ", employeeId=" + employeeId
				+ ", servicesCSV=" + servicesCSV + ", appointmentStatusId="
				+ appointmentStatusId + ", otherDetails="
				+ otherDetails + ", createdDate=" + createdDate + "]";
	}
 
}
