package com.bfrc.pojo.admin;
// Generated Nov 3, 2011 9:03:49 PM by Hibernate Tools 3.2.1.GA



/**
 * AdminAppsUsers generated by hbm2java
 */
public class AdminAppsUsers  implements java.io.Serializable {


     private AdminAppsUsersId id;

    public AdminAppsUsers() {
    }

    public AdminAppsUsers(AdminAppsUsersId id) {
       this.id = id;
    }
   
    public AdminAppsUsersId getId() {
        return this.id;
    }
    
    public void setId(AdminAppsUsersId id) {
        this.id = id;
    }




}


