package com.bfrc.pojo.admin;

// Generated Jan 9, 2007 10:54:09 PM by Hibernate Tools 3.2.0.beta8

/**
 * AdminApp generated by hbm2java
 */
public class AdminApp implements java.io.Serializable {

	// Fields    

	private long applicationId;

	private String applicationName;

	private String applicationLink;

	private String webSite;

	public long getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(long applicationId) {
		this.applicationId = applicationId;
	}

	public String getLink() {
		return this.applicationLink;
	}

	public void setLink(String applicationLink) {
		this.applicationLink = applicationLink;
	}

	public String getName() {
		return this.applicationName;
	}

	public void setName(String applicationName) {
		this.applicationName = applicationName;
	}

	public String getWebSite() {
		return this.webSite;
	}

	public void setWebSite(String webSite) {
		this.webSite = webSite;
	}

}
