package com.bfrc.pojo.admin;
// Generated Feb 1, 2012 10:43:04 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AppCacheController generated by hbm2java
 */
public class AppCacheController  implements java.io.Serializable {


     private long appId;
     private String appName;
     private Long interval;
     private Date modifiedDate;

    public AppCacheController() {
    }

	
    public AppCacheController(long appId, Date modifiedDate) {
        this.appId = appId;
        this.modifiedDate = modifiedDate;
    }
    public AppCacheController(long appId, String appName, Long interval, Date modifiedDate) {
       this.appId = appId;
       this.appName = appName;
       this.interval = interval;
       this.modifiedDate = modifiedDate;
    }
   
    public long getAppId() {
        return this.appId;
    }
    
    public void setAppId(long appId) {
        this.appId = appId;
    }
    public String getAppName() {
        return this.appName;
    }
    
    public void setAppName(String appName) {
        this.appName = appName;
    }
    public Long getInterval() {
        return this.interval;
    }
    
    public void setInterval(Long interval) {
        this.interval = interval;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


