
package com.bfrc.pojo.admin;

import java.util.*;

import com.bfrc.*;

/**
 * GlobalAdmin generated by hbm2java
 */
public class GlobalAdmin implements java.io.Serializable {

	// Fields    

	private long userId;

	private String name;

	private String password;
	
	private Set adminApps = new HashSet();
	
	private String emailAddress;
	private String firstName;
    private String lastName;
    private Date createdDate;
    private Date modifiedDate;
    private String permissionLevel;
    private Boolean passwordReset;
    private boolean isSuperUser;
    private boolean isZoneManager;
    private boolean isDistrictManager;
	private String token;
    private String emailSettings;

	// Constructors

	public Set getAdminApps() {
		return this.adminApps;
	}

	public void setAdminApps(Set adminApps) {
		this.adminApps = adminApps;
	}

	public boolean isAuthorizedFor(String application, Config c) {
		if(this.adminApps == null || this.adminApps.isEmpty())
			return false;
		Iterator i = this.adminApps.iterator();
		while(i.hasNext()) {
			AdminApp app = (AdminApp)i.next();
			if(app.getName().equals(application) && app.getWebSite().equals(c.getSiteName()))
				return true;
		}
		return false;
	}
	
	/** default constructor */
	public GlobalAdmin() {
	}

	/** full constructor */
	public GlobalAdmin(long userId, String name, String password) {
		this.userId = userId;
		this.name = name;
		this.password = password;
	}

	// Property accessors
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getPermissionLevel() {
        return this.permissionLevel;
    }
    
    public void setPermissionLevel(String permissionLevel) {
        this.permissionLevel = permissionLevel;
    }
    public Boolean getPasswordReset() {
        return this.passwordReset;
    }

    public void setPasswordReset(Boolean passwordReset) {
        this.passwordReset = passwordReset;
    }
    
    public boolean getIsSuperUser() {
		return isSuperUser;
	}

	public void setSuperUser(boolean isSuperUser) {
		this.isSuperUser = isSuperUser;
	}

	public boolean getIsZoneManager() {
		return isZoneManager;
	}

	public void setIsZoneManager(boolean isZoneManager) {
		this.isZoneManager = isZoneManager;
	}

	public boolean getIsDistrictManager() {
		return isDistrictManager;
	}

	public void setIsDistrictManager(boolean isDistrictManager) {
		this.isDistrictManager = isDistrictManager;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getToken() {
		return token;
	}

	public String getEmailSettings() {
		return emailSettings;
	}

	public void setEmailSettings(String emailSettings) {
		this.emailSettings = emailSettings;
	}

	

}
