package com.bfrc.pojo.realestate;
// Generated Mar 29, 2010 11:51:08 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RealestateStoreGallery generated by hbm2java
 */
public class RealestateStoreGallery  implements java.io.Serializable {


     private Long galleryId;
     private Short galleryYear;
     private byte[] thumbImage;
     private byte[] largeImage;
     private String addressInfo;
     private String sortOrder;
     private Date createdDate;
     private Date modifiedDate;
     private String webSite;

    public RealestateStoreGallery() {
    }

	
    public RealestateStoreGallery(Long galleryId) {
        this.galleryId = galleryId;
    }
    public RealestateStoreGallery(Long galleryId, Short galleryYear, byte[] thumbImage, byte[] largeImage, String addressInfo, String sortOrder, Date createdDate, Date modifiedDate, String webSite) {
       this.galleryId = galleryId;
       this.galleryYear = galleryYear;
       this.thumbImage = thumbImage;
       this.largeImage = largeImage;
       this.addressInfo = addressInfo;
       this.sortOrder = sortOrder;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.webSite = webSite;
    }
   
    public Long getGalleryId() {
        return this.galleryId;
    }
    
    public void setGalleryId(Long galleryId) {
        this.galleryId = galleryId;
    }
    public Short getGalleryYear() {
        return this.galleryYear;
    }
    
    public void setGalleryYear(Short galleryYear) {
        this.galleryYear = galleryYear;
    }
    public byte[] getThumbImage() {
        return this.thumbImage;
    }
    
    public void setThumbImage(byte[] thumbImage) {
        this.thumbImage = thumbImage;
    }
    public byte[] getLargeImage() {
        return this.largeImage;
    }
    
    public void setLargeImage(byte[] largeImage) {
        this.largeImage = largeImage;
    }
    public String getAddressInfo() {
        return this.addressInfo;
    }
    
    public void setAddressInfo(String addressInfo) {
        this.addressInfo = addressInfo;
    }
    public String getSortOrder() {
        return this.sortOrder;
    }
    
    public void setSortOrder(String sortOrder) {
        this.sortOrder = sortOrder;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getWebSite() {
        return this.webSite;
    }
    
    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }




}


