package com.bfrc.pojo.realestate;
// Generated Mar 29, 2010 11:51:08 AM by Hibernate Tools 3.2.1.GA


import java.sql.Clob;
import java.util.Date;

/**
 * RealestateRegionContact generated by hbm2java
 */
public class RealestateRegionContact  implements java.io.Serializable {


     private String regionId;
     private String contactInfo;
     private Date createdDate;
     private Date modifiedDate;
     private String webSite;

    public RealestateRegionContact() {
    }

	
    public RealestateRegionContact(String regionId) {
        this.regionId = regionId;
    }
    public RealestateRegionContact(String regionId, String contactInfo, Date createdDate, Date modifiedDate, String webSite) {
       this.regionId = regionId;
       this.contactInfo = contactInfo;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.webSite = webSite;
    }
   
    public String getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }
    public String getContactInfo() {
        return this.contactInfo;
    }
    
    public void setContactInfo(String contactInfo) {
        this.contactInfo = contactInfo;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getWebSite() {
        return this.webSite;
    }
    
    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }




}


