package com.bfrc.pojo.realestate;
// Generated Mar 29, 2010 11:51:08 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RealestatePage generated by hbm2java
 */
public class RealestatePage  implements java.io.Serializable {


     private String pageId;
     private String content;
     private Date createdDate;
     private Date modifiedDate;
     private String webSite;

    public RealestatePage() {
    }

	
    public RealestatePage(String pageId) {
        this.pageId = pageId;
    }
    public RealestatePage(String pageId, String content, Date createdDate, Date modifiedDate, String webSite) {
       this.pageId = pageId;
       this.content = content;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.webSite = webSite;
    }
   
    public String getPageId() {
        return this.pageId;
    }
    
    public void setPageId(String pageId) {
        this.pageId = pageId;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getWebSite() {
        return this.webSite;
    }
    
    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }




}


