package com.bfrc.pojo.promotion;

// Generated Jun 14, 2007 11:50:22 AM by Hibernate Tools 3.2.0.beta8

/**
 * Promotion generated by hbm2java
 */
public class Promotion extends AbstractPromotion {

}
