package com.bfrc.pojo.promotion;

// Generated Jun 14, 2007 11:50:22 AM by Hibernate Tools 3.2.0.beta8

/**
 * Promotion generated by hbm2java
 */
public class PromotionImages extends AbstractPromotion {

	private byte[] image;
	private byte[] thumb;
	private byte[] flashIcon;

	public String toString() {
		StringBuffer sb = new StringBuffer(super.toString());
		if(image != null && image.length > 0)
			sb.append("Image present\n");
		if(thumb != null && thumb.length > 0)
			sb.append("Thumbnail present\n");
		if(flashIcon != null && flashIcon.length > 0)
			sb.append("Flash icon present\n");
		return sb.toString();
	}

	// Constructors

	/** default constructor */
	public PromotionImages() {
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public byte[] getThumb() {
		return thumb;
	}

	public void setThumb(byte[] thumb) {
		this.thumb = thumb;
	}

	public byte[] getFlashIcon() {
		return flashIcon;
	}

	public void setFlashIcon(byte[] flashIcon) {
		this.flashIcon = flashIcon;
	}
}
