package com.bfrc.pojo.alignment;
// Generated Aug 18, 2011 2:22:58 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import org.codehaus.jackson.map.annotate.JsonSerialize;
import org.codehaus.jackson.map.ser.ToStringSerializer;

/**
 * AlignmentPricing generated by hbm2java
 */
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class AlignmentPricing  implements java.io.Serializable {


     private short alignmentPricingId;
     private BigDecimal standardPricing;
     private BigDecimal lifetimePricing;
     private BigDecimal threeYearPricing;
     private long standardArticle;
     private long lifetimeArticle;
     private Long threeYearArticle;
     private String storeType;
     private String district;

    public AlignmentPricing() {
    }

	
    public AlignmentPricing(short alignmentPricingId, BigDecimal standardPricing, BigDecimal lifetimePricing, long standardArticle, long lifetimeArticle) {
        this.alignmentPricingId = alignmentPricingId;
        this.standardPricing = standardPricing;
        this.lifetimePricing = lifetimePricing;
        this.standardArticle = standardArticle;
        this.lifetimeArticle = lifetimeArticle;
    }
    public AlignmentPricing(short alignmentPricingId, BigDecimal standardPricing, BigDecimal lifetimePricing, BigDecimal threeYearPricing, long standardArticle, long lifetimeArticle, Long threeYearArticle, String storeType, String district) {
       this.alignmentPricingId = alignmentPricingId;
       this.standardPricing = standardPricing;
       this.lifetimePricing = lifetimePricing;
       this.threeYearPricing = threeYearPricing;
       this.standardArticle = standardArticle;
       this.lifetimeArticle = lifetimeArticle;
       this.threeYearArticle = threeYearArticle;
       this.storeType = storeType;
       this.district = district;
    }
   
    @JsonSerialize(include=JsonSerialize.Inclusion.NON_DEFAULT, using=ToStringSerializer.class)
    public short getAlignmentPricingId() {
        return this.alignmentPricingId;
    }
    
    public void setAlignmentPricingId(short alignmentPricingId) {
        this.alignmentPricingId = alignmentPricingId;
    }
    @JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL, using=ToStringSerializer.class)
    public BigDecimal getStandardPricing() {
        return this.standardPricing;
    }
    
    public void setStandardPricing(BigDecimal standardPricing) {
        this.standardPricing = standardPricing;
    }
    @JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL, using=ToStringSerializer.class)
    public BigDecimal getLifetimePricing() {
        return this.lifetimePricing;
    }
    
    public void setLifetimePricing(BigDecimal lifetimePricing) {
        this.lifetimePricing = lifetimePricing;
    }
    @JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL, using=ToStringSerializer.class)
    public BigDecimal getThreeYearPricing() {
        return this.threeYearPricing;
    }
    
    public void setThreeYearPricing(BigDecimal threeYearPricing) {
        this.threeYearPricing = threeYearPricing;
    }
    @JsonSerialize(include=JsonSerialize.Inclusion.NON_DEFAULT, using=ToStringSerializer.class)
    public long getStandardArticle() {
        return this.standardArticle;
    }
    
    public void setStandardArticle(long standardArticle) {
        this.standardArticle = standardArticle;
    }
    @JsonSerialize(include=JsonSerialize.Inclusion.NON_DEFAULT, using=ToStringSerializer.class)
    public long getLifetimeArticle() {
        return this.lifetimeArticle;
    }
    
    public void setLifetimeArticle(long lifetimeArticle) {
        this.lifetimeArticle = lifetimeArticle;
    }
    @JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL, using=ToStringSerializer.class)
    public Long getThreeYearArticle() {
        return this.threeYearArticle;
    }
    
    public void setThreeYearArticle(Long threeYearArticle) {
        this.threeYearArticle = threeYearArticle;
    }
    public String getStoreType() {
        return this.storeType;
    }
    
    public void setStoreType(String storeType) {
        this.storeType = storeType;
    }
	public String getDistrict() {
		return this.district;
	}
	
	public void setDistrict(String district) {
		this.district = district;
	}

}


