package com.bfrc.pojo.appointment.rules;

import java.util.Date;

// Generated Aug 2, 2012 12:55:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * AppointmentRuleSite generated by hbm2java
 */
public class AppointmentRuleSite implements java.io.Serializable {

	private AppointmentRuleSiteId id;
	private AppointmentRule appointmentRule;
	private Integer appointmentRuleValue;
	private Date updatedDate;
	private String updatedBy;

	public AppointmentRuleSite() {
	}
	
	public AppointmentRuleSite(AppointmentRuleSiteId id,
			AppointmentRule appointmentRule, Integer appointmentRuleValue,
			Date updatedDate, String updatedBy) {
		super();
		this.id = id;
		this.appointmentRule = appointmentRule;
		this.appointmentRuleValue = appointmentRuleValue;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	public AppointmentRuleSiteId getId() {
		return this.id;
	}

	public void setId(AppointmentRuleSiteId id) {
		this.id = id;
	}

	public AppointmentRule getAppointmentRule() {
		return this.appointmentRule;
	}

	public void setAppointmentRule(AppointmentRule appointmentRule) {
		this.appointmentRule = appointmentRule;
	}

	public Integer getAppointmentRuleValue() {
		return appointmentRuleValue;
	}

	public void setAppointmentRuleValue(Integer appointmentRuleValue) {
		this.appointmentRuleValue = appointmentRuleValue;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
