package com.bfrc.pojo.appointment.rules;

// Generated Aug 6, 2012 9:43:41 AM by Hibernate Tools 3.4.0.CR1

/**
 * AppointmentRuleTargetId generated by hbm2java
 */
public class AppointmentRuleTargetId implements java.io.Serializable {

	private int appointmentRuleId;
	private String target;

	public AppointmentRuleTargetId() {
	}

	public AppointmentRuleTargetId(int appointmentRuleId, String target) {
		this.appointmentRuleId = appointmentRuleId;
		this.target = target;
	}

	public int getAppointmentRuleId() {
		return this.appointmentRuleId;
	}

	public void setAppointmentRuleId(int appointmentRuleId) {
		this.appointmentRuleId = appointmentRuleId;
	}

	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AppointmentRuleTargetId))
			return false;
		AppointmentRuleTargetId castOther = (AppointmentRuleTargetId) other;

		return (this.getAppointmentRuleId() == castOther.getAppointmentRuleId())
				&& ((this.getTarget() == castOther.getTarget()) || (this
						.getTarget() != null && castOther.getTarget() != null && this
						.getTarget().equals(castOther.getTarget())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAppointmentRuleId();
		result = 37 * result
				+ (getTarget() == null ? 0 : this.getTarget().hashCode());
		return result;
	}

}
