package com.bfrc.pojo.appointment.rules;

// Generated Aug 6, 2012 9:43:41 AM by Hibernate Tools 3.4.0.CR1

/**
 * AppointmentRuleTarget generated by hbm2java
 */
public class AppointmentRuleTarget implements java.io.Serializable {

	private AppointmentRuleTargetId id;
	private AppointmentRule appointmentRule;
	private Integer appointmentRuleTargetId;

	public AppointmentRuleTarget() {
	}

	public AppointmentRuleTarget(AppointmentRuleTargetId id,
			AppointmentRule appointmentRule) {
		this.id = id;
		this.appointmentRule = appointmentRule;
	}

	public AppointmentRuleTarget(AppointmentRuleTargetId id,
			AppointmentRule appointmentRule, Integer appointmentRuleTargetId) {
		this.id = id;
		this.appointmentRule = appointmentRule;
		this.appointmentRuleTargetId = appointmentRuleTargetId;
	}

	public AppointmentRuleTargetId getId() {
		return this.id;
	}

	public void setId(AppointmentRuleTargetId id) {
		this.id = id;
	}

	public AppointmentRule getAppointmentRule() {
		return this.appointmentRule;
	}

	public void setAppointmentRule(AppointmentRule appointmentRule) {
		this.appointmentRule = appointmentRule;
	}

	public Integer getAppointmentRuleTargetId() {
		return this.appointmentRuleTargetId;
	}

	public void setAppointmentRuleTargetId(Integer appointmentRuleTargetId) {
		this.appointmentRuleTargetId = appointmentRuleTargetId;
	}

}
