package com.bfrc.pojo.appointment.rules;

// Generated Aug 6, 2012 9:43:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AppointmentRule generated by hbm2java
 */
public class AppointmentRule implements java.io.Serializable {

	private int appointmentRuleId;
	
	private String appointmentRuleName;
	private String appointmentRuleDescription;
	private Date createdDate;
	private String createdBy;
	private Date updatedDate;
	private String updatedBy;
	private Set<AppointmentRuleTarget> appointmentRuleTargets = new HashSet<AppointmentRuleTarget>(
			0);
	private Set<AppointmentRuleSite> appointmentRuleSites = new HashSet<AppointmentRuleSite>(
			0);

	public AppointmentRule() {
	}

	public AppointmentRule(int appointmentRuleId) {
		this.appointmentRuleId = appointmentRuleId;
	}

	public AppointmentRule(int appointmentRuleId,
			String appointmentRuleName,
			String appointmentRuleDescription, Date createdDate,
			String createdBy, Date updatedDate, String updatedBy,
			Set<AppointmentRuleTarget> appointmentRuleTargets,
			Set<AppointmentRuleSite> appointmentRuleSites) {
		this.appointmentRuleId = appointmentRuleId;		
		this.appointmentRuleName = appointmentRuleName;
		this.appointmentRuleDescription = appointmentRuleDescription;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.appointmentRuleTargets = appointmentRuleTargets;
		this.appointmentRuleSites = appointmentRuleSites;
	}

	public int getAppointmentRuleId() {
		return this.appointmentRuleId;
	}

	public void setAppointmentRuleId(int appointmentRuleId) {
		this.appointmentRuleId = appointmentRuleId;
	}

	public String getAppointmentRuleName() {
		return this.appointmentRuleName;
	}

	public void setAppointmentRuleName(String appointmentRuleName) {
		this.appointmentRuleName = appointmentRuleName;
	}

	public String getAppointmentRuleDescription() {
		return this.appointmentRuleDescription;
	}

	public void setAppointmentRuleDescription(String appointmentRuleDescription) {
		this.appointmentRuleDescription = appointmentRuleDescription;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set<AppointmentRuleTarget> getAppointmentRuleTargets() {
		return this.appointmentRuleTargets;
	}

	public void setAppointmentRuleTargets(
			Set<AppointmentRuleTarget> appointmentRuleTargets) {
		this.appointmentRuleTargets = appointmentRuleTargets;
	}

	public Set<AppointmentRuleSite> getAppointmentRuleSites() {
		return this.appointmentRuleSites;
	}

	public void setAppointmentRuleSites(
			Set<AppointmentRuleSite> appointmentRuleSites) {
		this.appointmentRuleSites = appointmentRuleSites;
	}

}
