package com.bfrc.dataaccess.model.oil;
// Generated Oct 11, 2012 12:44:56 PM by Hibernate Tools 3.1.0.beta4

import java.util.Calendar;


/**
 * OatsVehicleCache generated by hbm2java
 */

public class OatsVehicleCache  implements java.io.Serializable {


    // Fields    

     private String vehicleGuid;
     private String yearGuid;
     private String makeGuid;
     private String name;
     private Calendar retrievalDate;


    // Constructors

    /** default constructor */
    public OatsVehicleCache() {
    }

    
    /** full constructor */
    public OatsVehicleCache(String vehicleGuid, String yearGuid, String makeGuid, String name, Calendar retrievalDate) {
        this.vehicleGuid = vehicleGuid;
        this.yearGuid = yearGuid;
        this.makeGuid = makeGuid;
        this.name = name;
        this.retrievalDate = retrievalDate;
    }
    

   
    // Property accessors

    public String getVehicleGuid() {
        return this.vehicleGuid;
    }
    
    public void setVehicleGuid(String vehicleGuid) {
        this.vehicleGuid = vehicleGuid;
    }

    public String getYearGuid() {
        return this.yearGuid;
    }
    
    public void setYearGuid(String yearGuid) {
        this.yearGuid = yearGuid;
    }

    public String getMakeGuid() {
        return this.makeGuid;
    }
    
    public void setMakeGuid(String makeGuid) {
        this.makeGuid = makeGuid;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Calendar getRetrievalDate() {
        return this.retrievalDate;
    }
    
    public void setRetrievalDate(Calendar retrievalDate) {
        this.retrievalDate = retrievalDate;
    }

}
