package com.bfrc.dataaccess.model.oil;
// Generated Oct 11, 2012 12:44:56 PM by Hibernate Tools 3.1.0.beta4



/**
 * OatsVehicleCache generated by hbm2java
 */

public class OatsOilRecommendationId  implements java.io.Serializable {


    // Fields    

     private String vehicleGuid;
     private String oilName;


    // Constructors

    /** default constructor */
    public OatsOilRecommendationId() {
    }

    
    /** full constructor */
    public OatsOilRecommendationId(String vehicleGuid, String oilName) {
        this.vehicleGuid = vehicleGuid;
        this.oilName = oilName;
    }
    

   
    // Property accessors

    public String getVehicleGuid() {
        return this.vehicleGuid;
    }
    
    public void setVehicleGuid(String vehicleGuid) {
        this.vehicleGuid = vehicleGuid;
    }


	public String getOilName() {
		return oilName;
	}


	public void setOilName(String oilName) {
		this.oilName = oilName;
	}


}
