package com.bfrc.dataaccess.model.oil;
// Generated Oct 11, 2012 12:44:56 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.util.Calendar;


/**
 * OatsVehicleCache generated by hbm2java
 */

public class OatsOilRecommendationCache  implements java.io.Serializable {


    // Fields    

     private OatsOilRecommendationId id;
     private BigDecimal quarts;
     private Calendar retrievalDate;


    // Constructors

    /** default constructor */
    public OatsOilRecommendationCache() {
    }

    
    /** full constructor */
    public OatsOilRecommendationCache(OatsOilRecommendationId id, Calendar retrievalDate) {
        this.id = id;
        this.retrievalDate = retrievalDate;
    }
    

	public OatsOilRecommendationId getId() {
		return id;
	}


	public void setId(OatsOilRecommendationId id) {
		this.id = id;
	}

    public Calendar getRetrievalDate() {
        return this.retrievalDate;
    }
    
    public void setRetrievalDate(Calendar retrievalDate) {
        this.retrievalDate = retrievalDate;
    }


	public BigDecimal getQuarts() {
		return quarts;
	}


	public void setQuarts(BigDecimal quarts) {
		this.quarts = quarts;
	}

}
