package com.bfrc.dataaccess.model.oil;
// Generated Oct 11, 2012 12:44:56 PM by Hibernate Tools 3.1.0.beta4

import java.util.Calendar;


/**
 * OatsVehicleYearToMake generated by hbm2java
 */

public class OatsVehicleYearToMake  implements java.io.Serializable {

    // Fields    

     private OatsVehicleYearToMakeId id;
     private Calendar retrievalDate;


    // Constructors

    /** default constructor */
    public OatsVehicleYearToMake() {
    }

    
    /** full constructor */
    public OatsVehicleYearToMake(OatsVehicleYearToMakeId id, Calendar retrievalDate) {
        this.id = id;
        this.retrievalDate = retrievalDate;
    }

   
    // Property accessors

    public OatsVehicleYearToMakeId getId() {
        return this.id;
    }
    
    public void setId(OatsVehicleYearToMakeId id) {
        this.id = id;
    }

    public Calendar getRetrievalDate() {
        return this.retrievalDate;
    }
    
    public void setRetrievalDate(Calendar retrievalDate) {
        this.retrievalDate = retrievalDate;
    }
}
