package com.bfrc.dataaccess.model.oil;
// Generated Oct 11, 2012 12:44:56 PM by Hibernate Tools 3.1.0.beta4



/**
 * OatsVehicleYearToMakeId generated by hbm2java
 */

public class OatsVehicleYearToMakeId  implements java.io.Serializable {


    // Fields    

     private String yearGuid;
     private String makeGuid;


    // Constructors

    /** default constructor */
    public OatsVehicleYearToMakeId() {
    }

    
    /** full constructor */
    public OatsVehicleYearToMakeId(String yearGuid, String makeGuid) {
        this.yearGuid = yearGuid;
        this.makeGuid = makeGuid;
    }
    

   
    // Property accessors

    public String getYearGuid() {
        return this.yearGuid;
    }
    
    public void setYearGuid(String yearGuid) {
        this.yearGuid = yearGuid;
    }

    public String getMakeGuid() {
        return this.makeGuid;
    }
    
    public void setMakeGuid(String makeGuid) {
        this.makeGuid = makeGuid;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OatsVehicleYearToMakeId) ) return false;
		 OatsVehicleYearToMakeId castOther = ( OatsVehicleYearToMakeId ) other; 
         
		 return ( (this.getYearGuid()==castOther.getYearGuid()) || ( this.getYearGuid()!=null && castOther.getYearGuid()!=null && this.getYearGuid().equals(castOther.getYearGuid()) ) )
 && ( (this.getMakeGuid()==castOther.getMakeGuid()) || ( this.getMakeGuid()!=null && castOther.getMakeGuid()!=null && this.getMakeGuid().equals(castOther.getMakeGuid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getYearGuid() == null ? 0 : this.getYearGuid().hashCode() );
         result = 37 * result + ( getMakeGuid() == null ? 0 : this.getMakeGuid().hashCode() );
         return result;
   }   





}
