package com.bfrc.dataaccess.model.oil;
// Generated Aug 30, 2012 3:49:10 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;


/**
 * Oil generated by hbm2java
 */

public class Oil  implements java.io.Serializable {
	private static final long serialVersionUID = 5687870305212993107L;

	private long articleNumber;
     private Long oilTypeId;
     private String articleName;
     private String description;
     private Boolean isDiesel;
     private String viscosity;
     private BigDecimal maximumQuarts;
     private Boolean quartsAreConsideredAdditional;
     private Set oilOatsMappings = new HashSet(0);
     private Set oilStorePrices = new HashSet(0);


    // Constructors

    /** default constructor */
    public Oil() {
    }

	/** minimal constructor */
    public Oil(long articleNumber, Long oilTypeId, String articleName, String description, Boolean isDiesel, String viscosity, BigDecimal quantity, Boolean quartsAreConsideredAdditional) {
        this.articleNumber = articleNumber;
        this.oilTypeId = oilTypeId;
        this.articleName = articleName;
        this.description = description;
        this.isDiesel = isDiesel;
        this.viscosity = viscosity;
        this.maximumQuarts = quantity;
        this.quartsAreConsideredAdditional = quartsAreConsideredAdditional;
    }
    
    /** full constructor */
    public Oil(long articleNumber, Long oilTypeId, String articleName, String description, Boolean isDiesel, String viscosity, BigDecimal quantity, Boolean quartsAreConsideredAdditional, Set oilOatsMappings, Set oilStorePrices) {
        this.articleNumber = articleNumber;
        this.oilTypeId = oilTypeId;
        this.articleName = articleName;
        this.description = description;
        this.isDiesel = isDiesel;
        this.viscosity = viscosity;
        this.maximumQuarts = quantity;
        this.quartsAreConsideredAdditional = quartsAreConsideredAdditional;
        this.oilOatsMappings = oilOatsMappings;
        this.oilStorePrices = oilStorePrices;
    }
    

   
    // Property accessors

    public long getArticleNumber() {
        return this.articleNumber;
    }
    
    public void setArticleNumber(long articleNumber) {
        this.articleNumber = articleNumber;
    }

    public Long getOilTypeId() {
        return this.oilTypeId;
    }
    
    public void setOilTypeId(Long oilTypeId) {
        this.oilTypeId = oilTypeId;
    }

    public String getArticleName() {
        return this.articleName;
    }
    
    public void setArticleName(String articleName) {
        this.articleName = articleName;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getViscosity() {
        return this.viscosity;
    }
    
    public void setViscosity(String viscosity) {
        this.viscosity = viscosity;
    }


    public Set getOilOatsMappings() {
        return this.oilOatsMappings;
    }
    
    public void setOilOatsMappings(Set oilOatsMappings) {
        this.oilOatsMappings = oilOatsMappings;
    }

    public Set getOilStorePrices() {
        return this.oilStorePrices;
    }
    
    public void setOilStorePrices(Set oilStorePrices) {
        this.oilStorePrices = oilStorePrices;
    }

	public Boolean getIsDiesel() {
		return isDiesel;
	}

	public void setIsDiesel(Boolean isDiesel) {
		this.isDiesel = isDiesel;
	}

	public BigDecimal getMaximumQuarts() {
		return maximumQuarts;
	}

	public void setMaximumQuarts(BigDecimal maximumQuarts) {
		this.maximumQuarts = maximumQuarts;
	}

	public Boolean getQuartsAreConsideredAdditional() {
		return quartsAreConsideredAdditional;
	}

	public void setQuartsAreConsideredAdditional(Boolean quartsAreConsideredAdditional) {
		this.quartsAreConsideredAdditional = quartsAreConsideredAdditional;
	}
}
