package com.bfrc.dataaccess.model.oil;
// Generated Aug 30, 2012 3:49:10 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;


/**
 * OilChangeStorePrice generated by hbm2java
 */

public class OilChangeStorePrice  implements java.io.Serializable {
	private static final long serialVersionUID = 800951853814385420L;
	
	private OilChangeStorePriceId id;
     private BigDecimal price;


    // Constructors

    /** default constructor */
    public OilChangeStorePrice() {
    }

    
    /** full constructor */
    public OilChangeStorePrice(OilChangeStorePriceId id, BigDecimal price) {
        this.id = id;
        this.price = price;
    }
    

   
    // Property accessors

    public OilChangeStorePriceId getId() {
        return this.id;
    }
    
    public void setId(OilChangeStorePriceId id) {
        this.id = id;
    }

    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
   








}
