package com.bfrc.dataaccess.model.oil;
// Generated Aug 30, 2012 3:49:10 PM by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * OilChange generated by hbm2java
 */

public class OilChange  implements java.io.Serializable {
	private static final long serialVersionUID = -5865771284073820727L;
	
	private long articleNumber;
     private Long oilTypeId;
     private String articleName;
     private String description;
     private Set oilChangeStorePrices = new HashSet(0);


    // Constructors

    /** default constructor */
    public OilChange() {
    }

	/** minimal constructor */
    public OilChange(long articleNumber, Long oilTypeId, String articleName, String description) {
        this.articleNumber = articleNumber;
        this.oilTypeId = oilTypeId;
        this.articleName = articleName;
        this.description = description;
    }
    
    /** full constructor */
    public OilChange(long articleNumber, Long oilTypeId, String articleName, String description, Set oilChangeStorePrices) {
        this.articleNumber = articleNumber;
        this.oilTypeId = oilTypeId;
        this.articleName = articleName;
        this.description = description;
        this.oilChangeStorePrices = oilChangeStorePrices;
    }
    

   
    // Property accessors

    public long getArticleNumber() {
        return this.articleNumber;
    }
    
    public void setArticleNumber(long articleNumber) {
        this.articleNumber = articleNumber;
    }

    public Long getOilTypeId() {
        return this.oilTypeId;
    }
    
    public void setOilTypeId(Long oilTypeId) {
        this.oilTypeId = oilTypeId;
    }

    public String getArticleName() {
        return this.articleName;
    }
    
    public void setArticleName(String articleName) {
        this.articleName = articleName;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getOilChangeStorePrices() {
        return this.oilChangeStorePrices;
    }
    
    public void setOilChangeStorePrices(Set oilChangeStorePrices) {
        this.oilChangeStorePrices = oilChangeStorePrices;
    }
   








}
