package com.bfrc.dataaccess.model.oil;
// Generated Aug 30, 2012 5:10:55 PM by Hibernate Tools 3.1.0.beta4



/**
 * OilFilter generated by hbm2java
 */

public class OilFilter  implements java.io.Serializable {
	private static final long serialVersionUID = -7989159555901104725L;
	
	private Long oilFilterId;
     private String description;
    // Constructors

    /** default constructor */
    public OilFilter() {
    }

    
    /** full constructor */
    public OilFilter(Long oilFilterId, String description) {
        this.oilFilterId = oilFilterId;
        this.description = description;
    }
    
    // Property accessors
	public Long getOilFilterId() {
		return oilFilterId;
	}

	public void setOilFilterId(Long oilFilterId) {
		this.oilFilterId = oilFilterId;
	}

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
}
