package com.bfrc.dataaccess.model.oil;
// Generated Aug 30, 2012 5:10:55 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;


/**
 * OilFilterPrice generated by hbm2java
 */

public class OilFilterPrice  implements java.io.Serializable {
	private static final long serialVersionUID = 13101706347127370L;
	
	private Long oilFilterId;
     private BigDecimal price;


    // Constructors

    /** default constructor */
    public OilFilterPrice() {
    }
    
    /** full constructor */
    public OilFilterPrice(Long oilFilterId, BigDecimal price) {
        this.oilFilterId = oilFilterId;
        this.price = price;
    }
   
    // Property accessors

    public long getOilFilterId() {
        return this.oilFilterId;
    }
    
    public void setOilFilterId(Long oilFilterId) {
        this.oilFilterId = oilFilterId;
    }

    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
   








}
