package com.bfrc.dataaccess.model.oil;
// Generated Aug 30, 2012 3:49:10 PM by Hibernate Tools 3.1.0.beta4



/**
 * OilOatsMappingId generated by hbm2java
 */

public class OilOatsMappingId  implements java.io.Serializable {


    // Fields    

     private long oilArticleNumber;
     private String oatsName;


    // Constructors

    /** default constructor */
    public OilOatsMappingId() {
    }

    
    /** full constructor */
    public OilOatsMappingId(long oilArticleNumber, String oatsName) {
        this.oilArticleNumber = oilArticleNumber;
        this.oatsName = oatsName;
    }
    

   
    // Property accessors

    public long getOilArticleNumber() {
        return this.oilArticleNumber;
    }
    
    public void setOilArticleNumber(long oilArticleNumber) {
        this.oilArticleNumber = oilArticleNumber;
    }

    public String getOatsName() {
        return this.oatsName;
    }
    
    public void setOatsName(String oatsName) {
        this.oatsName = oatsName;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OilOatsMappingId) ) return false;
		 OilOatsMappingId castOther = ( OilOatsMappingId ) other; 
         
		 return (this.getOilArticleNumber()==castOther.getOilArticleNumber())
 && ( (this.getOatsName()==castOther.getOatsName()) || ( this.getOatsName()!=null && castOther.getOatsName()!=null && this.getOatsName().equals(castOther.getOatsName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getOilArticleNumber();
         result = 37 * result + ( getOatsName() == null ? 0 : this.getOatsName().hashCode() );
         return result;
   }   





}
