package com.bfrc.dataaccess.model.oil;
// Generated Aug 30, 2012 3:49:10 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;


/**
 * OilStorePrice generated by hbm2java
 */

public class OilStorePrice  implements java.io.Serializable {
	private static final long serialVersionUID = -5641676512076809139L;
	
	private OilStorePriceId id;
     private BigDecimal price;


    // Constructors

    /** default constructor */
    public OilStorePrice() {
    }

    
    /** full constructor */
    public OilStorePrice(OilStorePriceId id, BigDecimal price) {
        this.id = id;
        this.price = price;
    }
    

   
    // Property accessors

    public OilStorePriceId getId() {
        return this.id;
    }
    
    public void setId(OilStorePriceId id) {
        this.id = id;
    }

    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

}
