package com.bfrc.pojo.store;



/**
 * StoreHour generated by hbm2java
 */

public class StoreHolidayHourId  implements java.io.Serializable {

    // Fields    
     private Long holidayId;
     private Long storeNumber;
     
	public Long getStoreNumber() {
		return storeNumber;
	}

	public void setStoreNumber(Long storeNumber) {
		this.storeNumber = storeNumber;
	}

	public Long getHolidayId() {
		return holidayId;
	}

	public void setHolidayId(Long holidayId) {
		this.holidayId = holidayId;
	}

}