package com.bfrc.pojo.store;

import java.math.BigDecimal;
import java.util.List;
import java.util.Set;

import org.apache.commons.lang.StringUtils;

/**
 * Store generated by hbm2java
 */

public class Store implements java.io.Serializable {

	// Fields    

	private String storeHour;
	
	private Set hours = null;
	
	//cxs
	private List taxRates = null;
	
//	cxs
	private List taxStatus = null;
	
	private com.bfrc.pojo.geo.HrDistricts district = null;

	private Long storeNumber;

	private String districtId;

	private String address;

	private String city;

	private String state;

	private String zip;

	private String phone;
	
	private String trackingPhone;

	private String managerName;

	private String managerEmailAddress;

	private String storeType;

	private BigDecimal activeFlag;

	private String geoMatch;

	private Float latitude;

	private Float longitude;

	private String postalStatusCode;

	private String storeName;

	private BigDecimal onlineAppointmentActiveFlag;

	private BigDecimal tirePricingActiveFlag;

	private String fax;

	private String bannerSetting;
	private StoreBanner storeBanner;
	
	
	private Boolean fivestarActiveFlag;
    private String websiteName;
    
    private boolean isMilitaryStore = false;
    private List<String> holidayHourMessages;
    private String reasonDesc;
    
    private String currentPromotionTitle;

	// Constructors

	/** default constructor */
	public Store() {
	}

	/** constructor with id */
	public Store(Long storeNumber) {
		this.storeNumber = storeNumber;
	}
	
	public Store(Store s) {
		this.storeHour = s.getStoreHour();
		this.hours = s.getHours();
		this.district = s.getDistrict();
		this.storeNumber = s.getStoreNumber();
		this.districtId = s.getDistrictId();
		this.address = s.getAddress();
		this.city = s.getCity();
		this.state = s.getState();
		this.zip = s.getZip();
		this.managerName = s.getManagerName();
		this.managerEmailAddress = s.getManagerEmailAddress();
		this.storeType = s.getStoreType();
		this.activeFlag = s.getActiveFlag();
		this.geoMatch = s.getGeoMatch();
		this.latitude = s.getLatitude();
		this.longitude = s.getLongitude();
		this.postalStatusCode = s.getPostalStatusCode();
		this.storeName = s.getStoreName();
		this.onlineAppointmentActiveFlag = s.getOnlineAppointmentActiveFlag();
		this.tirePricingActiveFlag = s.getTirePricingActiveFlag();
		this.fax = s.getFax();
		//for correct copy
		this.phone = s.phone;
		this.trackingPhone = s.trackingPhone;
	}

	// Property accessors

	public Long getStoreNumber() {
		return this.storeNumber;
	}

	public long getNumber() {
		return this.storeNumber;
	}

	public void setStoreNumber(Long storeNumber) {
		this.storeNumber = storeNumber;
	}

	public void setNumber(long storeNumber) {
		setStoreNumber(new Long(storeNumber));
	}

	public String getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(String districtId) {
		this.districtId = districtId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getPhone() {
		if(this.trackingPhone == null 
				|| this.trackingPhone.length() == 0 
				|| this.trackingPhone.equals("")){
			return this.phone;
		}else{
			return this.trackingPhone;
		}
	}
	
	public String getFormattedPhone() {
		String formatted = this.getPhone();
		formatted = StringUtils.replace(formatted, "(", "");
		formatted = StringUtils.replace(formatted, ")", "-");
		formatted = formatted.replaceAll("\\s", "");
		
		return formatted;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getManagerName() {
		return this.managerName;
	}

	public void setManagerName(String managerName) {
		this.managerName = managerName;
	}

	public String getManagerEmailAddress() {
		return this.managerEmailAddress;
	}

	public String getManagerEmail() {
		return getManagerEmailAddress();
	}

	public void setManagerEmailAddress(String managerEmailAddress) {
		this.managerEmailAddress = managerEmailAddress;
	}

	public void setManagerEmail(String managerEmailAddress) {
		setManagerEmailAddress(managerEmailAddress);
	}

	public String getStoreType() {
		return this.storeType;
	}

	public String getType() {
		return getStoreType();
	}

	public void setStoreType(String storeType) {
		this.storeType = storeType;
	}

	public void setType(String storeType) {
		setStoreType(storeType);
	}

	public BigDecimal getActiveFlag() {
		return this.activeFlag;
	}

	public int getActive() {
		return getActiveFlag().intValue();
	}

	public void setActiveFlag(BigDecimal activeFlag) {
		this.activeFlag = activeFlag;
	}

	public void setActive(int active) {
		setActiveFlag(new BigDecimal(active));
	}

	public String getGeoMatch() {
		return this.geoMatch;
	}

	public void setGeoMatch(String geoMatch) {
		this.geoMatch = geoMatch;
	}

	public String getPostalStatusCode() {
		return this.postalStatusCode;
	}

	public void setPostalStatusCode(String postalStatusCode) {
		this.postalStatusCode = postalStatusCode;
	}

	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	public BigDecimal getOnlineAppointmentActiveFlag() {
		return this.onlineAppointmentActiveFlag;
	}

	public void setOnlineAppointmentActiveFlag(
			BigDecimal onlineAppointmentActiveFlag) {
		this.onlineAppointmentActiveFlag = onlineAppointmentActiveFlag;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	public Float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	public com.bfrc.pojo.geo.HrDistricts getDistrict() {
		return this.district;
	}

	public void setDistrict(com.bfrc.pojo.geo.HrDistricts district) {
		this.district = district;
	}
	
	public Set getHours() {
		return this.hours;
	}
	
	public void setHours(Set hours) {
		this.hours = hours;
	}

	public String getStoreHour() {
		return this.storeHour;
	}

	public void setStoreHour(String storeHour) {
		this.storeHour = storeHour;
	}

	public BigDecimal getTirePricingActiveFlag() {
		return this.tirePricingActiveFlag;
	}

	public void setTirePricingActiveFlag(BigDecimal tirePricingActiveFlag) {
		this.tirePricingActiveFlag = tirePricingActiveFlag;
	}
	
	public List getTaxRates() {
		return this.taxRates;
	}

	public void setTaxRates(List taxRates) {
		this.taxRates = taxRates;
	}
	
	public List getTaxStatus() {
		return this.taxStatus;
	}

	public void setTaxStatus(List taxStatus) {
		this.taxStatus = taxStatus;
	}

	public String getBannerSetting() {
		return storeBanner==null?null:storeBanner.getBannerSetting();
	}

	public void setBannerSetting(String bannerSetting) {
		this.bannerSetting = bannerSetting;
	}

	public StoreBanner getStoreBanner() {
		return storeBanner;
	}

	public void setStoreBanner(StoreBanner storeBanner) {
		this.storeBanner = storeBanner;
	}
	
	
	public Boolean getFivestarActiveFlag() {
        return this.fivestarActiveFlag;
    }
    
    public void setFivestarActiveFlag(Boolean fivestarActiveFlag) {
        this.fivestarActiveFlag = fivestarActiveFlag;
    }
    public String getWebsiteName() {
        return this.websiteName;
    }
    
    public void setWebsiteName(String websiteName) {
        this.websiteName = websiteName;
    }

	public String getTrackingPhone() {
		return trackingPhone;
	}

	public void setTrackingPhone(String trackingPhone) {
		this.trackingPhone = trackingPhone;
	}
	
	public boolean getIsMilitaryStore() {
		return isMilitaryStore;
	}

	public void setMilitaryStore(boolean isMilitaryStore) {
		this.isMilitaryStore = isMilitaryStore;
	}

	@Override
	public String toString(){
		StringBuffer sb = new StringBuffer();
		sb.append("\nStoreName: " + this.storeName);
		sb.append("\nStoreNumber: " + this.storeNumber);
		sb.append("\nAddress: " + this.address);
		sb.append("\nCity: " + this.city);
		sb.append("\nState: " + this.state);
		sb.append("\nZip: " + this.zip);
		sb.append("\nPhone: " + this.getPhone());
		sb.append("\nLatitude: " + this.latitude);
		sb.append("\nLongitude: " + this.longitude);
		sb.append("\nOnlineAppointmentActiveFlag: " + this.onlineAppointmentActiveFlag);
		sb.append("\nSite: " + this.websiteName);
		sb.append("\nStoreHour: " + this.storeHour);
		return sb.toString();
		
	}

	public List<String> getHolidayHourMessages() {
		return holidayHourMessages;
	}

	public void setHolidayHourMessages(List<String> holidayHourMessages) {
		this.holidayHourMessages = holidayHourMessages;
	}

	public String getReasonDesc() {
		return reasonDesc;
	}

	public void setReasonDesc(String reasonDesc) {
		this.reasonDesc = reasonDesc;
	}

	public String getCurrentPromotionTitle() {
		return currentPromotionTitle;
	}

	public void setCurrentPromotionTitle(String currentPromotionTitle) {
		this.currentPromotionTitle = currentPromotionTitle;
	}
	
}