package com.bfrc.pojo.store;
// Generated Mar 8, 2011 2:46:51 PM by Hibernate Tools 3.2.1.GA



/**
 * StoreMilitary generated by hbm2java
 */
public class StoreMilitary  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 3671335317411546580L;
	private long storeNumber;

    public StoreMilitary() {
    }

    public StoreMilitary(long storeNumber) {
       this.storeNumber = storeNumber;
    }
   
    public long getStoreNumber() {
        return this.storeNumber;
    }
    
    public void setStoreNumber(long storeNumber) {
        this.storeNumber = storeNumber;
    }
    public int hashCode() {
    	return 36733 + (int)storeNumber;
    }



}


