package com.bfrc.pojo.store;



/**
 * StoreHour generated by hbm2java
 */

public class StoreHour  implements java.io.Serializable {


    // Fields    

     private StoreHourId id;
     private String openTime;
     private String closeTime;
     private String timeZone;


    // Constructors

    /** default constructor */
    public StoreHour() {
    }
    
    /** constructor with id */
    public StoreHour(StoreHourId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public StoreHourId getId() {
        return this.id;
    }
    
    public void setId(StoreHourId id) {
        this.id = id;
    }

    public String getOpenTime() {
        return this.openTime;
    }
    
    public void setOpenTime(String openTime) {
        this.openTime = openTime;
    }

    public String getCloseTime() {
        return this.closeTime;
    }
    
    public void setCloseTime(String closeTime) {
        this.closeTime = closeTime;
    }

    public String getTimeZone() {
        return this.timeZone;
    }
    
    public void setTimeZone(String timeZone) {
        this.timeZone = timeZone;
    }
   
    public boolean equals(Object obj) {
    	if (!(obj instanceof StoreHour))
    		return false;
    	StoreHour other = (StoreHour) obj;
    	return this.getOpenTime().equals(other.getOpenTime())
    				&& this.getCloseTime().equals(other.getCloseTime());
    }


    public String toString(){
    	StringBuffer sb = new StringBuffer();
    	if(id != null) {sb.append(" dayOfWeek: " + id.getWeekDay());}
    	sb.append(" openTime: " + openTime);
    	sb.append(" closeTime: " + closeTime);    	
    	return sb.toString();
    }




}