package com.bfrc.pojo.partner;
// Generated Nov 27, 2006 7:58:57 AM by Hibernate Tools 3.1.0.beta4

import com.bfrc.Bean;
import java.util.Date;


/**
 * Record generated by hbm2java
 */

public class Record  implements Bean {


    // Fields    

     private long id;
     private String status;
     private String data;
     private Date createdDate;
     private Date noteDate;
     private Date contactDate;
     private String contactType;
     private String firstName;
     private String lastName;
     private String note;
     private String companyName;
     private String source;

    // Constructors

    public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	/** default constructor */
    public Record() {
    }

	/** minimal constructor */
    public Record(long id, String status, String data, Date createdDate, String firstName, String lastName) {
        this.id = id;
        this.status = status;
        this.data = data;
        this.createdDate = createdDate;
        this.firstName = firstName;
        this.lastName = lastName;
    }
    
    /** full constructor */
    public Record(long id, String status, String data, Date createdDate, String firstName, String lastName, String source) {
        this.id = id;
        this.status = status;
        this.data = data;
        this.createdDate = createdDate;
        this.firstName = firstName;
        this.lastName = lastName;
        this.source = source;
    }
    

   
    // Property accessors

    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

	public String getHTMLData() {
		if(this.data == null)
			return null;
		String filteredData = com.bfrc.security.Encode.html(this.data);
		return filteredData.replaceAll("\n", "<br />");
	}

	public Date getContactDate() {
		return this.contactDate;
	}

	public void setContactDate(Date contactDate) {
		this.contactDate = contactDate;
	}

	public String getContactType() {
		return this.contactType;
	}

	public void setContactType(String contactType) {
		this.contactType = contactType;
	}

	public Date getNoteDate() {
		return this.noteDate;
	}

	public void setNoteDate(Date noteDate) {
		this.noteDate = noteDate;
	}








}
