package com.bfrc.dataaccess.model.store;

import java.io.Serializable;
import org.codehaus.jackson.map.annotate.JsonSerialize;
import org.codehaus.jackson.annotate.JsonUnwrapped;

/**
 * StoreHour generated by hbm2java
 */

@JsonSerialize(include = JsonSerialize.Inclusion.NON_DEFAULT)
public class StoreHolidayHour  implements java.io.Serializable {

    // Fields    

	@JsonUnwrapped
     private StoreHolidayHourId storeHolidayHourId;
     private String openTime;
     private String closeTime;
     
	public String getOpenTime() {
		return openTime;
	}

	public void setOpenTime(String openTime) {
		this.openTime = openTime;
	}

	public String getCloseTime() {
		return closeTime;
	}

	public void setCloseTime(String closeTime) {
		this.closeTime = closeTime;
	}

	public StoreHolidayHourId getStoreHolidayHourId() {
		return storeHolidayHourId;
	}

	public void setStoreHolidayHourId(StoreHolidayHourId storeHolidayHourId) {
		this.storeHolidayHourId = storeHolidayHourId;
	}

}