package com.bfrc.dataaccess.model.store;

import java.io.Serializable;
import org.codehaus.jackson.map.annotate.JsonSerialize;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.map.ser.ToStringSerializer;
import org.codehaus.jackson.annotate.JsonUnwrapped;

/**
 * StoreHoliday generated by hbm2java
 */

@JsonSerialize(include = JsonSerialize.Inclusion.NON_DEFAULT)
public class StoreHoliday  implements java.io.Serializable {


    // Fields    

	 @JsonUnwrapped
     private StoreHolidayId id;

     private Long holidayId;

	private String description;
	
	private String status;
    // Constructors

	/** default constructor */
    
	@JsonIgnore
    public String getStatus() {
		return status;
	}
	
	@JsonIgnore
	public void setStatus(String status) {
		this.status = status;
	}
	
	public StoreHoliday() {
    }
	/** constructor with id */
    public StoreHoliday(StoreHolidayId id) {
        this.id = id;
    }
    
    // Property accessors

    public StoreHolidayId getId() {
        return this.id;
    }
    
    public void setId(StoreHolidayId id) {
        this.id = id;
    }
   
    @JsonSerialize(using=ToStringSerializer.class)
    public Long getHolidayId() {
		return holidayId;
	}

	public void setHolidayId(Long holidayId) {
		this.holidayId = holidayId;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}