package com.bfrc.pojo.geodata;
// Generated Apr 25, 2010 2:24:44 PM by Hibernate Tools 3.2.1.GA



/**
 * BsroCityStateGeoDataId generated by hbm2java
 */
public class BsroCityStateGeoDataId  implements java.io.Serializable {


     private String city;
     private String state;

    public BsroCityStateGeoDataId() {
    }

    public BsroCityStateGeoDataId(String city, String state) {
    	if(city != null)
    		city = city.trim().toUpperCase();
       this.city = city;
       if(state != null)
   		state = state.trim().toUpperCase();
       this.state = state;
    }
   
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
    	if(city != null)
    		city = city.trim().toUpperCase();
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
    	if(state != null)
    		state = state.trim().toUpperCase();
        this.state = state;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BsroCityStateGeoDataId) ) return false;
		 BsroCityStateGeoDataId castOther = ( BsroCityStateGeoDataId ) other; 
         
		 return ( (this.getCity()==castOther.getCity()) || ( this.getCity()!=null && castOther.getCity()!=null && this.getCity().equals(castOther.getCity()) ) )
 && ( (this.getState()==castOther.getState()) || ( this.getState()!=null && castOther.getState()!=null && this.getState().equals(castOther.getState()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCity() == null ? 0 : this.getCity().hashCode() );
         result = 37 * result + ( getState() == null ? 0 : this.getState().hashCode() );
         return result;
   }   


}


