package com.bfrc.pojo.geodata;
// Generated Apr 25, 2010 2:24:44 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * BsroZipGeoData generated by hbm2java
 */
public class BsroZipGeoData  implements java.io.Serializable {


     private String zip;
     private Float latitude;
     private Float longitude;
     private Date checkDate;
     private String source;

    public BsroZipGeoData() {
    }

	
    public BsroZipGeoData(String zip) {
        this.zip = zip;
    }
    public BsroZipGeoData(String zip, Float latitude, Float longitude, Date checkDate) {
       this.zip = zip;
       this.latitude = latitude;
       this.longitude = longitude;
       this.checkDate = checkDate;
    }
   
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public Float getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }
    public Float getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }
    public Date getCheckDate() {
        return this.checkDate;
    }
    
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
}