package com.bfrc.pojo.geodata;
// Generated Apr 25, 2010 2:24:44 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * BsroCityStateGeoData generated by hbm2java
 */
public class BsroCityStateGeoData  implements java.io.Serializable {


     private BsroCityStateGeoDataId id;
     private Float latitude;
     private Float longitude;
     private Date checkDate;

    public BsroCityStateGeoData() {
    }

	
    public BsroCityStateGeoData(BsroCityStateGeoDataId id) {
        this.id = id;
    }
    public BsroCityStateGeoData(BsroCityStateGeoDataId id, Float latitude, Float longitude, Date checkDate) {
       this.id = id;
       this.latitude = latitude;
       this.longitude = longitude;
       this.checkDate = checkDate;
    }
   
    public BsroCityStateGeoDataId getId() {
        return this.id;
    }
    
    public void setId(BsroCityStateGeoDataId id) {
        this.id = id;
    }
    public Float getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }
    public Float getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }
    public Date getCheckDate() {
        return this.checkDate;
    }
    
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }




}


