package com.bfrc.pojo.geodata;
// Generated Apr 25, 2010 2:24:44 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * BsroStateGeoData generated by hbm2java
 */
public class BsroStateGeoData  implements java.io.Serializable {


     private String state;
     private Float latitude;
     private Float longitude;
     private Date checkDate;

    public BsroStateGeoData() {
    }

	
    public BsroStateGeoData(String state) {
        this.state = state;
    }
    public BsroStateGeoData(String state, Float latitude, Float longitude, Date checkDate) {
       this.state = state;
       this.latitude = latitude;
       this.longitude = longitude;
       this.checkDate = checkDate;
    }
   
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
    	if(state != null)
    		state = state.trim().toUpperCase();
        this.state = state;
    }
    public Float getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }
    public Float getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }
    public Date getCheckDate() {
        return this.checkDate;
    }
    
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }




}


