package com.bfrc.pojo.maintenance;

// Generated Jan 19, 2007 2:46:32 PM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Components generated by hbm2java
 */
public class Components implements java.io.Serializable {

	// Fields    

	private long componentId;

	private String component;

	private Set intervalses = new HashSet(0);

	// Constructors

	/** default constructor */
	public Components() {
	}

	/** minimal constructor */
	public Components(long componentId) {
		this.componentId = componentId;
	}

	/** full constructor */
	public Components(long componentId, String component, Set intervalses) {
		this.componentId = componentId;
		this.component = component;
		this.intervalses = intervalses;
	}

	// Property accessors
	public long getComponentId() {
		return this.componentId;
	}

	public void setComponentId(long componentId) {
		this.componentId = componentId;
	}

	public String getComponent() {
		return this.component;
	}

	public void setComponent(String component) {
		this.component = component;
	}

	public Set getIntervalses() {
		return this.intervalses;
	}

	public void setIntervalses(Set intervalses) {
		this.intervalses = intervalses;
	}

}
