package com.bfrc.pojo.maintenance;

// Generated Jan 19, 2007 2:46:32 PM by Hibernate Tools 3.2.0.beta8

/**
 * IntervalsId generated by hbm2java
 */
public class IntervalsId implements java.io.Serializable {

	// Fields    

	private long acesVehicleId;

	private String serviceType;

	private Long mileageInterval;

	private long operationTypeId;

	private long componentId;

	private String footnoteTxt;

	private Long timeInterval;

	private String timeUnits;

	// Constructors

	/** default constructor */
	public IntervalsId() {
	}

	/** minimal constructor */
	public IntervalsId(long acesVehicleId, String serviceType,
			long operationTypeId, long componentId) {
		this.acesVehicleId = acesVehicleId;
		this.serviceType = serviceType;
		this.operationTypeId = operationTypeId;
		this.componentId = componentId;
	}

	/** full constructor */
	public IntervalsId(long acesVehicleId, String serviceType,
			Long mileageInterval, long operationTypeId, long componentId,
			String footnoteTxt, Long timeInterval, String timeUnits) {
		this.acesVehicleId = acesVehicleId;
		this.serviceType = serviceType;
		this.mileageInterval = mileageInterval;
		this.operationTypeId = operationTypeId;
		this.componentId = componentId;
		this.footnoteTxt = footnoteTxt;
		this.timeInterval = timeInterval;
		this.timeUnits = timeUnits;
	}

	

	public long getAcesVehicleId() {
		return acesVehicleId;
	}

	public void setAcesVehicleId(long acesVehicleId) {
		this.acesVehicleId = acesVehicleId;
	}

	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	public Long getMileageInterval() {
		return this.mileageInterval;
	}

	public void setMileageInterval(Long mileageInterval) {
		this.mileageInterval = mileageInterval;
	}

	public long getOperationTypeId() {
		return this.operationTypeId;
	}

	public void setOperationTypeId(long operationTypeId) {
		this.operationTypeId = operationTypeId;
	}

	public long getComponentId() {
		return this.componentId;
	}

	public void setComponentId(long componentId) {
		this.componentId = componentId;
	}

	public String getFootnoteTxt() {
		return this.footnoteTxt;
	}

	public void setFootnoteTxt(String footnoteTxt) {
		this.footnoteTxt = footnoteTxt;
	}

	public Long getTimeInterval() {
		return this.timeInterval;
	}

	public void setTimeInterval(Long timeInterval) {
		this.timeInterval = timeInterval;
	}

	public String getTimeUnits() {
		return this.timeUnits;
	}

	public void setTimeUnits(String timeUnits) {
		this.timeUnits = timeUnits;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IntervalsId))
			return false;
		IntervalsId castOther = (IntervalsId) other;

		return (this.getAcesVehicleId() == castOther.getAcesVehicleId())
				&& ((this.getServiceType() == castOther.getServiceType()) || (this
						.getServiceType() != null
						&& castOther.getServiceType() != null && this
						.getServiceType().equals(castOther.getServiceType())))
				&& ((this.getMileageInterval() == castOther
						.getMileageInterval()) || (this.getMileageInterval() != null
						&& castOther.getMileageInterval() != null && this
						.getMileageInterval().equals(
								castOther.getMileageInterval())))
				&& (this.getOperationTypeId() == castOther.getOperationTypeId())
				&& (this.getComponentId() == castOther.getComponentId())
				&& ((this.getFootnoteTxt() == castOther.getFootnoteTxt()) || (this
						.getFootnoteTxt() != null
						&& castOther.getFootnoteTxt() != null && this
						.getFootnoteTxt().equals(castOther.getFootnoteTxt())))
				&& ((this.getTimeInterval() == castOther.getTimeInterval()) || (this
						.getTimeInterval() != null
						&& castOther.getTimeInterval() != null && this
						.getTimeInterval().equals(castOther.getTimeInterval())))
				&& ((this.getTimeUnits() == castOther.getTimeUnits()) || (this
						.getTimeUnits() != null
						&& castOther.getTimeUnits() != null && this
						.getTimeUnits().equals(castOther.getTimeUnits())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAcesVehicleId();
		result = 37
				* result
				+ (getServiceType() == null ? 0 : this.getServiceType()
						.hashCode());
		result = 37
				* result
				+ (getMileageInterval() == null ? 0 : this.getMileageInterval()
						.hashCode());
		result = 37 * result + (int) this.getOperationTypeId();
		result = 37 * result + (int) this.getComponentId();
		result = 37
				* result
				+ (getFootnoteTxt() == null ? 0 : this.getFootnoteTxt()
						.hashCode());
		result = 37
				* result
				+ (getTimeInterval() == null ? 0 : this.getTimeInterval()
						.hashCode());
		result = 37 * result
				+ (getTimeUnits() == null ? 0 : this.getTimeUnits().hashCode());
		return result;
	}

}
