package com.bfrc.pojo.maintenance;

// Generated Jan 19, 2007 2:46:32 PM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * OperationTypes generated by hbm2java
 */
public class OperationTypes implements java.io.Serializable {

	// Fields    

	private long operationTypeId;

	private String operationType;

	private Set intervalses = new HashSet(0);

	// Constructors

	/** default constructor */
	public OperationTypes() {
	}

	/** minimal constructor */
	public OperationTypes(long operationTypeId) {
		this.operationTypeId = operationTypeId;
	}

	/** full constructor */
	public OperationTypes(long operationTypeId, String operationType,
			Set intervalses) {
		this.operationTypeId = operationTypeId;
		this.operationType = operationType;
		this.intervalses = intervalses;
	}

	// Property accessors
	public long getOperationTypeId() {
		return this.operationTypeId;
	}

	public void setOperationTypeId(long operationTypeId) {
		this.operationTypeId = operationTypeId;
	}

	public String getOperationType() {
		return this.operationType;
	}

	public void setOperationType(String operationType) {
		this.operationType = operationType;
	}

	public Set getIntervalses() {
		return this.intervalses;
	}

	public void setIntervalses(Set intervalses) {
		this.intervalses = intervalses;
	}

}
