package com.bfrc.pojo;
// Generated Nov 27, 2006 7:58:56 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.List;

import com.bfrc.Bean;
import com.bfrc.framework.util.StringUtils;
import com.bfrc.pojo.appointment.*;
import com.bfrc.pojo.partner.Company;
import com.bfrc.pojo.store.*;
import com.bfrc.security.Encode;

/**
 * User generated by hbm2java
 */

public class User  implements Bean {

	public final static int DEFAULT = 1;
	public final static int PPS = 2;
	public final static int ET = 3;
	public final static int FCAC = 4;
	public final static int ETIRE = 5;
	public final static int TP = 6;
	public final static int FCFC = 7;
	public final static int HT = 8;
	public final static int WWT = 10;

    // Fields

     private long id;
     private String confirmEmailAddress;
     private String eveningPhone, cellPhone;
     private Integer otherYear;
     private String otherMake;
     private String otherModel;
     private String otherSubmodel;
     private Integer otherMileage;
     private Store store;
     private UserVehicle vehicle;
     private String firstName;
     private String lastName;
     private String emailAddress;
     private String password;
     private String confirmPassword;
     private String passwordHint;
     private Date createdDate;
     private boolean active;
     private String address;
     private String address2;
     private String city;
     private String state;
     private String zip;
     private String phone;
     private String optinCode;
     private String optinConfirm;
     private Appointment appointment;
     private Company company;
     private int userTypeId = DEFAULT;
     private Boolean optIn = new Boolean(true);
     private Boolean mailRemind = new Boolean(false);
     private Boolean emailRemind = new Boolean(false);
     private Boolean smsRemind = new Boolean(false);
     private Boolean mailOffers = new Boolean(false);
     private Boolean emailOffers = new Boolean(false);
     private Boolean smsOffers = new Boolean(false);
     private String title;
     private Boolean battery = new Boolean(false), inflation = new Boolean(false), alignment = new Boolean(false), mfgr  = new Boolean(false);
 	public String toString() {
		StringBuffer sb = new StringBuffer("ID: " + id + "\nUser Type ID: " + userTypeId + "\nActive: " + active + "\n");
		if(emailAddress != null)
			sb.append("E-mail Address: " + emailAddress + "\n");
		if(firstName != null)
			sb.append("First Name: " + firstName + "\n");
		if(lastName != null)
			sb.append("Last Name: " + lastName + "\n");
		if(phone != null)
			sb.append("Phone: " + phone + "\n");
		if(eveningPhone != null)
			sb.append("Evening Phone: " + eveningPhone + "\n");
		if(cellPhone != null)
			sb.append("Cell Phone: " + cellPhone + "\n");
		if(address != null)
			sb.append("Address: " + address + "\n");
		if(address2 != null)
			sb.append("Address 2: " + address2 + "\n");
		if(city != null)
			sb.append("City: " + city + "\n");
		if(state != null)
			sb.append("State: " + state + "\n");
		if(zip != null)
			sb.append("ZIP Code: " + zip + "\n");
		if(store != null)
			sb.append("Store Number: " + store.getStoreNumber() + "\n");
		if(appointment != null)
			sb.append("Appointment ID: " + appointment.getAppointmentId() + "\n");
		if(vehicle != null)
			sb.append("UserVehicle ID: " + vehicle.getId() + "\n");
		if(otherYear != null)
			sb.append("Other Year: " + otherYear + "\n");
		if(otherMake != null)
			sb.append("Other Make: " + otherMake + "\n");
		if(otherModel != null)
			sb.append("Other Model: " + otherModel + "\n");
		if(otherSubmodel != null)
			sb.append("Other Submodel: " + otherSubmodel + "\n");
		if(password != null)
			sb.append("Password: " + password + "\n");
		if(passwordHint != null)
			sb.append("Password Hint: " + passwordHint + "\n");
		if(company != null)
			sb.append("Company ID: " + company.getId() + "\n");
		if(optIn != null)
			sb.append("Opt In: " + optIn + "\n");
		if(mailRemind != null)
			sb.append("Mail Reminders: " + mailRemind + "\n");
		if(emailRemind != null)
			sb.append("E-mail Reminders: " + emailRemind + "\n");
		if(smsRemind != null)
			sb.append("SMS Reminders: " + smsRemind + "\n");
		if(mailOffers != null)
			sb.append("Mail Offers: " + mailOffers + "\n");
		if(emailOffers != null)
			sb.append("E-mail Offers: " + emailOffers + "\n");
		if(battery != null)
			sb.append("Battery Reminder: " + battery + "\n");
		if(inflation != null)
			sb.append("Inflation Reminder: " + inflation + "\n");
		if(alignment != null)
			sb.append("Alignment Reminder: " + alignment + "\n");
		if(mfgr != null)
			sb.append("Mfgr. Reminder: " + mfgr + "\n");
		if(title != null)
			sb.append("Title: " + title + "\n");
		if(optinCode != null)
			sb.append("Opt-in Code: " + optinCode);
		if(optinCode != null)
			sb.append("Opt-in Confirmation Code: " + optinConfirm);
		return sb.toString();
 	}

    // Constructors

    public Boolean getBattery() {
		return battery;
	}

	public void setBattery(Boolean battery) {
		this.battery = battery;
	}

	public Boolean getInflation() {
		return inflation;
	}

	public void setInflation(Boolean inflation) {
		this.inflation = inflation;
	}

	public Boolean getAlignment() {
		return alignment;
	}

	public void setAlignment(Boolean alignment) {
		this.alignment = alignment;
	}

	public Boolean getMfgr() {
		return mfgr;
	}

	public void setMfgr(Boolean mfgr) {
		this.mfgr = mfgr;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getUserTypeId() {
		return this.userTypeId;
	}

	public void setUserTypeId(int userTypeId) {
		this.userTypeId = userTypeId;
	}

	/** default constructor */
    public User() {
    }

	/** minimal constructor */
    public User(long id, String firstName, String lastName, String emailAddress, String password, String passwordHint, Date createdDate, boolean active, String address, String city, String state, String zip, String phone) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.emailAddress = emailAddress;
        this.password = password;
        this.passwordHint = passwordHint;
        this.createdDate = createdDate;
        this.active = active;
        this.address = address;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.phone = phone;
    }

    /** full constructor */
    public User(long id, String firstName, String lastName, String emailAddress, String password, String passwordHint, Date createdDate, boolean active, String address, String address2, String city, String state, String zip, String phone, Company company) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.emailAddress = emailAddress;
        this.password = password;
        this.passwordHint = passwordHint;
        this.createdDate = createdDate;
        this.active = active;
        this.address = address;
        this.address2 = address2;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.phone = phone;
        this.company = company;
    }



    // Property accessors

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getFirstName() {
        return StringUtils.userNameFilter(this.firstName,50);
    }

    public void setFirstName(String firstName) {
        this.firstName = Encode.encodeForJavaScript(firstName);
    }

    public String getLastName() {
        return StringUtils.userNameFilter(this.lastName,80);
    }

    public void setLastName(String lastName) {
        this.lastName = Encode.encodeForJavaScript(lastName);
    }

    public String getEmailAddress() {
        return this.emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = Encode.encodeForJavaScript(emailAddress);
    }

    public String getPassword() {
        return StringUtils.userNameFilter(this.password,20);
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPasswordHint() {
    	return StringUtils.truncate(this.passwordHint,20);
    }

    public void setPasswordHint(String passwordHint) {
        this.passwordHint = passwordHint;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public String getAddress() {
        return StringUtils.truncate(this.address,50);
    }

    public void setAddress(String address) {
        this.address = Encode.encodeForJavaScript(address);
    }

    public String getAddress2() {
        return StringUtils.truncate(this.address2,50);
    }

    public void setAddress2(String address2) {
        this.address2 = Encode.encodeForJavaScript(address2);
    }

    public String getCity() {
        return StringUtils.truncate(this.city,50);
    }

    public void setCity(String city) {
        this.city = Encode.encodeForJavaScript(city);
    }

    public String getState() {
        return StringUtils.truncate(this.state,2);
    }

    public void setState(String state) {
        this.state = Encode.encodeForJavaScript(state);
    }

    public String getZip() {
        return StringUtils.truncate(this.zip,10);
    }

    public void setZip(String zip) {
        this.zip = Encode.encodeForJavaScript(zip);
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

	public String getConfirmPassword() {
		return this.confirmPassword;
	}

	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}

	public Boolean getOptIn() {
		return this.optIn;
	}

	public void setOptIn(Boolean optIn) {
		this.optIn = optIn;
	}

	public UserVehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(UserVehicle vehicle) {
		this.vehicle = vehicle;
	}

	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public Appointment getAppointment() {
		return this.appointment;
	}

	public void setAppointment(Appointment appointment) {
		this.appointment = appointment;
	}

	public String getOtherMake() {
		return this.otherMake;
	}

	public void setOtherMake(String otherMake) {
		this.otherMake = otherMake;
	}

	public String getOtherModel() {
		return this.otherModel;
	}

	public void setOtherModel(String otherModel) {
		this.otherModel = otherModel;
	}

	public Integer getOtherYear() {
		return this.otherYear;
	}

	public void setOtherYear(Integer otherYear) {
		this.otherYear = otherYear;
	}

	public String getOtherSubmodel() {
		return this.otherSubmodel;
	}

	public void setOtherSubmodel(String otherSubmodel) {
		this.otherSubmodel = otherSubmodel;
	}

	public Integer getOtherMileage() {
		return this.otherMileage;
	}

	public void setOtherMileage(Integer otherMileage) {
		this.otherMileage = otherMileage;
	}

	public String getConfirmEmailAddress() {
		return confirmEmailAddress;
	}

	public void setConfirmEmailAddress(String confirmEmailAddress) {
		this.confirmEmailAddress = confirmEmailAddress;
	}

	public String getEveningPhone() {
		return eveningPhone;
	}

	public void setEveningPhone(String eveningPhone) {
		this.eveningPhone = eveningPhone;
	}

	public String getCellPhone() {
		return cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	public Boolean getMailRemind() {
		return mailRemind;
	}

	public void setMailRemind(Boolean mailRemind) {
		this.mailRemind = mailRemind;
	}

	public Boolean getEmailRemind() {
		return emailRemind;
	}

	public void setEmailRemind(Boolean emailRemind) {
		this.emailRemind = emailRemind;
	}

	public Boolean getSmsRemind() {
		return smsRemind;
	}

	public void setSmsRemind(Boolean smsRemind) {
		this.smsRemind = smsRemind;
	}

	public Boolean getMailOffers() {
		return mailOffers;
	}

	public void setMailOffers(Boolean mailOffers) {
		this.mailOffers = mailOffers;
	}

	public Boolean getEmailOffers() {
		return emailOffers;
	}

	public void setEmailOffers(Boolean emailOffers) {
		this.emailOffers = emailOffers;
	}

	public Boolean getSmsOffers() {
		return smsOffers;
	}

	public void setSmsOffers(Boolean smsOffers) {
		this.smsOffers = smsOffers;
	}

	public void setOptinCode(String optinCode) {
		this.optinCode = optinCode;
	}

	public String getOptinCode() {
		return optinCode;
	}

	public void setOptinConfirm(String optinConfirm) {
		this.optinConfirm = optinConfirm;
	}

	public String getOptinConfirm() {
		return optinConfirm;
	}

    //--- new for myFirestone ---//
	private  List vehicles;
	public List getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(List vehicles) {
		this.vehicles = vehicles;
	}
}
