package com.bsro.databean.tireselector;


import java.util.List;
import java.util.Map;

import com.bfrc.Bean;
import com.bfrc.pojo.tire.*;
import com.bfrc.pojo.tire.jda.Display;
import com.bsro.databean.BaseDataBean;

/**
 * User generated by hbm2java
 */

public class CatalogGetQuoteDataBean extends  BaseDataBean {
    
	/**
	 * 
	 */
	private static final long serialVersionUID = -3089097397612994153L;
	List articlesInCatalog;
	public List getArticlesInCatalog(){
		return this.articlesInCatalog;
	}
	public void setArticlesInCatalog(List articlesInCatalog){
		this.articlesInCatalog = articlesInCatalog;
	}
	
	List articlesInCatalogRear;
	public List getArticlesInCatalogRear(){
		return this.articlesInCatalogRear;
	}
	public void setArticlesInCatalogRear(List articlesInCatalogRear){
		this.articlesInCatalogRear = articlesInCatalogRear;
	}
	
	String messageCode;
	public String getMessageCode(){
		return messageCode;
	}
	public void setMessageCode(String messageCode){
		this.messageCode = messageCode;
	}
	
	Display passedTireCatalog;
	public Display getPassedTireCatalog(){
		return this.passedTireCatalog;
	}
	public void setPassedTireCatalog(Display passedTireCatalog){
		this.passedTireCatalog = passedTireCatalog;
	}
}
