package com.bsro.service.location;

import java.util.LinkedHashMap;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.bfrc.framework.dao.store.LocatorOperator;

@Service("locationService")
public class LocationServiceImpl implements LocationService {
	
	@Autowired
	private LocatorOperator locatorOperator;
	
	private static final Map<String, String> zipCodeFirstThreeDigitsToStateMap = new LinkedHashMap<String, String>();
	
	private static final String ZIP_CODE_DELIMITER = "-";
	
	private static final String UNUSED_ZIP_CODE = null;
	private static final String INTERNATIONAL_MAIL = "International Mail";

	/**
	 * Armed Forces Americas (APO/FPO)
	 */
	private static final String AA = "AA";
	
	/**
	 * Armed Forces Europe (APO/FPO)
	 */
	
	private static final String AE = "AE";
	/**
	 * Armed Forces Pacific (APO/FPO)
	 */
	private static final String AP = "AP";
	/**
	 * American Samoa
	 */
	private static final String AS = "AS";
	/**
	 * Federated States of Micronesia
	 */
	private static final String FM = "FM";
	/**
	 * Guam
	 */
	private static final String GU = "GU";
	/**
	 * Marshall Islands
	 */
	private static final String MH = "MH";
	/**
	 * Commonwealth of the Northern Mariana Islands
	 */
	private static final String MP = "MP";
	/**
	 * Puerto Rico
	 */
	private static final String PR = "PR";
	/**
	 * Palau
	 */
	private static final String PW = "PW";
	/**
	 * Virgin Islands
	 */
	private static final String VI = "VI";
	/**
	 * Hawaii or American Samoa (needs further drilldown)
	 */
	private static final String HI_or_AS = "HI_or_AS";
	/**
	 * Federated States of Micronesia or Guam or Marshall Islands or Commonwealth of the Northern Mariana Islands or Palau  (needs further drilldown)
	 */
	private static final String FM_or_GU_or_MH_or_MP_or_PW = "FM_or_GU_or_MH_or_MP_or_PW";
		
	static {
		zipCodeFirstThreeDigitsToStateMap.put("000",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("001",INTERNATIONAL_MAIL);
		zipCodeFirstThreeDigitsToStateMap.put("002",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("003",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("004",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("005",NY);
		zipCodeFirstThreeDigitsToStateMap.put("006",PR);
		zipCodeFirstThreeDigitsToStateMap.put("007",PR);
		zipCodeFirstThreeDigitsToStateMap.put("008",VI);
		zipCodeFirstThreeDigitsToStateMap.put("009",PR);
		zipCodeFirstThreeDigitsToStateMap.put("010",MA);
		zipCodeFirstThreeDigitsToStateMap.put("011",MA);
		zipCodeFirstThreeDigitsToStateMap.put("012",MA);
		zipCodeFirstThreeDigitsToStateMap.put("013",MA);
		zipCodeFirstThreeDigitsToStateMap.put("014",MA);
		zipCodeFirstThreeDigitsToStateMap.put("015",MA);
		zipCodeFirstThreeDigitsToStateMap.put("016",MA);
		zipCodeFirstThreeDigitsToStateMap.put("017",MA);
		zipCodeFirstThreeDigitsToStateMap.put("018",MA);
		zipCodeFirstThreeDigitsToStateMap.put("019",MA);
		zipCodeFirstThreeDigitsToStateMap.put("020",MA);
		zipCodeFirstThreeDigitsToStateMap.put("021",MA);
		zipCodeFirstThreeDigitsToStateMap.put("022",MA);
		zipCodeFirstThreeDigitsToStateMap.put("023",MA);
		zipCodeFirstThreeDigitsToStateMap.put("024",MA);
		zipCodeFirstThreeDigitsToStateMap.put("025",MA);
		zipCodeFirstThreeDigitsToStateMap.put("026",MA);
		zipCodeFirstThreeDigitsToStateMap.put("027",MA);
		zipCodeFirstThreeDigitsToStateMap.put("028",RI);
		zipCodeFirstThreeDigitsToStateMap.put("029",RI);
		zipCodeFirstThreeDigitsToStateMap.put("030",NH);
		zipCodeFirstThreeDigitsToStateMap.put("031",NH);
		zipCodeFirstThreeDigitsToStateMap.put("032",NH);
		zipCodeFirstThreeDigitsToStateMap.put("033",NH);
		zipCodeFirstThreeDigitsToStateMap.put("034",NH);
		zipCodeFirstThreeDigitsToStateMap.put("035",NH);
		zipCodeFirstThreeDigitsToStateMap.put("036",NH);
		zipCodeFirstThreeDigitsToStateMap.put("037",NH);
		zipCodeFirstThreeDigitsToStateMap.put("038",NH);
		zipCodeFirstThreeDigitsToStateMap.put("039",ME);
		zipCodeFirstThreeDigitsToStateMap.put("040",ME);
		zipCodeFirstThreeDigitsToStateMap.put("041",ME);
		zipCodeFirstThreeDigitsToStateMap.put("042",ME);
		zipCodeFirstThreeDigitsToStateMap.put("043",ME);
		zipCodeFirstThreeDigitsToStateMap.put("044",ME);
		zipCodeFirstThreeDigitsToStateMap.put("045",ME);
		zipCodeFirstThreeDigitsToStateMap.put("046",ME);
		zipCodeFirstThreeDigitsToStateMap.put("047",ME);
		zipCodeFirstThreeDigitsToStateMap.put("048",ME);
		zipCodeFirstThreeDigitsToStateMap.put("049",ME);
		zipCodeFirstThreeDigitsToStateMap.put("050",VT);
		zipCodeFirstThreeDigitsToStateMap.put("051",VT);
		zipCodeFirstThreeDigitsToStateMap.put("052",VT);
		zipCodeFirstThreeDigitsToStateMap.put("053",VT);
		zipCodeFirstThreeDigitsToStateMap.put("054",VT);
		zipCodeFirstThreeDigitsToStateMap.put("055",MA);
		zipCodeFirstThreeDigitsToStateMap.put("056",VT);
		zipCodeFirstThreeDigitsToStateMap.put("057",VT);
		zipCodeFirstThreeDigitsToStateMap.put("058",VT);
		zipCodeFirstThreeDigitsToStateMap.put("059",VT);
		zipCodeFirstThreeDigitsToStateMap.put("060",CT);
		zipCodeFirstThreeDigitsToStateMap.put("061",CT);
		zipCodeFirstThreeDigitsToStateMap.put("062",CT);
		zipCodeFirstThreeDigitsToStateMap.put("063",CT);
		zipCodeFirstThreeDigitsToStateMap.put("064",CT);
		zipCodeFirstThreeDigitsToStateMap.put("065",CT);
		zipCodeFirstThreeDigitsToStateMap.put("066",CT);
		zipCodeFirstThreeDigitsToStateMap.put("067",CT);
		zipCodeFirstThreeDigitsToStateMap.put("068",CT);
		zipCodeFirstThreeDigitsToStateMap.put("069",CT);
		zipCodeFirstThreeDigitsToStateMap.put("070",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("071",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("072",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("073",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("074",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("075",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("076",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("077",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("078",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("079",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("080",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("081",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("082",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("083",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("084",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("085",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("086",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("087",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("088",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("089",NJ);
		zipCodeFirstThreeDigitsToStateMap.put("090",AE);
		zipCodeFirstThreeDigitsToStateMap.put("091",AE);
		zipCodeFirstThreeDigitsToStateMap.put("092",AE);
		zipCodeFirstThreeDigitsToStateMap.put("093",AE);
		zipCodeFirstThreeDigitsToStateMap.put("094",AE);
		zipCodeFirstThreeDigitsToStateMap.put("095",AE);
		zipCodeFirstThreeDigitsToStateMap.put("096",AE);
		zipCodeFirstThreeDigitsToStateMap.put("097",AE);
		zipCodeFirstThreeDigitsToStateMap.put("098",AE);
		zipCodeFirstThreeDigitsToStateMap.put("099",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("100",NY);
		zipCodeFirstThreeDigitsToStateMap.put("101",NY);
		zipCodeFirstThreeDigitsToStateMap.put("102",NY);
		zipCodeFirstThreeDigitsToStateMap.put("103",NY);
		zipCodeFirstThreeDigitsToStateMap.put("104",NY);
		zipCodeFirstThreeDigitsToStateMap.put("105",NY);
		zipCodeFirstThreeDigitsToStateMap.put("106",NY);
		zipCodeFirstThreeDigitsToStateMap.put("107",NY);
		zipCodeFirstThreeDigitsToStateMap.put("108",NY);
		zipCodeFirstThreeDigitsToStateMap.put("109",NY);
		zipCodeFirstThreeDigitsToStateMap.put("110",NY);
		zipCodeFirstThreeDigitsToStateMap.put("111",NY);
		zipCodeFirstThreeDigitsToStateMap.put("112",NY);
		zipCodeFirstThreeDigitsToStateMap.put("113",NY);
		zipCodeFirstThreeDigitsToStateMap.put("114",NY);
		zipCodeFirstThreeDigitsToStateMap.put("115",NY);
		zipCodeFirstThreeDigitsToStateMap.put("116",NY);
		zipCodeFirstThreeDigitsToStateMap.put("117",NY);
		zipCodeFirstThreeDigitsToStateMap.put("118",NY);
		zipCodeFirstThreeDigitsToStateMap.put("119",NY);
		zipCodeFirstThreeDigitsToStateMap.put("120",NY);
		zipCodeFirstThreeDigitsToStateMap.put("121",NY);
		zipCodeFirstThreeDigitsToStateMap.put("122",NY);
		zipCodeFirstThreeDigitsToStateMap.put("123",NY);
		zipCodeFirstThreeDigitsToStateMap.put("124",NY);
		zipCodeFirstThreeDigitsToStateMap.put("125",NY);
		zipCodeFirstThreeDigitsToStateMap.put("126",NY);
		zipCodeFirstThreeDigitsToStateMap.put("127",NY);
		zipCodeFirstThreeDigitsToStateMap.put("128",NY);
		zipCodeFirstThreeDigitsToStateMap.put("129",NY);
		zipCodeFirstThreeDigitsToStateMap.put("130",NY);
		zipCodeFirstThreeDigitsToStateMap.put("131",NY);
		zipCodeFirstThreeDigitsToStateMap.put("132",NY);
		zipCodeFirstThreeDigitsToStateMap.put("133",NY);
		zipCodeFirstThreeDigitsToStateMap.put("134",NY);
		zipCodeFirstThreeDigitsToStateMap.put("135",NY);
		zipCodeFirstThreeDigitsToStateMap.put("136",NY);
		zipCodeFirstThreeDigitsToStateMap.put("137",NY);
		zipCodeFirstThreeDigitsToStateMap.put("138",NY);
		zipCodeFirstThreeDigitsToStateMap.put("139",NY);
		zipCodeFirstThreeDigitsToStateMap.put("140",NY);
		zipCodeFirstThreeDigitsToStateMap.put("141",NY);
		zipCodeFirstThreeDigitsToStateMap.put("142",NY);
		zipCodeFirstThreeDigitsToStateMap.put("143",NY);
		zipCodeFirstThreeDigitsToStateMap.put("144",NY);
		zipCodeFirstThreeDigitsToStateMap.put("145",NY);
		zipCodeFirstThreeDigitsToStateMap.put("146",NY);
		zipCodeFirstThreeDigitsToStateMap.put("147",NY);
		zipCodeFirstThreeDigitsToStateMap.put("148",NY);
		zipCodeFirstThreeDigitsToStateMap.put("149",NY);
		zipCodeFirstThreeDigitsToStateMap.put("150",PA);
		zipCodeFirstThreeDigitsToStateMap.put("151",PA);
		zipCodeFirstThreeDigitsToStateMap.put("152",PA);
		zipCodeFirstThreeDigitsToStateMap.put("153",PA);
		zipCodeFirstThreeDigitsToStateMap.put("154",PA);
		zipCodeFirstThreeDigitsToStateMap.put("155",PA);
		zipCodeFirstThreeDigitsToStateMap.put("156",PA);
		zipCodeFirstThreeDigitsToStateMap.put("157",PA);
		zipCodeFirstThreeDigitsToStateMap.put("158",PA);
		zipCodeFirstThreeDigitsToStateMap.put("159",PA);
		zipCodeFirstThreeDigitsToStateMap.put("160",PA);
		zipCodeFirstThreeDigitsToStateMap.put("161",PA);
		zipCodeFirstThreeDigitsToStateMap.put("162",PA);
		zipCodeFirstThreeDigitsToStateMap.put("163",PA);
		zipCodeFirstThreeDigitsToStateMap.put("164",PA);
		zipCodeFirstThreeDigitsToStateMap.put("165",PA);
		zipCodeFirstThreeDigitsToStateMap.put("166",PA);
		zipCodeFirstThreeDigitsToStateMap.put("167",PA);
		zipCodeFirstThreeDigitsToStateMap.put("168",PA);
		zipCodeFirstThreeDigitsToStateMap.put("169",PA);
		zipCodeFirstThreeDigitsToStateMap.put("170",PA);
		zipCodeFirstThreeDigitsToStateMap.put("171",PA);
		zipCodeFirstThreeDigitsToStateMap.put("172",PA);
		zipCodeFirstThreeDigitsToStateMap.put("173",PA);
		zipCodeFirstThreeDigitsToStateMap.put("174",PA);
		zipCodeFirstThreeDigitsToStateMap.put("175",PA);
		zipCodeFirstThreeDigitsToStateMap.put("176",PA);
		zipCodeFirstThreeDigitsToStateMap.put("177",PA);
		zipCodeFirstThreeDigitsToStateMap.put("178",PA);
		zipCodeFirstThreeDigitsToStateMap.put("179",PA);
		zipCodeFirstThreeDigitsToStateMap.put("180",PA);
		zipCodeFirstThreeDigitsToStateMap.put("181",PA);
		zipCodeFirstThreeDigitsToStateMap.put("182",PA);
		zipCodeFirstThreeDigitsToStateMap.put("183",PA);
		zipCodeFirstThreeDigitsToStateMap.put("184",PA);
		zipCodeFirstThreeDigitsToStateMap.put("185",PA);
		zipCodeFirstThreeDigitsToStateMap.put("186",PA);
		zipCodeFirstThreeDigitsToStateMap.put("187",PA);
		zipCodeFirstThreeDigitsToStateMap.put("188",PA);
		zipCodeFirstThreeDigitsToStateMap.put("189",PA);
		zipCodeFirstThreeDigitsToStateMap.put("190",PA);
		zipCodeFirstThreeDigitsToStateMap.put("191",PA);
		zipCodeFirstThreeDigitsToStateMap.put("192",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("193",PA);
		zipCodeFirstThreeDigitsToStateMap.put("194",PA);
		zipCodeFirstThreeDigitsToStateMap.put("195",PA);
		zipCodeFirstThreeDigitsToStateMap.put("196",PA);
		zipCodeFirstThreeDigitsToStateMap.put("197",DE);
		zipCodeFirstThreeDigitsToStateMap.put("198",DE);
		zipCodeFirstThreeDigitsToStateMap.put("199",DE);
		zipCodeFirstThreeDigitsToStateMap.put("200",DC);
		zipCodeFirstThreeDigitsToStateMap.put("201",VA);
		zipCodeFirstThreeDigitsToStateMap.put("202",DC);
		zipCodeFirstThreeDigitsToStateMap.put("203",DC);
		zipCodeFirstThreeDigitsToStateMap.put("204",DC);
		zipCodeFirstThreeDigitsToStateMap.put("205",DC);
		zipCodeFirstThreeDigitsToStateMap.put("206",MD);
		zipCodeFirstThreeDigitsToStateMap.put("207",MD);
		zipCodeFirstThreeDigitsToStateMap.put("208",MD);
		zipCodeFirstThreeDigitsToStateMap.put("209",MD);
		zipCodeFirstThreeDigitsToStateMap.put("210",MD);
		zipCodeFirstThreeDigitsToStateMap.put("211",MD);
		zipCodeFirstThreeDigitsToStateMap.put("212",MD);
		zipCodeFirstThreeDigitsToStateMap.put("213",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("214",MD);
		zipCodeFirstThreeDigitsToStateMap.put("215",MD);
		zipCodeFirstThreeDigitsToStateMap.put("216",MD);
		zipCodeFirstThreeDigitsToStateMap.put("217",MD);
		zipCodeFirstThreeDigitsToStateMap.put("218",MD);
		zipCodeFirstThreeDigitsToStateMap.put("219",MD);
		zipCodeFirstThreeDigitsToStateMap.put("220",VA);
		zipCodeFirstThreeDigitsToStateMap.put("221",VA);
		zipCodeFirstThreeDigitsToStateMap.put("222",VA);
		zipCodeFirstThreeDigitsToStateMap.put("223",VA);
		zipCodeFirstThreeDigitsToStateMap.put("224",VA);
		zipCodeFirstThreeDigitsToStateMap.put("225",VA);
		zipCodeFirstThreeDigitsToStateMap.put("226",VA);
		zipCodeFirstThreeDigitsToStateMap.put("227",VA);
		zipCodeFirstThreeDigitsToStateMap.put("228",VA);
		zipCodeFirstThreeDigitsToStateMap.put("229",VA);
		zipCodeFirstThreeDigitsToStateMap.put("230",VA);
		zipCodeFirstThreeDigitsToStateMap.put("231",VA);
		zipCodeFirstThreeDigitsToStateMap.put("232",VA);
		zipCodeFirstThreeDigitsToStateMap.put("233",VA);
		zipCodeFirstThreeDigitsToStateMap.put("234",VA);
		zipCodeFirstThreeDigitsToStateMap.put("235",VA);
		zipCodeFirstThreeDigitsToStateMap.put("236",VA);
		zipCodeFirstThreeDigitsToStateMap.put("237",VA);
		zipCodeFirstThreeDigitsToStateMap.put("238",VA);
		zipCodeFirstThreeDigitsToStateMap.put("239",VA);
		zipCodeFirstThreeDigitsToStateMap.put("240",VA);
		zipCodeFirstThreeDigitsToStateMap.put("241",VA);
		zipCodeFirstThreeDigitsToStateMap.put("242",VA);
		zipCodeFirstThreeDigitsToStateMap.put("243",VA);
		zipCodeFirstThreeDigitsToStateMap.put("244",VA);
		zipCodeFirstThreeDigitsToStateMap.put("245",VA);
		zipCodeFirstThreeDigitsToStateMap.put("246",VA);
		zipCodeFirstThreeDigitsToStateMap.put("247",WV);
		zipCodeFirstThreeDigitsToStateMap.put("248",WV);
		zipCodeFirstThreeDigitsToStateMap.put("249",WV);
		zipCodeFirstThreeDigitsToStateMap.put("250",WV);
		zipCodeFirstThreeDigitsToStateMap.put("251",WV);
		zipCodeFirstThreeDigitsToStateMap.put("252",WV);
		zipCodeFirstThreeDigitsToStateMap.put("253",WV);
		zipCodeFirstThreeDigitsToStateMap.put("254",WV);
		zipCodeFirstThreeDigitsToStateMap.put("255",WV);
		zipCodeFirstThreeDigitsToStateMap.put("256",WV);
		zipCodeFirstThreeDigitsToStateMap.put("257",WV);
		zipCodeFirstThreeDigitsToStateMap.put("258",WV);
		zipCodeFirstThreeDigitsToStateMap.put("259",WV);
		zipCodeFirstThreeDigitsToStateMap.put("260",WV);
		zipCodeFirstThreeDigitsToStateMap.put("261",WV);
		zipCodeFirstThreeDigitsToStateMap.put("262",WV);
		zipCodeFirstThreeDigitsToStateMap.put("263",WV);
		zipCodeFirstThreeDigitsToStateMap.put("264",WV);
		zipCodeFirstThreeDigitsToStateMap.put("265",WV);
		zipCodeFirstThreeDigitsToStateMap.put("266",WV);
		zipCodeFirstThreeDigitsToStateMap.put("267",WV);
		zipCodeFirstThreeDigitsToStateMap.put("268",WV);
		zipCodeFirstThreeDigitsToStateMap.put("269",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("270",NC);
		zipCodeFirstThreeDigitsToStateMap.put("271",NC);
		zipCodeFirstThreeDigitsToStateMap.put("272",NC);
		zipCodeFirstThreeDigitsToStateMap.put("273",NC);
		zipCodeFirstThreeDigitsToStateMap.put("274",NC);
		zipCodeFirstThreeDigitsToStateMap.put("275",NC);
		zipCodeFirstThreeDigitsToStateMap.put("276",NC);
		zipCodeFirstThreeDigitsToStateMap.put("277",NC);
		zipCodeFirstThreeDigitsToStateMap.put("278",NC);
		zipCodeFirstThreeDigitsToStateMap.put("279",NC);
		zipCodeFirstThreeDigitsToStateMap.put("280",NC);
		zipCodeFirstThreeDigitsToStateMap.put("281",NC);
		zipCodeFirstThreeDigitsToStateMap.put("282",NC);
		zipCodeFirstThreeDigitsToStateMap.put("283",NC);
		zipCodeFirstThreeDigitsToStateMap.put("284",NC);
		zipCodeFirstThreeDigitsToStateMap.put("285",NC);
		zipCodeFirstThreeDigitsToStateMap.put("286",NC);
		zipCodeFirstThreeDigitsToStateMap.put("287",NC);
		zipCodeFirstThreeDigitsToStateMap.put("288",NC);
		zipCodeFirstThreeDigitsToStateMap.put("289",NC);
		zipCodeFirstThreeDigitsToStateMap.put("290",SC);
		zipCodeFirstThreeDigitsToStateMap.put("291",SC);
		zipCodeFirstThreeDigitsToStateMap.put("292",SC);
		zipCodeFirstThreeDigitsToStateMap.put("293",SC);
		zipCodeFirstThreeDigitsToStateMap.put("294",SC);
		zipCodeFirstThreeDigitsToStateMap.put("295",SC);
		zipCodeFirstThreeDigitsToStateMap.put("296",SC);
		zipCodeFirstThreeDigitsToStateMap.put("297",SC);
		zipCodeFirstThreeDigitsToStateMap.put("298",SC);
		zipCodeFirstThreeDigitsToStateMap.put("299",SC);
		zipCodeFirstThreeDigitsToStateMap.put("300",GA);
		zipCodeFirstThreeDigitsToStateMap.put("301",GA);
		zipCodeFirstThreeDigitsToStateMap.put("302",GA);
		zipCodeFirstThreeDigitsToStateMap.put("303",GA);
		zipCodeFirstThreeDigitsToStateMap.put("304",GA);
		zipCodeFirstThreeDigitsToStateMap.put("305",GA);
		zipCodeFirstThreeDigitsToStateMap.put("306",GA);
		zipCodeFirstThreeDigitsToStateMap.put("307",GA);
		zipCodeFirstThreeDigitsToStateMap.put("308",GA);
		zipCodeFirstThreeDigitsToStateMap.put("309",GA);
		zipCodeFirstThreeDigitsToStateMap.put("310",GA);
		zipCodeFirstThreeDigitsToStateMap.put("311",GA);
		zipCodeFirstThreeDigitsToStateMap.put("312",GA);
		zipCodeFirstThreeDigitsToStateMap.put("313",GA);
		zipCodeFirstThreeDigitsToStateMap.put("314",GA);
		zipCodeFirstThreeDigitsToStateMap.put("315",GA);
		zipCodeFirstThreeDigitsToStateMap.put("316",GA);
		zipCodeFirstThreeDigitsToStateMap.put("317",GA);
		zipCodeFirstThreeDigitsToStateMap.put("318",GA);
		zipCodeFirstThreeDigitsToStateMap.put("319",GA);
		zipCodeFirstThreeDigitsToStateMap.put("320",FL);
		zipCodeFirstThreeDigitsToStateMap.put("321",FL);
		zipCodeFirstThreeDigitsToStateMap.put("322",FL);
		zipCodeFirstThreeDigitsToStateMap.put("323",FL);
		zipCodeFirstThreeDigitsToStateMap.put("324",FL);
		zipCodeFirstThreeDigitsToStateMap.put("325",FL);
		zipCodeFirstThreeDigitsToStateMap.put("326",FL);
		zipCodeFirstThreeDigitsToStateMap.put("327",FL);
		zipCodeFirstThreeDigitsToStateMap.put("328",FL);
		zipCodeFirstThreeDigitsToStateMap.put("329",FL);
		zipCodeFirstThreeDigitsToStateMap.put("330",FL);
		zipCodeFirstThreeDigitsToStateMap.put("331",FL);
		zipCodeFirstThreeDigitsToStateMap.put("332",FL);
		zipCodeFirstThreeDigitsToStateMap.put("333",FL);
		zipCodeFirstThreeDigitsToStateMap.put("334",FL);
		zipCodeFirstThreeDigitsToStateMap.put("335",FL);
		zipCodeFirstThreeDigitsToStateMap.put("336",FL);
		zipCodeFirstThreeDigitsToStateMap.put("337",FL);
		zipCodeFirstThreeDigitsToStateMap.put("338",FL);
		zipCodeFirstThreeDigitsToStateMap.put("339",FL);
		zipCodeFirstThreeDigitsToStateMap.put("340",AA);
		zipCodeFirstThreeDigitsToStateMap.put("341",FL);
		zipCodeFirstThreeDigitsToStateMap.put("342",FL);
		zipCodeFirstThreeDigitsToStateMap.put("343",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("344",FL);
		zipCodeFirstThreeDigitsToStateMap.put("345",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("346",FL);
		zipCodeFirstThreeDigitsToStateMap.put("347",FL);
		zipCodeFirstThreeDigitsToStateMap.put("348",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("349",FL);
		zipCodeFirstThreeDigitsToStateMap.put("350",AL);
		zipCodeFirstThreeDigitsToStateMap.put("351",AL);
		zipCodeFirstThreeDigitsToStateMap.put("352",AL);
		zipCodeFirstThreeDigitsToStateMap.put("353",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("354",AL);
		zipCodeFirstThreeDigitsToStateMap.put("355",AL);
		zipCodeFirstThreeDigitsToStateMap.put("356",AL);
		zipCodeFirstThreeDigitsToStateMap.put("357",AL);
		zipCodeFirstThreeDigitsToStateMap.put("358",AL);
		zipCodeFirstThreeDigitsToStateMap.put("359",AL);
		zipCodeFirstThreeDigitsToStateMap.put("360",AL);
		zipCodeFirstThreeDigitsToStateMap.put("361",AL);
		zipCodeFirstThreeDigitsToStateMap.put("362",AL);
		zipCodeFirstThreeDigitsToStateMap.put("363",AL);
		zipCodeFirstThreeDigitsToStateMap.put("364",AL);
		zipCodeFirstThreeDigitsToStateMap.put("365",AL);
		zipCodeFirstThreeDigitsToStateMap.put("366",AL);
		zipCodeFirstThreeDigitsToStateMap.put("367",AL);
		zipCodeFirstThreeDigitsToStateMap.put("368",AL);
		zipCodeFirstThreeDigitsToStateMap.put("369",AL);
		zipCodeFirstThreeDigitsToStateMap.put("370",TN);
		zipCodeFirstThreeDigitsToStateMap.put("371",TN);
		zipCodeFirstThreeDigitsToStateMap.put("372",TN);
		zipCodeFirstThreeDigitsToStateMap.put("373",TN);
		zipCodeFirstThreeDigitsToStateMap.put("374",TN);
		zipCodeFirstThreeDigitsToStateMap.put("375",TN);
		zipCodeFirstThreeDigitsToStateMap.put("376",TN);
		zipCodeFirstThreeDigitsToStateMap.put("377",TN);
		zipCodeFirstThreeDigitsToStateMap.put("378",TN);
		zipCodeFirstThreeDigitsToStateMap.put("379",TN);
		zipCodeFirstThreeDigitsToStateMap.put("380",TN);
		zipCodeFirstThreeDigitsToStateMap.put("381",TN);
		zipCodeFirstThreeDigitsToStateMap.put("382",TN);
		zipCodeFirstThreeDigitsToStateMap.put("383",TN);
		zipCodeFirstThreeDigitsToStateMap.put("384",TN);
		zipCodeFirstThreeDigitsToStateMap.put("385",TN);
		zipCodeFirstThreeDigitsToStateMap.put("386",MS);
		zipCodeFirstThreeDigitsToStateMap.put("387",MS);
		zipCodeFirstThreeDigitsToStateMap.put("388",MS);
		zipCodeFirstThreeDigitsToStateMap.put("389",MS);
		zipCodeFirstThreeDigitsToStateMap.put("390",MS);
		zipCodeFirstThreeDigitsToStateMap.put("391",MS);
		zipCodeFirstThreeDigitsToStateMap.put("392",MS);
		zipCodeFirstThreeDigitsToStateMap.put("393",MS);
		zipCodeFirstThreeDigitsToStateMap.put("394",MS);
		zipCodeFirstThreeDigitsToStateMap.put("395",MS);
		zipCodeFirstThreeDigitsToStateMap.put("396",MS);
		zipCodeFirstThreeDigitsToStateMap.put("397",MS);
		zipCodeFirstThreeDigitsToStateMap.put("398",GA);
		zipCodeFirstThreeDigitsToStateMap.put("399",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("400",KY);
		zipCodeFirstThreeDigitsToStateMap.put("401",KY);
		zipCodeFirstThreeDigitsToStateMap.put("402",KY);
		zipCodeFirstThreeDigitsToStateMap.put("403",KY);
		zipCodeFirstThreeDigitsToStateMap.put("404",KY);
		zipCodeFirstThreeDigitsToStateMap.put("405",KY);
		zipCodeFirstThreeDigitsToStateMap.put("406",KY);
		zipCodeFirstThreeDigitsToStateMap.put("407",KY);
		zipCodeFirstThreeDigitsToStateMap.put("408",KY);
		zipCodeFirstThreeDigitsToStateMap.put("409",KY);
		zipCodeFirstThreeDigitsToStateMap.put("410",KY);
		zipCodeFirstThreeDigitsToStateMap.put("411",KY);
		zipCodeFirstThreeDigitsToStateMap.put("412",KY);
		zipCodeFirstThreeDigitsToStateMap.put("413",KY);
		zipCodeFirstThreeDigitsToStateMap.put("414",KY);
		zipCodeFirstThreeDigitsToStateMap.put("415",KY);
		zipCodeFirstThreeDigitsToStateMap.put("416",KY);
		zipCodeFirstThreeDigitsToStateMap.put("417",KY);
		zipCodeFirstThreeDigitsToStateMap.put("418",KY);
		zipCodeFirstThreeDigitsToStateMap.put("419",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("420",KY);
		zipCodeFirstThreeDigitsToStateMap.put("421",KY);
		zipCodeFirstThreeDigitsToStateMap.put("422",KY);
		zipCodeFirstThreeDigitsToStateMap.put("423",KY);
		zipCodeFirstThreeDigitsToStateMap.put("424",KY);
		zipCodeFirstThreeDigitsToStateMap.put("425",KY);
		zipCodeFirstThreeDigitsToStateMap.put("426",KY);
		zipCodeFirstThreeDigitsToStateMap.put("427",KY);
		zipCodeFirstThreeDigitsToStateMap.put("428",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("429",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("430",OH);
		zipCodeFirstThreeDigitsToStateMap.put("431",OH);
		zipCodeFirstThreeDigitsToStateMap.put("432",OH);
		zipCodeFirstThreeDigitsToStateMap.put("433",OH);
		zipCodeFirstThreeDigitsToStateMap.put("434",OH);
		zipCodeFirstThreeDigitsToStateMap.put("435",OH);
		zipCodeFirstThreeDigitsToStateMap.put("436",OH);
		zipCodeFirstThreeDigitsToStateMap.put("437",OH);
		zipCodeFirstThreeDigitsToStateMap.put("438",OH);
		zipCodeFirstThreeDigitsToStateMap.put("439",OH);
		zipCodeFirstThreeDigitsToStateMap.put("440",OH);
		zipCodeFirstThreeDigitsToStateMap.put("441",OH);
		zipCodeFirstThreeDigitsToStateMap.put("442",OH);
		zipCodeFirstThreeDigitsToStateMap.put("443",OH);
		zipCodeFirstThreeDigitsToStateMap.put("444",OH);
		zipCodeFirstThreeDigitsToStateMap.put("445",OH);
		zipCodeFirstThreeDigitsToStateMap.put("446",OH);
		zipCodeFirstThreeDigitsToStateMap.put("447",OH);
		zipCodeFirstThreeDigitsToStateMap.put("448",OH);
		zipCodeFirstThreeDigitsToStateMap.put("449",OH);
		zipCodeFirstThreeDigitsToStateMap.put("450",OH);
		zipCodeFirstThreeDigitsToStateMap.put("451",OH);
		zipCodeFirstThreeDigitsToStateMap.put("452",OH);
		zipCodeFirstThreeDigitsToStateMap.put("453",OH);
		zipCodeFirstThreeDigitsToStateMap.put("454",OH);
		zipCodeFirstThreeDigitsToStateMap.put("455",OH);
		zipCodeFirstThreeDigitsToStateMap.put("456",OH);
		zipCodeFirstThreeDigitsToStateMap.put("457",OH);
		zipCodeFirstThreeDigitsToStateMap.put("458",OH);
		zipCodeFirstThreeDigitsToStateMap.put("459",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("460",IN);
		zipCodeFirstThreeDigitsToStateMap.put("461",IN);
		zipCodeFirstThreeDigitsToStateMap.put("462",IN);
		zipCodeFirstThreeDigitsToStateMap.put("463",IN);
		zipCodeFirstThreeDigitsToStateMap.put("464",IN);
		zipCodeFirstThreeDigitsToStateMap.put("465",IN);
		zipCodeFirstThreeDigitsToStateMap.put("466",IN);
		zipCodeFirstThreeDigitsToStateMap.put("467",IN);
		zipCodeFirstThreeDigitsToStateMap.put("468",IN);
		zipCodeFirstThreeDigitsToStateMap.put("469",IN);
		zipCodeFirstThreeDigitsToStateMap.put("470",IN);
		zipCodeFirstThreeDigitsToStateMap.put("471",IN);
		zipCodeFirstThreeDigitsToStateMap.put("472",IN);
		zipCodeFirstThreeDigitsToStateMap.put("473",IN);
		zipCodeFirstThreeDigitsToStateMap.put("474",IN);
		zipCodeFirstThreeDigitsToStateMap.put("475",IN);
		zipCodeFirstThreeDigitsToStateMap.put("476",IN);
		zipCodeFirstThreeDigitsToStateMap.put("477",IN);
		zipCodeFirstThreeDigitsToStateMap.put("478",IN);
		zipCodeFirstThreeDigitsToStateMap.put("479",IN);
		zipCodeFirstThreeDigitsToStateMap.put("480",MI);
		zipCodeFirstThreeDigitsToStateMap.put("481",MI);
		zipCodeFirstThreeDigitsToStateMap.put("482",MI);
		zipCodeFirstThreeDigitsToStateMap.put("483",MI);
		zipCodeFirstThreeDigitsToStateMap.put("484",MI);
		zipCodeFirstThreeDigitsToStateMap.put("485",MI);
		zipCodeFirstThreeDigitsToStateMap.put("486",MI);
		zipCodeFirstThreeDigitsToStateMap.put("487",MI);
		zipCodeFirstThreeDigitsToStateMap.put("488",MI);
		zipCodeFirstThreeDigitsToStateMap.put("489",MI);
		zipCodeFirstThreeDigitsToStateMap.put("490",MI);
		zipCodeFirstThreeDigitsToStateMap.put("491",MI);
		zipCodeFirstThreeDigitsToStateMap.put("492",MI);
		zipCodeFirstThreeDigitsToStateMap.put("493",MI);
		zipCodeFirstThreeDigitsToStateMap.put("494",MI);
		zipCodeFirstThreeDigitsToStateMap.put("495",MI);
		zipCodeFirstThreeDigitsToStateMap.put("496",MI);
		zipCodeFirstThreeDigitsToStateMap.put("497",MI);
		zipCodeFirstThreeDigitsToStateMap.put("498",MI);
		zipCodeFirstThreeDigitsToStateMap.put("499",MI);
		zipCodeFirstThreeDigitsToStateMap.put("500",IA);
		zipCodeFirstThreeDigitsToStateMap.put("501",IA);
		zipCodeFirstThreeDigitsToStateMap.put("502",IA);
		zipCodeFirstThreeDigitsToStateMap.put("503",IA);
		zipCodeFirstThreeDigitsToStateMap.put("504",IA);
		zipCodeFirstThreeDigitsToStateMap.put("505",IA);
		zipCodeFirstThreeDigitsToStateMap.put("506",IA);
		zipCodeFirstThreeDigitsToStateMap.put("507",IA);
		zipCodeFirstThreeDigitsToStateMap.put("508",IA);
		zipCodeFirstThreeDigitsToStateMap.put("509",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("510",IA);
		zipCodeFirstThreeDigitsToStateMap.put("511",IA);
		zipCodeFirstThreeDigitsToStateMap.put("512",IA);
		zipCodeFirstThreeDigitsToStateMap.put("513",IA);
		zipCodeFirstThreeDigitsToStateMap.put("514",IA);
		zipCodeFirstThreeDigitsToStateMap.put("515",IA);
		zipCodeFirstThreeDigitsToStateMap.put("516",IA);
		zipCodeFirstThreeDigitsToStateMap.put("517",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("518",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("519",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("520",IA);
		zipCodeFirstThreeDigitsToStateMap.put("521",IA);
		zipCodeFirstThreeDigitsToStateMap.put("522",IA);
		zipCodeFirstThreeDigitsToStateMap.put("523",IA);
		zipCodeFirstThreeDigitsToStateMap.put("524",IA);
		zipCodeFirstThreeDigitsToStateMap.put("525",IA);
		zipCodeFirstThreeDigitsToStateMap.put("526",IA);
		zipCodeFirstThreeDigitsToStateMap.put("527",IA);
		zipCodeFirstThreeDigitsToStateMap.put("528",IA);
		zipCodeFirstThreeDigitsToStateMap.put("529",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("530",WI);
		zipCodeFirstThreeDigitsToStateMap.put("531",WI);
		zipCodeFirstThreeDigitsToStateMap.put("532",WI);
		zipCodeFirstThreeDigitsToStateMap.put("533",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("534",WI);
		zipCodeFirstThreeDigitsToStateMap.put("535",WI);
		zipCodeFirstThreeDigitsToStateMap.put("536",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("537",WI);
		zipCodeFirstThreeDigitsToStateMap.put("538",WI);
		zipCodeFirstThreeDigitsToStateMap.put("539",WI);
		zipCodeFirstThreeDigitsToStateMap.put("540",WI);
		zipCodeFirstThreeDigitsToStateMap.put("541",WI);
		zipCodeFirstThreeDigitsToStateMap.put("542",WI);
		zipCodeFirstThreeDigitsToStateMap.put("543",WI);
		zipCodeFirstThreeDigitsToStateMap.put("544",WI);
		zipCodeFirstThreeDigitsToStateMap.put("545",WI);
		zipCodeFirstThreeDigitsToStateMap.put("546",WI);
		zipCodeFirstThreeDigitsToStateMap.put("547",WI);
		zipCodeFirstThreeDigitsToStateMap.put("548",WI);
		zipCodeFirstThreeDigitsToStateMap.put("549",WI);
		zipCodeFirstThreeDigitsToStateMap.put("550",MN);
		zipCodeFirstThreeDigitsToStateMap.put("551",MN);
		zipCodeFirstThreeDigitsToStateMap.put("552",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("553",MN);
		zipCodeFirstThreeDigitsToStateMap.put("554",MN);
		zipCodeFirstThreeDigitsToStateMap.put("555",MN);
		zipCodeFirstThreeDigitsToStateMap.put("556",MN);
		zipCodeFirstThreeDigitsToStateMap.put("557",MN);
		zipCodeFirstThreeDigitsToStateMap.put("558",MN);
		zipCodeFirstThreeDigitsToStateMap.put("559",MN);
		zipCodeFirstThreeDigitsToStateMap.put("560",MN);
		zipCodeFirstThreeDigitsToStateMap.put("561",MN);
		zipCodeFirstThreeDigitsToStateMap.put("562",MN);
		zipCodeFirstThreeDigitsToStateMap.put("563",MN);
		zipCodeFirstThreeDigitsToStateMap.put("564",MN);
		zipCodeFirstThreeDigitsToStateMap.put("565",MN);
		zipCodeFirstThreeDigitsToStateMap.put("566",MN);
		zipCodeFirstThreeDigitsToStateMap.put("567",MN);
		zipCodeFirstThreeDigitsToStateMap.put("568",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("569",DC);
		zipCodeFirstThreeDigitsToStateMap.put("570",SD);
		zipCodeFirstThreeDigitsToStateMap.put("571",SD);
		zipCodeFirstThreeDigitsToStateMap.put("572",SD);
		zipCodeFirstThreeDigitsToStateMap.put("573",SD);
		zipCodeFirstThreeDigitsToStateMap.put("574",SD);
		zipCodeFirstThreeDigitsToStateMap.put("575",SD);
		zipCodeFirstThreeDigitsToStateMap.put("576",SD);
		zipCodeFirstThreeDigitsToStateMap.put("577",SD);
		zipCodeFirstThreeDigitsToStateMap.put("578",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("579",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("580",ND);
		zipCodeFirstThreeDigitsToStateMap.put("581",ND);
		zipCodeFirstThreeDigitsToStateMap.put("582",ND);
		zipCodeFirstThreeDigitsToStateMap.put("583",ND);
		zipCodeFirstThreeDigitsToStateMap.put("584",ND);
		zipCodeFirstThreeDigitsToStateMap.put("585",ND);
		zipCodeFirstThreeDigitsToStateMap.put("586",ND);
		zipCodeFirstThreeDigitsToStateMap.put("587",ND);
		zipCodeFirstThreeDigitsToStateMap.put("588",ND);
		zipCodeFirstThreeDigitsToStateMap.put("589",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("590",MT);
		zipCodeFirstThreeDigitsToStateMap.put("591",MT);
		zipCodeFirstThreeDigitsToStateMap.put("592",MT);
		zipCodeFirstThreeDigitsToStateMap.put("593",MT);
		zipCodeFirstThreeDigitsToStateMap.put("594",MT);
		zipCodeFirstThreeDigitsToStateMap.put("595",MT);
		zipCodeFirstThreeDigitsToStateMap.put("596",MT);
		zipCodeFirstThreeDigitsToStateMap.put("597",MT);
		zipCodeFirstThreeDigitsToStateMap.put("598",MT);
		zipCodeFirstThreeDigitsToStateMap.put("599",MT);
		zipCodeFirstThreeDigitsToStateMap.put("600",IL);
		zipCodeFirstThreeDigitsToStateMap.put("601",IL);
		zipCodeFirstThreeDigitsToStateMap.put("602",IL);
		zipCodeFirstThreeDigitsToStateMap.put("603",IL);
		zipCodeFirstThreeDigitsToStateMap.put("604",IL);
		zipCodeFirstThreeDigitsToStateMap.put("605",IL);
		zipCodeFirstThreeDigitsToStateMap.put("606",IL);
		zipCodeFirstThreeDigitsToStateMap.put("607",IL);
		zipCodeFirstThreeDigitsToStateMap.put("608",IL);
		zipCodeFirstThreeDigitsToStateMap.put("609",IL);
		zipCodeFirstThreeDigitsToStateMap.put("610",IL);
		zipCodeFirstThreeDigitsToStateMap.put("611",IL);
		zipCodeFirstThreeDigitsToStateMap.put("612",IL);
		zipCodeFirstThreeDigitsToStateMap.put("613",IL);
		zipCodeFirstThreeDigitsToStateMap.put("614",IL);
		zipCodeFirstThreeDigitsToStateMap.put("615",IL);
		zipCodeFirstThreeDigitsToStateMap.put("616",IL);
		zipCodeFirstThreeDigitsToStateMap.put("617",IL);
		zipCodeFirstThreeDigitsToStateMap.put("618",IL);
		zipCodeFirstThreeDigitsToStateMap.put("619",IL);
		zipCodeFirstThreeDigitsToStateMap.put("620",IL);
		zipCodeFirstThreeDigitsToStateMap.put("621",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("622",IL);
		zipCodeFirstThreeDigitsToStateMap.put("623",IL);
		zipCodeFirstThreeDigitsToStateMap.put("624",IL);
		zipCodeFirstThreeDigitsToStateMap.put("625",IL);
		zipCodeFirstThreeDigitsToStateMap.put("626",IL);
		zipCodeFirstThreeDigitsToStateMap.put("627",IL);
		zipCodeFirstThreeDigitsToStateMap.put("628",IL);
		zipCodeFirstThreeDigitsToStateMap.put("629",IL);
		zipCodeFirstThreeDigitsToStateMap.put("630",MO);
		zipCodeFirstThreeDigitsToStateMap.put("631",MO);
		zipCodeFirstThreeDigitsToStateMap.put("632",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("633",MO);
		zipCodeFirstThreeDigitsToStateMap.put("634",MO);
		zipCodeFirstThreeDigitsToStateMap.put("635",MO);
		zipCodeFirstThreeDigitsToStateMap.put("636",MO);
		zipCodeFirstThreeDigitsToStateMap.put("637",MO);
		zipCodeFirstThreeDigitsToStateMap.put("638",MO);
		zipCodeFirstThreeDigitsToStateMap.put("639",MO);
		zipCodeFirstThreeDigitsToStateMap.put("640",MO);
		zipCodeFirstThreeDigitsToStateMap.put("641",MO);
		zipCodeFirstThreeDigitsToStateMap.put("642",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("643",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("644",MO);
		zipCodeFirstThreeDigitsToStateMap.put("645",MO);
		zipCodeFirstThreeDigitsToStateMap.put("646",MO);
		zipCodeFirstThreeDigitsToStateMap.put("647",MO);
		zipCodeFirstThreeDigitsToStateMap.put("648",MO);
		zipCodeFirstThreeDigitsToStateMap.put("649",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("650",MO);
		zipCodeFirstThreeDigitsToStateMap.put("651",MO);
		zipCodeFirstThreeDigitsToStateMap.put("652",MO);
		zipCodeFirstThreeDigitsToStateMap.put("653",MO);
		zipCodeFirstThreeDigitsToStateMap.put("654",MO);
		zipCodeFirstThreeDigitsToStateMap.put("655",MO);
		zipCodeFirstThreeDigitsToStateMap.put("656",MO);
		zipCodeFirstThreeDigitsToStateMap.put("657",MO);
		zipCodeFirstThreeDigitsToStateMap.put("658",MO);
		zipCodeFirstThreeDigitsToStateMap.put("659",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("660",KS);
		zipCodeFirstThreeDigitsToStateMap.put("661",KS);
		zipCodeFirstThreeDigitsToStateMap.put("662",KS);
		zipCodeFirstThreeDigitsToStateMap.put("663",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("664",KS);
		zipCodeFirstThreeDigitsToStateMap.put("665",KS);
		zipCodeFirstThreeDigitsToStateMap.put("666",KS);
		zipCodeFirstThreeDigitsToStateMap.put("667",KS);
		zipCodeFirstThreeDigitsToStateMap.put("668",KS);
		zipCodeFirstThreeDigitsToStateMap.put("669",KS);
		zipCodeFirstThreeDigitsToStateMap.put("670",KS);
		zipCodeFirstThreeDigitsToStateMap.put("671",KS);
		zipCodeFirstThreeDigitsToStateMap.put("672",KS);
		zipCodeFirstThreeDigitsToStateMap.put("673",KS);
		zipCodeFirstThreeDigitsToStateMap.put("674",KS);
		zipCodeFirstThreeDigitsToStateMap.put("675",KS);
		zipCodeFirstThreeDigitsToStateMap.put("676",KS);
		zipCodeFirstThreeDigitsToStateMap.put("677",KS);
		zipCodeFirstThreeDigitsToStateMap.put("678",KS);
		zipCodeFirstThreeDigitsToStateMap.put("679",KS);
		zipCodeFirstThreeDigitsToStateMap.put("680",NE);
		zipCodeFirstThreeDigitsToStateMap.put("681",NE);
		zipCodeFirstThreeDigitsToStateMap.put("682",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("683",NE);
		zipCodeFirstThreeDigitsToStateMap.put("684",NE);
		zipCodeFirstThreeDigitsToStateMap.put("685",NE);
		zipCodeFirstThreeDigitsToStateMap.put("686",NE);
		zipCodeFirstThreeDigitsToStateMap.put("687",NE);
		zipCodeFirstThreeDigitsToStateMap.put("688",NE);
		zipCodeFirstThreeDigitsToStateMap.put("689",NE);
		zipCodeFirstThreeDigitsToStateMap.put("690",NE);
		zipCodeFirstThreeDigitsToStateMap.put("691",NE);
		zipCodeFirstThreeDigitsToStateMap.put("692",NE);
		zipCodeFirstThreeDigitsToStateMap.put("693",NE);
		zipCodeFirstThreeDigitsToStateMap.put("694",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("695",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("696",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("697",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("698",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("699",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("700",LA);
		zipCodeFirstThreeDigitsToStateMap.put("701",LA);
		zipCodeFirstThreeDigitsToStateMap.put("702",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("703",LA);
		zipCodeFirstThreeDigitsToStateMap.put("704",LA);
		zipCodeFirstThreeDigitsToStateMap.put("705",LA);
		zipCodeFirstThreeDigitsToStateMap.put("706",LA);
		zipCodeFirstThreeDigitsToStateMap.put("707",LA);
		zipCodeFirstThreeDigitsToStateMap.put("708",LA);
		zipCodeFirstThreeDigitsToStateMap.put("709",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("710",LA);
		zipCodeFirstThreeDigitsToStateMap.put("711",LA);
		zipCodeFirstThreeDigitsToStateMap.put("712",LA);
		zipCodeFirstThreeDigitsToStateMap.put("713",LA);
		zipCodeFirstThreeDigitsToStateMap.put("714",LA);
		zipCodeFirstThreeDigitsToStateMap.put("715",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("716",AR);
		zipCodeFirstThreeDigitsToStateMap.put("717",AR);
		zipCodeFirstThreeDigitsToStateMap.put("718",AR);
		zipCodeFirstThreeDigitsToStateMap.put("719",AR);
		zipCodeFirstThreeDigitsToStateMap.put("720",AR);
		zipCodeFirstThreeDigitsToStateMap.put("721",AR);
		zipCodeFirstThreeDigitsToStateMap.put("722",AR);
		zipCodeFirstThreeDigitsToStateMap.put("723",AR);
		zipCodeFirstThreeDigitsToStateMap.put("724",AR);
		zipCodeFirstThreeDigitsToStateMap.put("725",AR);
		zipCodeFirstThreeDigitsToStateMap.put("726",AR);
		zipCodeFirstThreeDigitsToStateMap.put("727",AR);
		zipCodeFirstThreeDigitsToStateMap.put("728",AR);
		zipCodeFirstThreeDigitsToStateMap.put("729",AR);
		zipCodeFirstThreeDigitsToStateMap.put("730",OK);
		zipCodeFirstThreeDigitsToStateMap.put("731",OK);
		zipCodeFirstThreeDigitsToStateMap.put("732",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("733",TX);
		zipCodeFirstThreeDigitsToStateMap.put("734",OK);
		zipCodeFirstThreeDigitsToStateMap.put("735",OK);
		zipCodeFirstThreeDigitsToStateMap.put("736",OK);
		zipCodeFirstThreeDigitsToStateMap.put("737",OK);
		zipCodeFirstThreeDigitsToStateMap.put("738",OK);
		zipCodeFirstThreeDigitsToStateMap.put("739",OK);
		zipCodeFirstThreeDigitsToStateMap.put("740",OK);
		zipCodeFirstThreeDigitsToStateMap.put("741",OK);
		zipCodeFirstThreeDigitsToStateMap.put("742",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("743",OK);
		zipCodeFirstThreeDigitsToStateMap.put("744",OK);
		zipCodeFirstThreeDigitsToStateMap.put("745",OK);
		zipCodeFirstThreeDigitsToStateMap.put("746",OK);
		zipCodeFirstThreeDigitsToStateMap.put("747",OK);
		zipCodeFirstThreeDigitsToStateMap.put("748",OK);
		zipCodeFirstThreeDigitsToStateMap.put("749",OK);
		zipCodeFirstThreeDigitsToStateMap.put("750",TX);
		zipCodeFirstThreeDigitsToStateMap.put("751",TX);
		zipCodeFirstThreeDigitsToStateMap.put("752",TX);
		zipCodeFirstThreeDigitsToStateMap.put("753",TX);
		zipCodeFirstThreeDigitsToStateMap.put("754",TX);
		zipCodeFirstThreeDigitsToStateMap.put("755",TX);
		zipCodeFirstThreeDigitsToStateMap.put("756",TX);
		zipCodeFirstThreeDigitsToStateMap.put("757",TX);
		zipCodeFirstThreeDigitsToStateMap.put("758",TX);
		zipCodeFirstThreeDigitsToStateMap.put("759",TX);
		zipCodeFirstThreeDigitsToStateMap.put("760",TX);
		zipCodeFirstThreeDigitsToStateMap.put("761",TX);
		zipCodeFirstThreeDigitsToStateMap.put("762",TX);
		zipCodeFirstThreeDigitsToStateMap.put("763",TX);
		zipCodeFirstThreeDigitsToStateMap.put("764",TX);
		zipCodeFirstThreeDigitsToStateMap.put("765",TX);
		zipCodeFirstThreeDigitsToStateMap.put("766",TX);
		zipCodeFirstThreeDigitsToStateMap.put("767",TX);
		zipCodeFirstThreeDigitsToStateMap.put("768",TX);
		zipCodeFirstThreeDigitsToStateMap.put("769",TX);
		zipCodeFirstThreeDigitsToStateMap.put("770",TX);
		zipCodeFirstThreeDigitsToStateMap.put("771",TX);
		zipCodeFirstThreeDigitsToStateMap.put("772",TX);
		zipCodeFirstThreeDigitsToStateMap.put("773",TX);
		zipCodeFirstThreeDigitsToStateMap.put("774",TX);
		zipCodeFirstThreeDigitsToStateMap.put("775",TX);
		zipCodeFirstThreeDigitsToStateMap.put("776",TX);
		zipCodeFirstThreeDigitsToStateMap.put("777",TX);
		zipCodeFirstThreeDigitsToStateMap.put("778",TX);
		zipCodeFirstThreeDigitsToStateMap.put("779",TX);
		zipCodeFirstThreeDigitsToStateMap.put("780",TX);
		zipCodeFirstThreeDigitsToStateMap.put("781",TX);
		zipCodeFirstThreeDigitsToStateMap.put("782",TX);
		zipCodeFirstThreeDigitsToStateMap.put("783",TX);
		zipCodeFirstThreeDigitsToStateMap.put("784",TX);
		zipCodeFirstThreeDigitsToStateMap.put("785",TX);
		zipCodeFirstThreeDigitsToStateMap.put("786",TX);
		zipCodeFirstThreeDigitsToStateMap.put("787",TX);
		zipCodeFirstThreeDigitsToStateMap.put("788",TX);
		zipCodeFirstThreeDigitsToStateMap.put("789",TX);
		zipCodeFirstThreeDigitsToStateMap.put("790",TX);
		zipCodeFirstThreeDigitsToStateMap.put("791",TX);
		zipCodeFirstThreeDigitsToStateMap.put("792",TX);
		zipCodeFirstThreeDigitsToStateMap.put("793",TX);
		zipCodeFirstThreeDigitsToStateMap.put("794",TX);
		zipCodeFirstThreeDigitsToStateMap.put("795",TX);
		zipCodeFirstThreeDigitsToStateMap.put("796",TX);
		zipCodeFirstThreeDigitsToStateMap.put("797",TX);
		zipCodeFirstThreeDigitsToStateMap.put("798",TX);
		zipCodeFirstThreeDigitsToStateMap.put("799",TX);
		zipCodeFirstThreeDigitsToStateMap.put("800",CO);
		zipCodeFirstThreeDigitsToStateMap.put("801",CO);
		zipCodeFirstThreeDigitsToStateMap.put("802",CO);
		zipCodeFirstThreeDigitsToStateMap.put("803",CO);
		zipCodeFirstThreeDigitsToStateMap.put("804",CO);
		zipCodeFirstThreeDigitsToStateMap.put("805",CO);
		zipCodeFirstThreeDigitsToStateMap.put("806",CO);
		zipCodeFirstThreeDigitsToStateMap.put("807",CO);
		zipCodeFirstThreeDigitsToStateMap.put("808",CO);
		zipCodeFirstThreeDigitsToStateMap.put("809",CO);
		zipCodeFirstThreeDigitsToStateMap.put("810",CO);
		zipCodeFirstThreeDigitsToStateMap.put("811",CO);
		zipCodeFirstThreeDigitsToStateMap.put("812",CO);
		zipCodeFirstThreeDigitsToStateMap.put("813",CO);
		zipCodeFirstThreeDigitsToStateMap.put("814",CO);
		zipCodeFirstThreeDigitsToStateMap.put("815",CO);
		zipCodeFirstThreeDigitsToStateMap.put("816",CO);
		zipCodeFirstThreeDigitsToStateMap.put("817",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("818",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("819",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("820",WY);
		zipCodeFirstThreeDigitsToStateMap.put("821",WY);
		zipCodeFirstThreeDigitsToStateMap.put("822",WY);
		zipCodeFirstThreeDigitsToStateMap.put("823",WY);
		zipCodeFirstThreeDigitsToStateMap.put("824",WY);
		zipCodeFirstThreeDigitsToStateMap.put("825",WY);
		zipCodeFirstThreeDigitsToStateMap.put("826",WY);
		zipCodeFirstThreeDigitsToStateMap.put("827",WY);
		zipCodeFirstThreeDigitsToStateMap.put("828",WY);
		zipCodeFirstThreeDigitsToStateMap.put("829",WY);
		zipCodeFirstThreeDigitsToStateMap.put("830",WY);
		zipCodeFirstThreeDigitsToStateMap.put("831",WY);
		zipCodeFirstThreeDigitsToStateMap.put("832",ID);
		zipCodeFirstThreeDigitsToStateMap.put("833",ID);
		zipCodeFirstThreeDigitsToStateMap.put("834",ID);
		zipCodeFirstThreeDigitsToStateMap.put("835",ID);
		zipCodeFirstThreeDigitsToStateMap.put("836",ID);
		zipCodeFirstThreeDigitsToStateMap.put("837",ID);
		zipCodeFirstThreeDigitsToStateMap.put("838",ID);
		zipCodeFirstThreeDigitsToStateMap.put("839",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("840",UT);
		zipCodeFirstThreeDigitsToStateMap.put("841",UT);
		zipCodeFirstThreeDigitsToStateMap.put("842",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("843",UT);
		zipCodeFirstThreeDigitsToStateMap.put("844",UT);
		zipCodeFirstThreeDigitsToStateMap.put("845",UT);
		zipCodeFirstThreeDigitsToStateMap.put("846",UT);
		zipCodeFirstThreeDigitsToStateMap.put("847",UT);
		zipCodeFirstThreeDigitsToStateMap.put("848",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("849",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("850",AZ);
		zipCodeFirstThreeDigitsToStateMap.put("851",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("852",AZ);
		zipCodeFirstThreeDigitsToStateMap.put("853",AZ);
		zipCodeFirstThreeDigitsToStateMap.put("854",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("855",AZ);
		zipCodeFirstThreeDigitsToStateMap.put("856",AZ);
		zipCodeFirstThreeDigitsToStateMap.put("857",AZ);
		zipCodeFirstThreeDigitsToStateMap.put("858",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("859",AZ);
		zipCodeFirstThreeDigitsToStateMap.put("860",AZ);
		zipCodeFirstThreeDigitsToStateMap.put("861",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("862",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("863",AZ);
		zipCodeFirstThreeDigitsToStateMap.put("864",AZ);
		zipCodeFirstThreeDigitsToStateMap.put("865",AZ);
		zipCodeFirstThreeDigitsToStateMap.put("866",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("867",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("868",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("869",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("870",NM);
		zipCodeFirstThreeDigitsToStateMap.put("871",NM);
		zipCodeFirstThreeDigitsToStateMap.put("872",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("873",NM);
		zipCodeFirstThreeDigitsToStateMap.put("874",NM);
		zipCodeFirstThreeDigitsToStateMap.put("875",NM);
		zipCodeFirstThreeDigitsToStateMap.put("876",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("877",NM);
		zipCodeFirstThreeDigitsToStateMap.put("878",NM);
		zipCodeFirstThreeDigitsToStateMap.put("879",NM);
		zipCodeFirstThreeDigitsToStateMap.put("880",NM);
		zipCodeFirstThreeDigitsToStateMap.put("881",NM);
		zipCodeFirstThreeDigitsToStateMap.put("882",NM);
		zipCodeFirstThreeDigitsToStateMap.put("883",NM);
		zipCodeFirstThreeDigitsToStateMap.put("884",NM);
		zipCodeFirstThreeDigitsToStateMap.put("885",NM);
		zipCodeFirstThreeDigitsToStateMap.put("886",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("887",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("888",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("889",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("890",NV);
		zipCodeFirstThreeDigitsToStateMap.put("891",NV);
		zipCodeFirstThreeDigitsToStateMap.put("892",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("893",NV);
		zipCodeFirstThreeDigitsToStateMap.put("894",NV);
		zipCodeFirstThreeDigitsToStateMap.put("895",NV);
		zipCodeFirstThreeDigitsToStateMap.put("896",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("897",NV);
		zipCodeFirstThreeDigitsToStateMap.put("898",NV);
		zipCodeFirstThreeDigitsToStateMap.put("899",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("900",CA);
		zipCodeFirstThreeDigitsToStateMap.put("901",CA);
		zipCodeFirstThreeDigitsToStateMap.put("902",CA);
		zipCodeFirstThreeDigitsToStateMap.put("903",CA);
		zipCodeFirstThreeDigitsToStateMap.put("904",CA);
		zipCodeFirstThreeDigitsToStateMap.put("905",CA);
		zipCodeFirstThreeDigitsToStateMap.put("906",CA);
		zipCodeFirstThreeDigitsToStateMap.put("907",CA);
		zipCodeFirstThreeDigitsToStateMap.put("908",CA);
		zipCodeFirstThreeDigitsToStateMap.put("909",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("910",CA);
		zipCodeFirstThreeDigitsToStateMap.put("911",CA);
		zipCodeFirstThreeDigitsToStateMap.put("912",CA);
		zipCodeFirstThreeDigitsToStateMap.put("913",CA);
		zipCodeFirstThreeDigitsToStateMap.put("914",CA);
		zipCodeFirstThreeDigitsToStateMap.put("915",CA);
		zipCodeFirstThreeDigitsToStateMap.put("916",CA);
		zipCodeFirstThreeDigitsToStateMap.put("917",CA);
		zipCodeFirstThreeDigitsToStateMap.put("918",CA);
		zipCodeFirstThreeDigitsToStateMap.put("919",CA);
		zipCodeFirstThreeDigitsToStateMap.put("920",CA);
		zipCodeFirstThreeDigitsToStateMap.put("921",CA);
		zipCodeFirstThreeDigitsToStateMap.put("920",CA);
		zipCodeFirstThreeDigitsToStateMap.put("923",CA);
		zipCodeFirstThreeDigitsToStateMap.put("924",CA);
		zipCodeFirstThreeDigitsToStateMap.put("925",CA);
		zipCodeFirstThreeDigitsToStateMap.put("926",CA);
		zipCodeFirstThreeDigitsToStateMap.put("927",CA);
		zipCodeFirstThreeDigitsToStateMap.put("928",CA);
		zipCodeFirstThreeDigitsToStateMap.put("929",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("930",CA);
		zipCodeFirstThreeDigitsToStateMap.put("931",CA);
		zipCodeFirstThreeDigitsToStateMap.put("932",CA);
		zipCodeFirstThreeDigitsToStateMap.put("933",CA);
		zipCodeFirstThreeDigitsToStateMap.put("934",CA);
		zipCodeFirstThreeDigitsToStateMap.put("935",CA);
		zipCodeFirstThreeDigitsToStateMap.put("936",CA);
		zipCodeFirstThreeDigitsToStateMap.put("937",CA);
		zipCodeFirstThreeDigitsToStateMap.put("938",CA);
		zipCodeFirstThreeDigitsToStateMap.put("939",CA);
		zipCodeFirstThreeDigitsToStateMap.put("940",CA);
		zipCodeFirstThreeDigitsToStateMap.put("941",CA);
		zipCodeFirstThreeDigitsToStateMap.put("942",CA);
		zipCodeFirstThreeDigitsToStateMap.put("943",CA);
		zipCodeFirstThreeDigitsToStateMap.put("944",CA);
		zipCodeFirstThreeDigitsToStateMap.put("945",CA);
		zipCodeFirstThreeDigitsToStateMap.put("946",CA);
		zipCodeFirstThreeDigitsToStateMap.put("947",CA);
		zipCodeFirstThreeDigitsToStateMap.put("948",CA);
		zipCodeFirstThreeDigitsToStateMap.put("949",CA);
		zipCodeFirstThreeDigitsToStateMap.put("950",CA);
		zipCodeFirstThreeDigitsToStateMap.put("951",CA);
		zipCodeFirstThreeDigitsToStateMap.put("952",CA);
		zipCodeFirstThreeDigitsToStateMap.put("953",CA);
		zipCodeFirstThreeDigitsToStateMap.put("954",CA);
		zipCodeFirstThreeDigitsToStateMap.put("955",CA);
		zipCodeFirstThreeDigitsToStateMap.put("956",CA);
		zipCodeFirstThreeDigitsToStateMap.put("957",CA);
		zipCodeFirstThreeDigitsToStateMap.put("958",CA);
		zipCodeFirstThreeDigitsToStateMap.put("959",CA);
		zipCodeFirstThreeDigitsToStateMap.put("960",CA);
		zipCodeFirstThreeDigitsToStateMap.put("961",CA);
		zipCodeFirstThreeDigitsToStateMap.put("962",AP);
		zipCodeFirstThreeDigitsToStateMap.put("963",AP);
		zipCodeFirstThreeDigitsToStateMap.put("964",AP);
		zipCodeFirstThreeDigitsToStateMap.put("965",AP);
		zipCodeFirstThreeDigitsToStateMap.put("966",AP);
		zipCodeFirstThreeDigitsToStateMap.put("967",HI_or_AS);
		zipCodeFirstThreeDigitsToStateMap.put("968",HI);
		zipCodeFirstThreeDigitsToStateMap.put("969",FM_or_GU_or_MH_or_MP_or_PW);
		zipCodeFirstThreeDigitsToStateMap.put("970",OR);
		zipCodeFirstThreeDigitsToStateMap.put("971",OR);
		zipCodeFirstThreeDigitsToStateMap.put("972",OR);
		zipCodeFirstThreeDigitsToStateMap.put("973",OR);
		zipCodeFirstThreeDigitsToStateMap.put("974",OR);
		zipCodeFirstThreeDigitsToStateMap.put("975",OR);
		zipCodeFirstThreeDigitsToStateMap.put("976",OR);
		zipCodeFirstThreeDigitsToStateMap.put("977",OR);
		zipCodeFirstThreeDigitsToStateMap.put("978",OR);
		zipCodeFirstThreeDigitsToStateMap.put("979",OR);
		zipCodeFirstThreeDigitsToStateMap.put("980",WA);
		zipCodeFirstThreeDigitsToStateMap.put("981",WA);
		zipCodeFirstThreeDigitsToStateMap.put("982",WA);
		zipCodeFirstThreeDigitsToStateMap.put("983",WA);
		zipCodeFirstThreeDigitsToStateMap.put("984",WA);
		zipCodeFirstThreeDigitsToStateMap.put("985",WA);
		zipCodeFirstThreeDigitsToStateMap.put("986",WA);
		zipCodeFirstThreeDigitsToStateMap.put("987",UNUSED_ZIP_CODE);
		zipCodeFirstThreeDigitsToStateMap.put("988",WA);
		zipCodeFirstThreeDigitsToStateMap.put("989",WA);
		zipCodeFirstThreeDigitsToStateMap.put("990",WA);
		zipCodeFirstThreeDigitsToStateMap.put("991",WA);
		zipCodeFirstThreeDigitsToStateMap.put("992",WA);
		zipCodeFirstThreeDigitsToStateMap.put("993",WA);
		zipCodeFirstThreeDigitsToStateMap.put("994",WA);
		zipCodeFirstThreeDigitsToStateMap.put("995",AK);
		zipCodeFirstThreeDigitsToStateMap.put("996",AK);
		zipCodeFirstThreeDigitsToStateMap.put("997",AK);
		zipCodeFirstThreeDigitsToStateMap.put("998",AK);
		zipCodeFirstThreeDigitsToStateMap.put("999",AK);
	}
	/**
	 * These all share 3-digit prefixes with Hawaii or with one another 
	 */
	private static final Map<String, String> fourDigitUSPosessionLookup = new LinkedHashMap<String, String>();

	static {
		fourDigitUSPosessionLookup.put("96799",AS);
		fourDigitUSPosessionLookup.put("96941",FM);
		fourDigitUSPosessionLookup.put("96942",FM);
		fourDigitUSPosessionLookup.put("96943",FM);
		fourDigitUSPosessionLookup.put("96944",FM);
		fourDigitUSPosessionLookup.put("96910",GU);
		fourDigitUSPosessionLookup.put("96912",GU);
		fourDigitUSPosessionLookup.put("96913",GU);
		fourDigitUSPosessionLookup.put("96915",GU);
		fourDigitUSPosessionLookup.put("96916",GU);
		fourDigitUSPosessionLookup.put("96917",GU);
		fourDigitUSPosessionLookup.put("96919",GU);
		fourDigitUSPosessionLookup.put("96921",GU);
		fourDigitUSPosessionLookup.put("96923",GU);
		fourDigitUSPosessionLookup.put("96928",GU);
		fourDigitUSPosessionLookup.put("96929",GU);
		fourDigitUSPosessionLookup.put("96931",GU);
		fourDigitUSPosessionLookup.put("96932",GU);
		fourDigitUSPosessionLookup.put("96960",MH);
		fourDigitUSPosessionLookup.put("96970",MH);
		fourDigitUSPosessionLookup.put("96950",MP);
		fourDigitUSPosessionLookup.put("96951",MP);
		fourDigitUSPosessionLookup.put("96952",MP);
		fourDigitUSPosessionLookup.put("96939",PW);
		fourDigitUSPosessionLookup.put("96940",PW);
	}
	
	/**
	 * Accepts 5 digits OR 5+4 digits
	 * 
	 * This will return null if nothing is found.
	 * 
	 * It can also return results that are not valid for BSRO stores. 
	 * 
	 * @param zipCode
	 * @return
	 */
	private String lookupStateByZipCode(String zipCode) {
		String myZipCode = null;
		
		if (zipCode != null && zipCode.length() >= 5) {
			if (zipCode.length() != 5) {
				if (zipCode.indexOf(ZIP_CODE_DELIMITER) == 5) {
					String[] zipCodeComponents = zipCode.split(ZIP_CODE_DELIMITER);
					myZipCode = zipCodeComponents[0];
				}
			} else {
				myZipCode = zipCode;
			}
			
			if (myZipCode != null) {
				String myZipCodeThreeDigitPrefix = myZipCode.substring(0, 3);
				String initialResult = zipCodeFirstThreeDigitsToStateMap.get(myZipCodeThreeDigitPrefix);
				
				if (initialResult != null) {
					if (initialResult.equals(HI_or_AS)) {
						String usPosessionResult = fourDigitUSPosessionLookup.get(myZipCode);
						if (usPosessionResult == null) {
							return HI;
						} else {
							return usPosessionResult;
						}
					} else if (initialResult.equals(FM_or_GU_or_MH_or_MP_or_PW)) {
						return fourDigitUSPosessionLookup.get(myZipCode);
					} else {
						return initialResult;
					}
				}
			}
		}
		
		return null;
	}
	
	/**
	 * Accepts 5 digits OR 5+4 digits
	 * 
	 * This will return null if nothing is found.
	 * 
	 * It can also return results that are not valid for BSRO stores. 
	 * 
	 * @param zipCode
	 * @return
	 */
	public String lookupStateWithStoresByZipCode(String zipCode) {
		String state = lookupStateByZipCode(zipCode);
		
		if (state != null) {
			map.States stateList = locatorOperator.getGeocodeOperator().getStates();
			
			if (stateList.containsKey(state)) {
				return state;
			}
		}
		
		return null;
	}
}
