package com.bfrc.pojo.pricing;

import java.math.BigDecimal;
import java.util.Set;
import java.util.List;

/**
 * Store generated by hbm2java
 */

public class StoreOnlinePurchase implements java.io.Serializable {


	private Long storeNumber;

	// Constructors

	/** default constructor */
	public StoreOnlinePurchase() {
	}

	/** constructor with id */
	public StoreOnlinePurchase(Long storeNumber) {
		this.storeNumber = storeNumber;
	}
	
	// Property accessors

	public Long getStoreNumber() {
		return this.storeNumber;
	}

	public void setStoreNumber(Long storeNumber) {
		this.storeNumber = storeNumber;
	}
}