package com.bfrc.pojo.pricing;

// Generated Jun 18, 2007 10:31:30 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;

/**
 * TpHierarchyPriceTestId generated by hbm2java
 */
public class TpHierarchyPriceTestId implements java.io.Serializable {

	// Fields    

	private long priceBookId;

	private long line;

	private BigDecimal valveStem;

	private BigDecimal wheelBalanceWeight;

	private BigDecimal wheelBalanceLabor;

	// Constructors

	/** default constructor */
	public TpHierarchyPriceTestId() {
	}

	/** full constructor */
	public TpHierarchyPriceTestId(long priceBookId, long line,
			BigDecimal valveStem, BigDecimal wheelBalanceWeight,
			BigDecimal wheelBalanceLabor) {
		this.priceBookId = priceBookId;
		this.line = line;
		this.valveStem = valveStem;
		this.wheelBalanceWeight = wheelBalanceWeight;
		this.wheelBalanceLabor = wheelBalanceLabor;
	}

	// Property accessors
	public long getPriceBookId() {
		return this.priceBookId;
	}

	public void setPriceBookId(long priceBookId) {
		this.priceBookId = priceBookId;
	}

	public long getLine() {
		return this.line;
	}

	public void setLine(long line) {
		this.line = line;
	}

	public BigDecimal getValveStem() {
		return this.valveStem;
	}

	public void setValveStem(BigDecimal valveStem) {
		this.valveStem = valveStem;
	}

	public BigDecimal getWheelBalanceWeight() {
		return this.wheelBalanceWeight;
	}

	public void setWheelBalanceWeight(BigDecimal wheelBalanceWeight) {
		this.wheelBalanceWeight = wheelBalanceWeight;
	}

	public BigDecimal getWheelBalanceLabor() {
		return this.wheelBalanceLabor;
	}

	public void setWheelBalanceLabor(BigDecimal wheelBalanceLabor) {
		this.wheelBalanceLabor = wheelBalanceLabor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TpHierarchyPriceTestId))
			return false;
		TpHierarchyPriceTestId castOther = (TpHierarchyPriceTestId) other;

		return (this.getPriceBookId() == castOther.getPriceBookId())
				&& (this.getLine() == castOther.getLine())
				&& ((this.getValveStem() == castOther.getValveStem()) || (this
						.getValveStem() != null
						&& castOther.getValveStem() != null && this
						.getValveStem().equals(castOther.getValveStem())))
				&& ((this.getWheelBalanceWeight() == castOther
						.getWheelBalanceWeight()) || (this
						.getWheelBalanceWeight() != null
						&& castOther.getWheelBalanceWeight() != null && this
						.getWheelBalanceWeight().equals(
								castOther.getWheelBalanceWeight())))
				&& ((this.getWheelBalanceLabor() == castOther
						.getWheelBalanceLabor()) || (this
						.getWheelBalanceLabor() != null
						&& castOther.getWheelBalanceLabor() != null && this
						.getWheelBalanceLabor().equals(
								castOther.getWheelBalanceLabor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPriceBookId();
		result = 37 * result + (int) this.getLine();
		result = 37 * result
				+ (getValveStem() == null ? 0 : this.getValveStem().hashCode());
		result = 37
				* result
				+ (getWheelBalanceWeight() == null ? 0 : this
						.getWheelBalanceWeight().hashCode());
		result = 37
				* result
				+ (getWheelBalanceLabor() == null ? 0 : this
						.getWheelBalanceLabor().hashCode());
		return result;
	}

}
