package com.bfrc.pojo.pricing;

// Generated Jun 18, 2007 10:31:30 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;

/**
 * TpHierarchyPrice generated by hbm2java
 */
public class TpHierarchyPrice implements java.io.Serializable {

	// Fields    

	private TpHierarchyPriceId id;

	private BigDecimal valveStem;

	private BigDecimal wheelBalanceWeight;

	private BigDecimal wheelBalanceLabor;
	
	private BigDecimal roadHazardPercent;


	private BigDecimal roadHazardMinAmount;
	

	// Constructors

	/** default constructor */
	public TpHierarchyPrice() {
	}

	/** full constructor */
	public TpHierarchyPrice(TpHierarchyPriceId id, BigDecimal valveStem,
			BigDecimal wheelBalanceWeight, BigDecimal wheelBalanceLabor) {
		this.id = id;
		this.valveStem = valveStem;
		this.wheelBalanceWeight = wheelBalanceWeight;
		this.wheelBalanceLabor = wheelBalanceLabor;
	}

	/** updatred full constructor */
	public TpHierarchyPrice(TpHierarchyPriceId id, BigDecimal valveStem,
			BigDecimal wheelBalanceWeight, BigDecimal wheelBalanceLabor,BigDecimal roadHazardPercent,BigDecimal roadHazardMinAmount) {
		this.id = id;
		this.valveStem = valveStem;
		this.wheelBalanceWeight = wheelBalanceWeight;
		this.wheelBalanceLabor = wheelBalanceLabor;
		this.roadHazardPercent = roadHazardPercent;
		this.roadHazardMinAmount = roadHazardMinAmount;
	}
	
	// Property accessors
	public TpHierarchyPriceId getId() {
		return this.id;
	}

	public void setId(TpHierarchyPriceId id) {
		this.id = id;
	}

	public BigDecimal getValveStem() {
		return this.valveStem;
	}

	public void setValveStem(BigDecimal valveStem) {
		this.valveStem = valveStem;
	}

	public BigDecimal getWheelBalanceWeight() {
		return this.wheelBalanceWeight;
	}

	public void setWheelBalanceWeight(BigDecimal wheelBalanceWeight) {
		this.wheelBalanceWeight = wheelBalanceWeight;
	}

	public BigDecimal getWheelBalanceLabor() {
		return this.wheelBalanceLabor;
	}

	public void setWheelBalanceLabor(BigDecimal wheelBalanceLabor) {
		this.wheelBalanceLabor = wheelBalanceLabor;
	}
	
	public BigDecimal getRoadHazardPercent() {
		return this.roadHazardPercent;
	}

	public void setRoadHazardPercent(BigDecimal roadHazardPercent) {
		this.roadHazardPercent = roadHazardPercent;
	}
	
	
	public BigDecimal getRoadHazardMinAmount() {
		return this.roadHazardMinAmount;
	}

	public void setRoadHazardMinAmount(BigDecimal roadHazardMinAmount) {
		this.roadHazardMinAmount = roadHazardMinAmount;
	}
	
	
}
