package com.bfrc.pojo.pricing;

// Generated Jun 18, 2007 10:31:30 AM by Hibernate Tools 3.2.0.beta8

/**
 * TpHierarchyPriceId generated by hbm2java
 */
public class TpHierarchyPriceId implements java.io.Serializable {

	// Fields    

	private long priceBookId;

	private long line;

	// Constructors

	/** default constructor */
	public TpHierarchyPriceId() {
	}

	/** full constructor */
	public TpHierarchyPriceId(long priceBookId, long line) {
		this.priceBookId = priceBookId;
		this.line = line;
	}

	// Property accessors
	public long getPriceBookId() {
		return this.priceBookId;
	}

	public void setPriceBookId(long priceBookId) {
		this.priceBookId = priceBookId;
	}

	public long getLine() {
		return this.line;
	}

	public void setLine(long line) {
		this.line = line;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TpHierarchyPriceId))
			return false;
		TpHierarchyPriceId castOther = (TpHierarchyPriceId) other;

		return (this.getPriceBookId() == castOther.getPriceBookId())
				&& (this.getLine() == castOther.getLine());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPriceBookId();
		result = 37 * result + (int) this.getLine();
		return result;
	}

}
