package com.bfrc.pojo.pricing;

// Generated Jun 18, 2007 10:31:30 AM by Hibernate Tools 3.2.0.beta8

/**
 * TpHierarchyPriceTest generated by hbm2java
 */
public class TpHierarchyPriceTest implements java.io.Serializable {

	// Fields    

	private TpHierarchyPriceTestId id;

	// Constructors

	/** default constructor */
	public TpHierarchyPriceTest() {
	}

	/** full constructor */
	public TpHierarchyPriceTest(TpHierarchyPriceTestId id) {
		this.id = id;
	}

	// Property accessors
	public TpHierarchyPriceTestId getId() {
		return this.id;
	}

	public void setId(TpHierarchyPriceTestId id) {
		this.id = id;
	}

}
