package com.bfrc.pojo.pricing;

// Generated Jun 18, 2007 10:31:30 AM by Hibernate Tools 3.2.0.beta8

/**
 * TpStoreListId generated by hbm2java
 */
public class TpStoreListId implements java.io.Serializable {

	// Fields    

	private long priceBookId;

	private long storeNumber;

	// Constructors

	/** default constructor */
	public TpStoreListId() {
	}

	/** full constructor */
	public TpStoreListId(long priceBookId, long storeNumber) {
		this.priceBookId = priceBookId;
		this.storeNumber = storeNumber;
	}

	// Property accessors
	public long getPriceBookId() {
		return this.priceBookId;
	}

	public void setPriceBookId(long priceBookId) {
		this.priceBookId = priceBookId;
	}

	public long getStoreNumber() {
		return this.storeNumber;
	}

	public void setStoreNumber(long storeNumber) {
		this.storeNumber = storeNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TpStoreListId))
			return false;
		TpStoreListId castOther = (TpStoreListId) other;

		return (this.getPriceBookId() == castOther.getPriceBookId())
				&& (this.getStoreNumber() == castOther.getStoreNumber());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPriceBookId();
		result = 37 * result + (int) this.getStoreNumber();
		return result;
	}

}
