package com.bfrc.pojo.pricing;

// Generated Jun 18, 2007 10:31:30 AM by Hibernate Tools 3.2.0.beta8

/**
 * TpSuppressionBrandId generated by hbm2java
 */
public class TpSuppressionBrandId implements java.io.Serializable {

	// Fields    

	private long suppressionId;

	private long brandId;

	// Constructors

	/** default constructor */
	public TpSuppressionBrandId() {
	}

	/** full constructor */
	public TpSuppressionBrandId(long suppressionId, long brandId) {
		this.suppressionId = suppressionId;
		this.brandId = brandId;
	}

	// Property accessors
	public long getSuppressionId() {
		return this.suppressionId;
	}

	public void setSuppressionId(long suppressionId) {
		this.suppressionId = suppressionId;
	}

	public long getBrandId() {
		return this.brandId;
	}

	public void setBrandId(long brandId) {
		this.brandId = brandId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TpSuppressionBrandId))
			return false;
		TpSuppressionBrandId castOther = (TpSuppressionBrandId) other;

		return (this.getSuppressionId() == castOther.getSuppressionId())
				&& (this.getBrandId() == castOther.getBrandId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getSuppressionId();
		result = 37 * result + (int) this.getBrandId();
		return result;
	}

}
