package com.bfrc.pojo.pricing;

// Generated Jun 18, 2007 10:31:30 AM by Hibernate Tools 3.2.0.beta8

/**
 * TpTireFeeId generated by hbm2java
 */
public class TpTaxDescId implements java.io.Serializable {

	// Fields    

	private long storeNumber;

	private long counter;

	// Constructors

	/** default constructor */
	public TpTaxDescId() {
	}

	/** full constructor */
	public TpTaxDescId(long storeNumber, long counter) {
		this.storeNumber = storeNumber;
		this.counter = counter;
	}

	// Property accessors
	public long getStoreNumber() {
		return this.storeNumber;
	}

	public void setStoreNumber(long storeNumber) {
		this.storeNumber = storeNumber;
	}

	public long getCounter() {
		return this.counter;
	}

	public void setCounter(long counter) {
		this.counter = counter;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TpTaxDescId))
			return false;
		TpTaxDescId castOther = (TpTaxDescId) other;

		return (this.getStoreNumber() == castOther.getStoreNumber())
				&& (this.getCounter() == castOther.getCounter());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getStoreNumber();
		result = 37 * result + (int) this.getCounter();
		return result;
	}

}
