package com.bfrc.pojo.pricing;

// Generated Jun 18, 2007 10:31:30 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;

/**
 * TpTireFee generated by hbm2java
 */
public class TpTireFee implements java.io.Serializable {

	// Fields    

	private TpTireFeeId id;

	private String description;

	private BigDecimal amount;

	private BigDecimal percent;

	private long article;

	// Constructors

	/** default constructor */
	public TpTireFee() {
	}

	/** full constructor */
	public TpTireFee(TpTireFeeId id, String description, BigDecimal amount,
			BigDecimal percent, long article) {
		this.id = id;
		this.description = description;
		this.amount = amount;
		this.percent = percent;
		this.article = article;
	}

	// Property accessors
	public TpTireFeeId getId() {
		return this.id;
	}

	public void setId(TpTireFeeId id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getPercent() {
		return this.percent;
	}

	public void setPercent(BigDecimal percent) {
		this.percent = percent;
	}

	public long getArticle() {
		return this.article;
	}

	public void setArticle(long article) {
		this.article = article;
	}

}
