package com.bfrc.pojo.pricing;

// Generated Jun 18, 2007 10:31:30 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * TpTirePrice generated by hbm2java
 */
public class TpTirePrice implements java.io.Serializable {

	// Fields    

	private TpTirePriceId id;

	private BigDecimal retailPrice;

	private char onsale;

	private Date endDate;

	// Constructors

	/** default constructor */
	public TpTirePrice() {
	}

	/** full constructor */
	public TpTirePrice(TpTirePriceId id, BigDecimal retailPrice, char onsale,
			Date endDate) {
		this.id = id;
		this.retailPrice = retailPrice;
		this.onsale = onsale;
		this.endDate = endDate;
	}

	// Property accessors
	public TpTirePriceId getId() {
		return this.id;
	}

	public void setId(TpTirePriceId id) {
		this.id = id;
	}

	public BigDecimal getRetailPrice() {
		return this.retailPrice;
	}

	public void setRetailPrice(BigDecimal retailPrice) {
		this.retailPrice = retailPrice;
	}

	public char getOnsale() {
		return this.onsale;
	}

	public void setOnsale(char onsale) {
		this.onsale = onsale;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
