package com.bfrc.pojo.pricing;

// Generated Jun 18, 2007 10:31:30 AM by Hibernate Tools 3.2.0.beta8

/**
 * TpTirePriceId generated by hbm2java
 */
public class TpTirePriceId implements java.io.Serializable {

	// Fields    

	private long priceBookId;

	private long article;

	// Constructors

	/** default constructor */
	public TpTirePriceId() {
	}

	/** full constructor */
	public TpTirePriceId(long priceBookId, long article) {
		this.priceBookId = priceBookId;
		this.article = article;
	}

	// Property accessors
	public long getPriceBookId() {
		return this.priceBookId;
	}

	public void setPriceBookId(long priceBookId) {
		this.priceBookId = priceBookId;
	}

	public long getArticle() {
		return this.article;
	}

	public void setArticle(long article) {
		this.article = article;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TpTirePriceId))
			return false;
		TpTirePriceId castOther = (TpTirePriceId) other;

		return (this.getPriceBookId() == castOther.getPriceBookId())
				&& (this.getArticle() == castOther.getArticle());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPriceBookId();
		result = 37 * result + (int) this.getArticle();
		return result;
	}

}
