package com.bfrc.pojo.pricing;

// Generated Jun 18, 2007 10:31:30 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;

/**
 * TpTireMaster generated by hbm2java
 */
public class TpTireMaster implements java.io.Serializable {

	// Fields    

	private long article;

	private String description;

	private long line;

	private long feeTypeCode;

	private BigDecimal exciseTax;
	
	private long itaxCode;

	// Constructors

	/** default constructor */
	public TpTireMaster() {
	}

	/** full constructor */
	public TpTireMaster(long article, String description, long line,
			long feeTypeCode, BigDecimal exciseTax) {
		this.article = article;
		this.description = description;
		this.line = line;
		this.feeTypeCode = feeTypeCode;
		this.exciseTax = exciseTax;
	}

	// Property accessors
	public long getArticle() {
		return this.article;
	}

	public void setArticle(long article) {
		this.article = article;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public long getLine() {
		return this.line;
	}

	public void setLine(long line) {
		this.line = line;
	}

	public long getFeeTypeCode() {
		return this.feeTypeCode;
	}

	public void setFeeTypeCode(long feeTypeCode) {
		this.feeTypeCode = feeTypeCode;
	}

	public BigDecimal getExciseTax() {
		return this.exciseTax;
	}

	public void setExciseTax(BigDecimal exciseTax) {
		this.exciseTax = exciseTax;
	}
	
	public long getItaxCode() {
		return this.itaxCode;
	}

	public void setItaxCode(long itaxCode) {
		this.itaxCode = itaxCode;
	}
	

}
