package com.bfrc.pojo.pricing;

import java.util.Date;

import com.bfrc.framework.util.StringUtils;

// Generated Jun 18, 2007 10:31:30 AM by Hibernate Tools 3.2.0.beta8

/**
 * TpUserLog generated by hbm2java
 */
public class TpUserLog implements java.io.Serializable {

	// Fields    

	private long tpUserId;

	private String emailAddress;

	private Date requestDate;

	private long storeNumber;

	private String firstName;

	private String lastName;

	private long quantity;

	private String modelYear;

	private String makeName;

	private String modelName;

	private String submodel;
	
	private String webSite;
	
	private Long rearQuantity;

	// Constructors

	/** default constructor */
	public TpUserLog() {
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getFirstName() {
		return StringUtils.userNameFilter(this.firstName,50);
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return StringUtils.userNameFilter(this.lastName,80);
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getMakeName() {
		return this.makeName;
	}

	public void setMakeName(String makeName) {
		this.makeName = makeName;
	}

	public String getModelName() {
		return this.modelName;
	}

	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	public String getModelYear() {
		return this.modelYear;
	}

	public void setModelYear(String modelYear) {
		this.modelYear = modelYear;
	}

	public long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(long quantity) {
		this.quantity = quantity;
	}

	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	public long getStoreNumber() {
		return this.storeNumber;
	}

	public void setStoreNumber(long storeNumber) {
		this.storeNumber = storeNumber;
	}

	public String getSubmodel() {
		return this.submodel;
	}

	public void setSubmodel(String submodel) {
		this.submodel = submodel;
	}

	public long getTpUserId() {
		return this.tpUserId;
	}

	public void setTpUserId(long tpUserId) {
		this.tpUserId = tpUserId;
	}

	public String getWebSite() {
        return this.webSite;
    }
    
    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }

	public Long getRearQuantity() {
		return rearQuantity;
	}

	public void setRearQuantity(Long rearQuantity) {
		this.rearQuantity = rearQuantity;
	}

}
