package com.bfrc.pojo.contact;

// Generated Jan 9, 2007 10:55:22 PM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable {

	// Fields    

	private int contactId;

	private String contactName;

	private String contactEmail;

	private Set bfrcWebSiteFeedbackContacts = new HashSet(0);

	// Constructors

	/** default constructor */
	public Contact() {
	}

	/** minimal constructor */
	public Contact(int contactId) {
		this.contactId = contactId;
	}

	/** full constructor */
	public Contact(int contactId, String contactName,
			String contactEmail, Set bfrcWebSiteFeedbackContacts) {
		this.contactId = contactId;
		this.contactName = contactName;
		this.contactEmail = contactEmail;
		this.bfrcWebSiteFeedbackContacts = bfrcWebSiteFeedbackContacts;
	}

	// Property accessors
	public int getContactId() {
		return this.contactId;
	}

	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

	public String getName() {
		return this.contactName;
	}

	public void setName(String contactName) {
		this.contactName = contactName;
	}

	public String getEmail() {
		return this.contactEmail;
	}

	public void setEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	public Set getFeedbackContacts() {
		return this.bfrcWebSiteFeedbackContacts;
	}

	public void setFeedbackContacts(Set bfrcWebSiteFeedbackContacts) {
		this.bfrcWebSiteFeedbackContacts = bfrcWebSiteFeedbackContacts;
	}

}
