package com.bfrc.pojo.contact;

// Generated Jan 9, 2007 10:55:22 PM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * ContactType generated by hbm2java
 */
public class ContactType implements java.io.Serializable {

	// Fields    

	private int contactTypeId;

	private String contactTypeName;

	private Set bfrcWebSiteFeedbackContacts = new HashSet(0);

	// Constructors

	/** default constructor */
	public ContactType() {
	}

	/** minimal constructor */
	public ContactType(int contactTypeId) {
		this.contactTypeId = contactTypeId;
	}

	/** full constructor */
	public ContactType(int contactTypeId, String contactTypeName,
			Set bfrcWebSiteFeedbackContacts) {
		this.contactTypeId = contactTypeId;
		this.contactTypeName = contactTypeName;
		this.bfrcWebSiteFeedbackContacts = bfrcWebSiteFeedbackContacts;
	}

	// Property accessors
	public int getContactTypeId() {
		return this.contactTypeId;
	}

	public void setContactTypeId(int contactTypeId) {
		this.contactTypeId = contactTypeId;
	}

	public String getName() {
		return this.contactTypeName;
	}

	public void setName(String contactTypeName) {
		this.contactTypeName = contactTypeName;
	}

	public Set getContacts() {
		return this.bfrcWebSiteFeedbackContacts;
	}

	public void setContacts(Set bfrcWebSiteFeedbackContacts) {
		this.bfrcWebSiteFeedbackContacts = bfrcWebSiteFeedbackContacts;
	}

}
