package com.bfrc.pojo.contact;

// Generated Jan 9, 2007 10:55:22 PM by Hibernate Tools 3.2.0.beta8

/**
 * FeedbackContact generated by hbm2java
 */
public class FeedbackContact implements java.io.Serializable {

	// Fields    

	private FeedbackContactId id;

	private Contact bfrcWebSiteContact;

	private Feedback bfrcWebSiteFeedback;

	private ContactType bfrcWebSiteContactType;

	// Constructors

	/** default constructor */
	public FeedbackContact() {
	}

	/** minimal constructor */
	public FeedbackContact(FeedbackContactId id) {
		this.id = id;
	}

	/** full constructor */
	public FeedbackContact(FeedbackContactId id,
			Contact bfrcWebSiteContact,
			Feedback bfrcWebSiteFeedback,
			ContactType bfrcWebSiteContactType) {
		this.id = id;
		this.bfrcWebSiteContact = bfrcWebSiteContact;
		this.bfrcWebSiteFeedback = bfrcWebSiteFeedback;
		this.bfrcWebSiteContactType = bfrcWebSiteContactType;
	}

	// Property accessors
	public FeedbackContactId getId() {
		return this.id;
	}

	public void setId(FeedbackContactId id) {
		this.id = id;
	}

	public Contact getContact() {
		return this.bfrcWebSiteContact;
	}

	public void setContact(Contact bfrcWebSiteContact) {
		this.bfrcWebSiteContact = bfrcWebSiteContact;
	}

	public Feedback getFeedback() {
		return this.bfrcWebSiteFeedback;
	}

	public void setFeedback(Feedback bfrcWebSiteFeedback) {
		this.bfrcWebSiteFeedback = bfrcWebSiteFeedback;
	}

	public ContactType getContactType() {
		return this.bfrcWebSiteContactType;
	}

	public void setContactType(
			ContactType bfrcWebSiteContactType) {
		this.bfrcWebSiteContactType = bfrcWebSiteContactType;
	}

}
