package com.bfrc.pojo.contact;

// Generated Jan 9, 2007 10:55:22 PM by Hibernate Tools 3.2.0.beta8

/**
 * FeedbackType generated by hbm2java
 */
public class FeedbackType implements java.io.Serializable {

	// Fields    

	private int feedbackTypeId;

	private String feedbackTypeName;

	// Constructors

	/** default constructor */
	public FeedbackType() {
	}

	/** minimal constructor */
	public FeedbackType(int feedbackTypeId) {
		this.feedbackTypeId = feedbackTypeId;
	}

	/** full constructor */
	public FeedbackType(int feedbackTypeId, String feedbackTypeName) {
		this.feedbackTypeId = feedbackTypeId;
		this.feedbackTypeName = feedbackTypeName;
	}

	// Property accessors
	public int getFeedbackTypeId() {
		return this.feedbackTypeId;
	}

	public void setFeedbackTypeId(int feedbackTypeId) {
		this.feedbackTypeId = feedbackTypeId;
	}

	public String getName() {
		return this.feedbackTypeName;
	}

	public void setName(String feedbackTypeName) {
		this.feedbackTypeName = feedbackTypeName;
	}

}
