package com.bfrc.pojo.contact;

// Generated Jan 9, 2007 10:55:22 PM by Hibernate Tools 3.2.0.beta8

import org.codehaus.jackson.map.annotate.JsonSerialize;
import org.codehaus.jackson.map.ser.ToStringSerializer;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Feedback generated by hbm2java
 */
public class MainFeedback implements java.io.Serializable {

	// Fields    

	private int mainFeedbackId;
	private String feedbackSubject;

	// Constructors

	/** default constructor */
	public MainFeedback() {
	}

	/** minimal constructor */
	public MainFeedback(int mainFeedbackId) {
		this.mainFeedbackId = mainFeedbackId;
	}

	/** full constructor */
	public MainFeedback(int mainFeedbackId, String feedbackSubject) {
		this.mainFeedbackId = mainFeedbackId;
		this.feedbackSubject = feedbackSubject;
	}

	// Property accessors   
	@JsonSerialize(using=ToStringSerializer.class)
	@JsonProperty("id")
	public int getMainFeedbackId() {
		return mainFeedbackId;
	}

	public void setMainFeedbackId(int mainFeedbackId) {
		this.mainFeedbackId = mainFeedbackId;
	}

	@JsonProperty("subject")
	public String getFeedbackSubject() {
		return feedbackSubject;
	}

	public void setFeedbackSubject(String feedbackSubject) {
		this.feedbackSubject = feedbackSubject;
	}

}
