package com.bfrc.pojo.geo;



/**
 * DistrictManagerId generated by hbm2java
 */

public class DistrictManagerId  implements java.io.Serializable {


    // Fields    

     private String districtId;
     private String managerType;
     private String name;


    // Constructors

    /** default constructor */
    public DistrictManagerId() {
    }
    

    

   
    // Property accessors

    public String getDistrictId() {
        return this.districtId;
    }
    
    public void setDistrictId(String districtId) {
        this.districtId = districtId;
    }

    public String getManagerType() {
        return this.managerType;
    }
    
    public void setManagerType(String managerType) {
        this.managerType = managerType;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DistrictManagerId) ) return false;
		 DistrictManagerId castOther = ( DistrictManagerId ) other; 
         
		 return ( (this.getDistrictId()==castOther.getDistrictId()) || ( this.getDistrictId()!=null && castOther.getDistrictId()!=null && this.getDistrictId().equals(castOther.getDistrictId()) ) )
 && ( (this.getManagerType()==castOther.getManagerType()) || ( this.getManagerType()!=null && castOther.getManagerType()!=null && this.getManagerType().equals(castOther.getManagerType()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDistrictId() == null ? 0 : this.getDistrictId().hashCode() );
         result = 37 * result + ( getManagerType() == null ? 0 : this.getManagerType().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         return result;
   }   





}