package com.bfrc.pojo.geo;


/**
 * LocatorLogId generated by hbm2java
 */

public class LocatorLogId  implements java.io.Serializable {


    // Fields    

     private Long requestId;
     private String requestType;


    // Constructors

    /** default constructor */
    public LocatorLogId() {
    }
    

    

   
    // Property accessors

    public String getRequestType() {
        return this.requestType;
    }
    
    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LocatorLogId) ) return false;
		 LocatorLogId castOther = ( LocatorLogId ) other; 
         
		 return ( (this.getRequestId()==castOther.getRequestId()) || ( this.getRequestId()!=null && castOther.getRequestId()!=null && this.getRequestId().equals(castOther.getRequestId()) ) )
 && ( (this.getRequestType()==castOther.getRequestType()) || ( this.getRequestType()!=null && castOther.getRequestType()!=null && this.getRequestType().equals(castOther.getRequestType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRequestId() == null ? 0 : this.getRequestId().hashCode() );
         result = 37 * result + ( getRequestType() == null ? 0 : this.getRequestType().hashCode() );
         return result;
   }   





	/**
	 * Returns the requestId.
	 * @return Long
	 */
	public Long getRequestId() {
		return this.requestId;
	}

	/**
	 * Sets the requestId.
	 * @param requestId The requestId to set
	 */
	public void setRequestId(Long requestId) {
		this.requestId = requestId;
	}

}