package com.bfrc.pojo.geo;

import java.util.Date;

/**
 * LocatorLog generated by hbm2java
 */

public class LocatorLog  implements java.io.Serializable {


    // Fields    

     private LocatorLogId id;
     private Long interval;
     private String serverIp;
     private String street;
     private String city;
     private String state;
     private String zip;
     private Long storeNumber;
     private String appName;
     private String remoteIp;
     private Date createdDate;


    // Constructors

    /** default constructor */
    public LocatorLog() {
    }
    
    /** constructor with id */
    public LocatorLog(LocatorLogId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public LocatorLogId getId() {
        return this.id;
    }
    
    public void setId(LocatorLogId id) {
        this.id = id;
    }
   








	/**
	 * Returns the interval.
	 * @return Long
	 */
	public Long getInterval() {
		return this.interval;
	}

	/**
	 * Sets the interval.
	 * @param interval The interval to set
	 */
	public void setInterval(Long interval) {
		this.interval = interval;
	}

    public String getRemoteIp() {
        return this.remoteIp;
    }
    
    public void setRemoteIp(String remoteIp) {
        this.remoteIp = remoteIp;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public String getServerIp() {
        return this.serverIp;
    }
    
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp;
    }

    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    public Long getStoreNumber() {
        return this.storeNumber;
    }
    
    public void setStoreNumber(Long storeNumber) {
        this.storeNumber = storeNumber;
    }

    public String getAppName() {
        return this.appName;
    }
    
    public void setAppName(String appName) {
        this.appName = appName;
    }
}