package com.bfrc.pojo.geo;



/**
 * States generated by hbm2java
 */

public class States  implements java.io.Serializable {


    // Fields    

     private String state;
     private String name;


    // Constructors

    /** default constructor */
    public States() {
    }
    
    /** constructor with id */
    public States(String state) {
        this.state = state;
    }

    

   
    // Property accessors

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
   








}