package com.bfrc.pojo.geo;



/**
 * ZoneManager generated by hbm2java
 */

public class ZoneManager  implements java.io.Serializable {


    // Fields    

     private ZoneManagerId id;
     private String name;
     private String emailAddress;


    // Constructors

    /** default constructor */
    public ZoneManager() {
    }
    
    /** constructor with id */
    public ZoneManager(ZoneManagerId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public ZoneManagerId getId() {
        return this.id;
    }
    
    public void setId(ZoneManagerId id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
   








}