package com.bfrc.pojo.geo;



/**
 * ZoneList generated by hbm2java
 */

public class ZoneList  implements java.io.Serializable {


    // Fields    

     private Byte zoneId;
     private String zoneName;


    // Constructors

    /** default constructor */
    public ZoneList() {
    }
    
    /** constructor with id */
    public ZoneList(Byte zoneId) {
        this.zoneId = zoneId;
    }

    

   
    // Property accessors

    public Byte getZoneId() {
        return this.zoneId;
    }
    
    public void setZoneId(Byte zoneId) {
        this.zoneId = zoneId;
    }

    public String getZoneName() {
        return this.zoneName;
    }
    
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName;
    }
   








}