package com.bfrc.pojo.geo;



/**
 * ZoneManagerId generated by hbm2java
 */

public class ZoneManagerId  implements java.io.Serializable {


    // Fields    

     private Byte zoneId;
     private String managerType;


    // Constructors

    /** default constructor */
    public ZoneManagerId() {
    }
    

    

   
    // Property accessors

    public Byte getZoneId() {
        return this.zoneId;
    }
    
    public void setZoneId(Byte zoneId) {
        this.zoneId = zoneId;
    }

    public String getManagerType() {
        return this.managerType;
    }
    
    public void setManagerType(String managerType) {
        this.managerType = managerType;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ZoneManagerId) ) return false;
		 ZoneManagerId castOther = ( ZoneManagerId ) other; 
         
		 return (this.getZoneId()==castOther.getZoneId())
 && ( (this.getManagerType()==castOther.getManagerType()) || ( this.getManagerType()!=null && castOther.getManagerType()!=null && this.getManagerType().equals(castOther.getManagerType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getZoneId().intValue();
         result = 37 * result + ( getManagerType() == null ? 0 : this.getManagerType().hashCode() );
         return result;
   }   





}