package com.bfrc.pojo.reward;
// Generated Aug 9, 2010 5:03:37 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Emailcollection generated by hbm2java
 */
public class Emailcollection  implements java.io.Serializable {


     private String tendigitcode;
     private String firstname;
     private String lastname;
     private String email;
     private String bestCustomer;
     private Date modifiedDate;

    public Emailcollection() {
    }

	
    public Emailcollection(String tendigitcode) {
        this.tendigitcode = tendigitcode;
    }
    public Emailcollection(String tendigitcode, String firstname, String lastname, String email, String bestCustomer, Date modifiedDate) {
       this.tendigitcode = tendigitcode;
       this.firstname = firstname;
       this.lastname = lastname;
       this.email = email;
       this.bestCustomer = bestCustomer;
       this.modifiedDate = modifiedDate;
    }
   
    public String getTendigitcode() {
        return this.tendigitcode;
    }
    
    public void setTendigitcode(String tendigitcode) {
        this.tendigitcode = tendigitcode;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getBestCustomer() {
        return this.bestCustomer;
    }
    
    public void setBestCustomer(String bestCustomer) {
        this.bestCustomer = bestCustomer;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


