package com.bsro.databean.tire;


import java.util.List;
import java.util.Map;

//import com.bfrc.pojo.tire.jda2.Display;
import com.bsro.databean.BaseDataBean;

/**
 * User generated by hbm2java
 */

public class LocalPageDataBean extends  BaseDataBean {
    
	/**
	 * 
	 */
	private String paragragh1;
	private String paragragh2;
	private String paragragh3;
	
	private String header1Sentence1;
	private String header1Sentence2;

	private String header2Sentence1;
	private String header2Sentence2;
	private List header2Sentence3;
	private List header2Sentence4;
	
	
	public String getHeader1Sentence1(){
		return this.header1Sentence1;
	}
	public void setHeader1Sentence1(String header1Sentence1){
		this.header1Sentence1 = header1Sentence1;
	}
	
	public String getHeader1Sentence2(){
		return this.header1Sentence2;
	}
	public void setHeader1Sentence2(String header1Sentence2){
		this.header1Sentence2 = header1Sentence2;
	}
	
	public String getHeader2Sentence1(){
		return this.header2Sentence1;
	}
	public void setHeader2Sentence1(String header2Sentence1){
		this.header2Sentence1 = header2Sentence1;
	}
	
	public String getHeader2Sentence2(){
		return this.header2Sentence2;
	}
	public void setHeader2Sentence2(String header2Sentence2){
		this.header2Sentence2 = header2Sentence2;
	}
	
	public List getHeader2Sentence3(){
		return this.header2Sentence3;
	}
	public void setHeader2Sentence3(List header2Sentence3){
		this.header2Sentence3 = header2Sentence3;
	}
	
	public List getHeader2Sentence4(){
		return this.header2Sentence4;
	}
	public void setHeader2Sentence4(List header2Sentence4){
		this.header2Sentence4 = header2Sentence4;
	}
	
	public String getParagragh1(){
		return this.paragragh1;
	}
	public void setParagragh1(String paragragh1){
		this.paragragh1 = paragragh1;
	}
	
	public String getParagragh2(){
		return this.paragragh2;
	}
	public void setParagragh2(String paragragh2){
		this.paragragh2 = paragragh2;
	}
	
	
	public String getParagragh3(){
		return this.paragragh3;
	}
	public void setParagragh3(String paragragh3){
		this.paragragh3 = paragragh3;
	}
	
}
